import { defineCurriculum } from "@repo/contents/_types/curriculum/schema";
import { LEARNING_PROGRAM_KEYS } from "@repo/contents/_types/program/catalog";

const classTranslations = {
  class10: {
    en: { title: "Class 10" },
    id: { title: "Kelas 10" },
  },
  class11: {
    en: { title: "Class 11" },
    id: { title: "Kelas 11" },
  },
  class12: {
    en: { title: "Class 12" },
    id: { title: "Kelas 12" },
  },
  class7: {
    en: { title: "Class 7" },
    id: { title: "Kelas 7" },
  },
  class8: {
    en: { title: "Class 8" },
    id: { title: "Kelas 8" },
  },
  class9: {
    en: { title: "Class 9" },
    id: { title: "Kelas 9" },
  },
};

const subjectTranslations = {
  biology: {
    en: { title: "Biology" },
    id: { title: "Biologi" },
  },
  chemistry: {
    en: { title: "Chemistry" },
    id: { title: "Kimia" },
  },
  economy: {
    en: { title: "Economics" },
    id: { title: "Ekonomi" },
  },
  geography: {
    en: { title: "Geography" },
    id: { title: "Geografi" },
  },
  history: {
    en: { title: "History" },
    id: { title: "Sejarah" },
  },
  mathematics: {
    en: { title: "Mathematics" },
    id: { title: "Matematika" },
  },
  physics: {
    en: { title: "Physics" },
    id: { title: "Fisika" },
  },
  sociology: {
    en: { title: "Sociology" },
    id: { title: "Sosiologi" },
  },
};

export const indonesiaMerdekaCurriculum = defineCurriculum({
  programKey: LEARNING_PROGRAM_KEYS.indonesiaMerdekaCurriculum,
  nodes: [
    {
      key: "class-7",
      level: "class",
      materialKeys: [],
      order: 70,
      translations: classTranslations.class7,
    },
    {
      key: "class-7-mathematics",
      level: "subject",
      materialKeys: ["subject.middle-school.7.mathematics"],
      order: 10,
      parentKey: "class-7",
      translations: subjectTranslations.mathematics,
    },
    {
      key: "class-8",
      level: "class",
      materialKeys: [],
      order: 80,
      translations: classTranslations.class8,
    },
    {
      key: "class-8-mathematics",
      level: "subject",
      materialKeys: ["subject.middle-school.8.mathematics"],
      order: 10,
      parentKey: "class-8",
      translations: subjectTranslations.mathematics,
    },
    {
      key: "class-9",
      level: "class",
      materialKeys: [],
      order: 90,
      translations: classTranslations.class9,
    },
    {
      key: "class-9-mathematics",
      level: "subject",
      materialKeys: ["subject.middle-school.9.mathematics"],
      order: 10,
      parentKey: "class-9",
      translations: subjectTranslations.mathematics,
    },
    {
      key: "class-10",
      level: "class",
      materialKeys: [],
      order: 100,
      translations: classTranslations.class10,
    },
    {
      key: "class-10-biology",
      level: "subject",
      materialKeys: ["subject.high-school.10.biology"],
      order: 10,
      parentKey: "class-10",
      translations: subjectTranslations.biology,
    },
    {
      key: "class-10-chemistry",
      level: "subject",
      materialKeys: ["subject.high-school.10.chemistry"],
      order: 20,
      parentKey: "class-10",
      translations: subjectTranslations.chemistry,
    },
    {
      key: "class-10-history",
      level: "subject",
      materialKeys: ["subject.high-school.10.history"],
      order: 30,
      parentKey: "class-10",
      translations: subjectTranslations.history,
    },
    {
      key: "class-10-mathematics",
      level: "subject",
      materialKeys: ["subject.high-school.10.mathematics"],
      order: 40,
      parentKey: "class-10",
      translations: subjectTranslations.mathematics,
    },
    {
      key: "class-10-physics",
      level: "subject",
      materialKeys: ["subject.high-school.10.physics"],
      order: 50,
      parentKey: "class-10",
      translations: subjectTranslations.physics,
    },
    {
      key: "class-11",
      level: "class",
      materialKeys: [],
      order: 110,
      translations: classTranslations.class11,
    },
    {
      key: "class-11-biology",
      level: "subject",
      materialKeys: ["subject.high-school.11.biology"],
      order: 10,
      parentKey: "class-11",
      translations: subjectTranslations.biology,
    },
    {
      key: "class-11-chemistry",
      level: "subject",
      materialKeys: ["subject.high-school.11.chemistry"],
      order: 20,
      parentKey: "class-11",
      translations: subjectTranslations.chemistry,
    },
    {
      key: "class-11-economy",
      level: "subject",
      materialKeys: ["subject.high-school.11.economy"],
      order: 30,
      parentKey: "class-11",
      translations: subjectTranslations.economy,
    },
    {
      key: "class-11-geography",
      level: "subject",
      materialKeys: ["subject.high-school.11.geography"],
      order: 40,
      parentKey: "class-11",
      translations: subjectTranslations.geography,
    },
    {
      key: "class-11-history",
      level: "subject",
      materialKeys: ["subject.high-school.11.history"],
      order: 50,
      parentKey: "class-11",
      translations: subjectTranslations.history,
    },
    {
      key: "class-11-mathematics",
      level: "subject",
      materialKeys: ["subject.high-school.11.mathematics"],
      order: 60,
      parentKey: "class-11",
      translations: subjectTranslations.mathematics,
    },
    {
      key: "class-11-physics",
      level: "subject",
      materialKeys: ["subject.high-school.11.physics"],
      order: 70,
      parentKey: "class-11",
      translations: subjectTranslations.physics,
    },
    {
      key: "class-11-sociology",
      level: "subject",
      materialKeys: ["subject.high-school.11.sociology"],
      order: 80,
      parentKey: "class-11",
      translations: subjectTranslations.sociology,
    },
    {
      key: "class-12",
      level: "class",
      materialKeys: [],
      order: 120,
      translations: classTranslations.class12,
    },
    {
      key: "class-12-biology",
      level: "subject",
      materialKeys: ["subject.high-school.12.biology"],
      order: 10,
      parentKey: "class-12",
      translations: subjectTranslations.biology,
    },
    {
      key: "class-12-chemistry",
      level: "subject",
      materialKeys: ["subject.high-school.12.chemistry"],
      order: 20,
      parentKey: "class-12",
      translations: subjectTranslations.chemistry,
    },
    {
      key: "class-12-economy",
      level: "subject",
      materialKeys: ["subject.high-school.12.economy"],
      order: 30,
      parentKey: "class-12",
      translations: subjectTranslations.economy,
    },
    {
      key: "class-12-geography",
      level: "subject",
      materialKeys: ["subject.high-school.12.geography"],
      order: 40,
      parentKey: "class-12",
      translations: subjectTranslations.geography,
    },
    {
      key: "class-12-history",
      level: "subject",
      materialKeys: ["subject.high-school.12.history"],
      order: 50,
      parentKey: "class-12",
      translations: subjectTranslations.history,
    },
    {
      key: "class-12-mathematics",
      level: "subject",
      materialKeys: ["subject.high-school.12.mathematics"],
      order: 60,
      parentKey: "class-12",
      translations: subjectTranslations.mathematics,
    },
    {
      key: "class-12-physics",
      level: "subject",
      materialKeys: ["subject.high-school.12.physics"],
      order: 70,
      parentKey: "class-12",
      translations: subjectTranslations.physics,
    },
    {
      key: "class-12-sociology",
      level: "subject",
      materialKeys: ["subject.high-school.12.sociology"],
      order: 80,
      parentKey: "class-12",
      translations: subjectTranslations.sociology,
    },
  ],
});
