import type {
  ResolvedLine,
  ResolvedLineLabel,
} from "@repo/design-system/components/contents/mathematics/line/spec";
import {
  GRAPH_ANGLE_ARC_SEGMENTS,
  GRAPH_FULL_CIRCLE_SEGMENTS,
} from "@repo/design-system/components/three/helpers/quality";
import { getRadians } from "@repo/math/angles";

type CircleLineLabel = Omit<ResolvedLineLabel, "at"> & {
  progress?: number;
};

interface CircleAngle {
  radius: number;
  startDegrees: number;
  sweepDegrees: number;
}

interface CircleArc extends CircleAngle {
  segments?: number;
}

interface CircleRadius {
  degrees: number;
  radius: number;
}

interface CircleArcLine extends CircleArc {
  color: NonNullable<ResolvedLine["color"]>;
  label?: CircleLineLabel;
  lineWidth?: ResolvedLine["lineWidth"];
}

const FULL_CIRCLE_DEGREES = 360;
const DEFAULT_SEGMENT_LINE_WIDTH = 4;
const DEFAULT_LABEL_PROGRESS = 0.5;

/**
 * Returns one exact XY-plane point on a circle.
 *
 * The caller supplies degrees because Nakafa lessons explain circle arcs with
 * degree measures. Keeping the conversion here prevents each MDX visual from
 * carrying its own degree-to-radian arithmetic.
 */
export function createCirclePoint(radius: number, degrees: number) {
  const normalized =
    ((degrees % FULL_CIRCLE_DEGREES) + FULL_CIRCLE_DEGREES) %
    FULL_CIRCLE_DEGREES;
  if (normalized === 0) {
    return { x: radius, y: 0, z: 0 };
  }
  if (normalized === 90) {
    return { x: 0, y: radius, z: 0 };
  }
  if (normalized === 180) {
    return { x: -radius, y: 0, z: 0 };
  }
  if (normalized === 270) {
    return { x: 0, y: -radius, z: 0 };
  }
  const angle = getRadians(normalized);

  return {
    x: radius * Math.cos(angle),
    y: radius * Math.sin(angle),
    z: 0,
  };
}

/**
 * Samples one directed circle arc from its mathematical start angle and sweep.
 *
 * The first and last points are generated by the same formula as standalone
 * circle points, so labels, radii, chords, and arc endpoints can share the same
 * source instead of patching endpoint coordinates by hand.
 */
export function createCircleArcPoints({
  radius,
  startDegrees,
  sweepDegrees,
  segments = GRAPH_ANGLE_ARC_SEGMENTS,
}: CircleArc) {
  const safeSegments = Math.max(1, segments);

  return Array.from({ length: safeSegments + 1 }, (_, index) =>
    createCirclePoint(
      radius,
      startDegrees + (index / safeSegments) * sweepDegrees
    )
  );
}

/**
 * Builds an analytically sampled arc with an optional progress-based label.
 *
 * MDX lessons should describe where a label belongs along the mathematical arc,
 * not depend on the current number of sampled points. This adapter converts the
 * caller-facing progress value into the renderer's point-index label contract.
 */
export function createCircleArcLine({
  color,
  label,
  lineWidth,
  ...arc
}: CircleArcLine) {
  const points = createCircleArcPoints(arc);

  if (label) {
    return {
      color,
      labels: [createCircleLineLabel(points.length, label)],
      lineWidth,
      points,
      showPoints: false,
      smooth: false,
    };
  }

  return {
    color,
    lineWidth,
    points,
    showPoints: false,
    smooth: false,
  };
}

/**
 * Samples a full circle using the shared graph quality budget.
 *
 * This keeps circular outlines consistent with other math visuals while still
 * allowing lesson-specific radii.
 */
export function createCircleOutlinePoints(radius: number) {
  return createCircleArcPoints({
    radius,
    startDegrees: 0,
    sweepDegrees: FULL_CIRCLE_DEGREES,
    segments: GRAPH_FULL_CIRCLE_SEGMENTS,
  });
}

/**
 * Returns the exact chord endpoints for a circle arc.
 *
 * A chord is a straight segment between the same start and end angles as the
 * arc, so this function intentionally returns only two points.
 */
export function createCircleChordPoints({
  radius,
  startDegrees,
  sweepDegrees,
}: CircleAngle) {
  return [
    createCirclePoint(radius, startDegrees),
    createCirclePoint(radius, startDegrees + sweepDegrees),
  ];
}

/**
 * Returns a radius line from the circle center to one exact circumference
 * point.
 *
 * This keeps radius, chord, and arc endpoints on the same degree-based circle
 * coordinate system instead of duplicating endpoint arithmetic in MDX lessons.
 */
export function createCircleRadiusPoints({ degrees, radius }: CircleRadius) {
  return [{ x: 0, y: 0, z: 0 }, createCirclePoint(radius, degrees)];
}

/**
 * Builds the two line primitives that form a circle segment boundary.
 *
 * The sampled arc and straight chord preserve their mathematical coordinates.
 * Neither path applies spline interpolation to the analytic points.
 */
export function createCircleSegmentBoundaryLines({
  color,
  label,
  lineWidth = DEFAULT_SEGMENT_LINE_WIDTH,
  ...arc
}: CircleArcLine) {
  const chordPoints = createCircleChordPoints(arc);

  return [
    createCircleArcLine({
      color,
      label,
      lineWidth,
      ...arc,
    }),
    {
      color,
      lineWidth,
      points: chordPoints,
      showPoints: false,
      smooth: false,
    },
  ];
}

/**
 * Converts a caller-facing label progress value into the renderer label shape.
 *
 * The returned label deliberately omits progress because LineEquation expects a
 * point index, not a normalized arc position.
 */
function createCircleLineLabel(pointCount: number, label: CircleLineLabel) {
  const { progress = DEFAULT_LABEL_PROGRESS, ...visibleLabel } = label;

  return {
    ...visibleLabel,
    at: getLabelPointIndex(pointCount, progress),
  };
}

/**
 * Maps a label progress value to the nearest generated arc point.
 *
 * Values outside the visible arc are clamped so a caller cannot accidentally
 * request a missing label anchor.
 */
function getLabelPointIndex(pointCount: number, progress: number) {
  const clampedProgress = Math.max(0, Math.min(1, progress));

  return Math.round(clampedProgress * (pointCount - 1));
}
