import registeredFunctions from "@repo/backend/confect/_generated/registered/contentSync";

export const listIntegrityArticleReferencesPage = registeredFunctions.contentSync.queries.integrity.listIntegrityArticleReferencesPage;
export const listIntegrityArticlesPage = registeredFunctions.contentSync.queries.integrity.listIntegrityArticlesPage;
export const listIntegrityContentAuthorsPage = registeredFunctions.contentSync.queries.integrity.listIntegrityContentAuthorsPage;
export const listIntegrityExerciseChoicesPage = registeredFunctions.contentSync.queries.integrity.listIntegrityExerciseChoicesPage;
export const listIntegrityExerciseQuestionsPage = registeredFunctions.contentSync.queries.integrity.listIntegrityExerciseQuestionsPage;
export const listIntegritySubjectSectionsPage = registeredFunctions.contentSync.queries.integrity.listIntegritySubjectSectionsPage;
