export const CONTENT_SYNC_BATCH_LIMITS = {
  articles: 50,
  authors: 50,
  exerciseQuestions: 30,
  exerciseSets: 50,
  staleArticles: 50,
  staleExerciseQuestions: 100,
  staleExerciseSets: 5,
  staleSubjectSections: 50,
  staleSubjectTopics: 20,
  subjectSections: 20,
  subjectTopics: 50,
  tryoutDetectionSets: 500,
  unusedAuthors: 50,
} as const;
