export const CONTENT_SYNC_BATCH_LIMITS = {
  articles: 50,
  articleReferences: 100,
  authors: 50,
  exerciseChoices: 10,
  exerciseQuestions: 30,
  exerciseSets: 50,
  quranSearchDocuments: 50,
  quranSurahs: 50,
  quranVerses: 100,
  staleArticles: 50,
  staleExerciseQuestions: 100,
  staleExerciseSets: 5,
  staleCurriculumLessons: 50,
  staleCurriculumTopics: 20,
  curriculumLessons: 20,
  curriculumTopics: 50,
  generatedAssessmentNodes: 100,
  generatedAssessments: 20,
  generatedCurricula: 20,
  generatedCurriculumMaterials: 200,
  generatedCurriculumNodes: 100,
  generatedMaterialLocales: 100,
  generatedMaterials: 100,
  tryoutDetectionSets: 500,
  unusedAuthors: 50,
} as const;
