export const CONTENT_SYNC_BATCH_LIMITS = {
  articles: 50,
  articleReferences: 100,
  authors: 50,
  quranSearchDocuments: 50,
  quranSurahs: 50,
  quranVerses: 100,
  staleArticles: 50,
  staleCurriculumLessons: 50,
  staleCurriculumTopics: 20,
  curriculumLessons: 20,
  curriculumTopics: 50,
  publicRouteRows: 1000,
  publicRouteShards: 100,
  publicSitemapPages: 100,
  unusedAuthors: 50,
} as const;
