import type { Document } from "@confect/server";
import type schemaDefinition from "./schema";

export type AccountConsentDecisionsDoc = Document.Document<typeof schemaDefinition, "accountConsentDecisions">;
export type AccountConsentsDoc = Document.Document<typeof schemaDefinition, "accountConsents">;
export type AccountDeletionAttemptCancellationsDoc = Document.Document<typeof schemaDefinition, "accountDeletionAttemptCancellations">;
export type AccountDeletionPreparationsDoc = Document.Document<typeof schemaDefinition, "accountDeletionPreparations">;
export type AccountDeletionReceiptsDoc = Document.Document<typeof schemaDefinition, "accountDeletionReceipts">;
export type AccountDeletionSchoolTransfersDoc = Document.Document<typeof schemaDefinition, "accountDeletionSchoolTransfers">;
export type ArticleBucketsDoc = Document.Document<typeof schemaDefinition, "articleBuckets">;
export type ArticleCatalogDoc = Document.Document<typeof schemaDefinition, "articleCatalog">;
export type ArticleCategoriesDoc = Document.Document<typeof schemaDefinition, "articleCategories">;
export type BookmarkCollectionsDoc = Document.Document<typeof schemaDefinition, "bookmarkCollections">;
export type BookmarksDoc = Document.Document<typeof schemaDefinition, "bookmarks">;
export type ChatsDoc = Document.Document<typeof schemaDefinition, "chats">;
export type CommentVotesDoc = Document.Document<typeof schemaDefinition, "commentVotes">;
export type CommentsDoc = Document.Document<typeof schemaDefinition, "comments">;
export type ContentAnalyticsPartitionsDoc = Document.Document<typeof schemaDefinition, "contentAnalyticsPartitions">;
export type ContentArtifactFactsDoc = Document.Document<typeof schemaDefinition, "contentArtifactFacts">;
export type ContentArtifactsDoc = Document.Document<typeof schemaDefinition, "contentArtifacts">;
export type ContentBindingsDoc = Document.Document<typeof schemaDefinition, "contentBindings">;
export type ContentHeadsDoc = Document.Document<typeof schemaDefinition, "contentHeads">;
export type ContentIndexDoc = Document.Document<typeof schemaDefinition, "contentIndex">;
export type ContentItemsDoc = Document.Document<typeof schemaDefinition, "contentItems">;
export type ContentKeysDoc = Document.Document<typeof schemaDefinition, "contentKeys">;
export type ContentModelBuildsDoc = Document.Document<typeof schemaDefinition, "contentModelBuilds">;
export type ContentPathsDoc = Document.Document<typeof schemaDefinition, "contentPaths">;
export type ContentReleasesDoc = Document.Document<typeof schemaDefinition, "contentReleases">;
export type ContentSnapshotsDoc = Document.Document<typeof schemaDefinition, "contentSnapshots">;
export type ContentStateDoc = Document.Document<typeof schemaDefinition, "contentState">;
export type CreditResetPeriodsDoc = Document.Document<typeof schemaDefinition, "creditResetPeriods">;
export type CreditTransactionsDoc = Document.Document<typeof schemaDefinition, "creditTransactions">;
export type CurriculumRoutesDoc = Document.Document<typeof schemaDefinition, "curriculumRoutes">;
export type CustomerDeletionTombstonesDoc = Document.Document<typeof schemaDefinition, "customerDeletionTombstones">;
export type CustomersDoc = Document.Document<typeof schemaDefinition, "customers">;
export type IrtCalibrationRunsDoc = Document.Document<typeof schemaDefinition, "irtCalibrationRuns">;
export type IrtScaleItemsDoc = Document.Document<typeof schemaDefinition, "irtScaleItems">;
export type IrtScaleVersionsDoc = Document.Document<typeof schemaDefinition, "irtScaleVersions">;
export type JournalEntriesDoc = Document.Document<typeof schemaDefinition, "journalEntries">;
export type LearningEngagementQueueDoc = Document.Document<typeof schemaDefinition, "learningEngagementQueue">;
export type LearningPopularityCountersDoc = Document.Document<typeof schemaDefinition, "learningPopularityCounters">;
export type LearningPopularityCyclesDoc = Document.Document<typeof schemaDefinition, "learningPopularityCycles">;
export type LearningPopularitySignalsDoc = Document.Document<typeof schemaDefinition, "learningPopularitySignals">;
export type LearningPopularityViewerSignalsDoc = Document.Document<typeof schemaDefinition, "learningPopularityViewerSignals">;
export type LearningPreferencesDoc = Document.Document<typeof schemaDefinition, "learningPreferences">;
export type LearningViewsDoc = Document.Document<typeof schemaDefinition, "learningViews">;
export type MaterialBucketsDoc = Document.Document<typeof schemaDefinition, "materialBuckets">;
export type MaterialCatalogDoc = Document.Document<typeof schemaDefinition, "materialCatalog">;
export type NinaMemoriesDoc = Document.Document<typeof schemaDefinition, "ninaMemories">;
export type NinaSummariesDoc = Document.Document<typeof schemaDefinition, "ninaSummaries">;
export type NinaTurnsDoc = Document.Document<typeof schemaDefinition, "ninaTurns">;
export type NinaUploadsDoc = Document.Document<typeof schemaDefinition, "ninaUploads">;
export type OnboardingProfilesDoc = Document.Document<typeof schemaDefinition, "onboardingProfiles">;
export type ProgramBucketsDoc = Document.Document<typeof schemaDefinition, "programBuckets">;
export type ProgramCatalogDoc = Document.Document<typeof schemaDefinition, "programCatalog">;
export type QuranRowsDoc = Document.Document<typeof schemaDefinition, "quranRows">;
export type QuranSearchDoc = Document.Document<typeof schemaDefinition, "quranSearch">;
export type SchoolActivityLogsDoc = Document.Document<typeof schemaDefinition, "schoolActivityLogs">;
export type SchoolClassForumPendingUploadsDoc = Document.Document<typeof schemaDefinition, "schoolClassForumPendingUploads">;
export type SchoolClassForumPostAttachmentsDoc = Document.Document<typeof schemaDefinition, "schoolClassForumPostAttachments">;
export type SchoolClassForumPostReactionsDoc = Document.Document<typeof schemaDefinition, "schoolClassForumPostReactions">;
export type SchoolClassForumPostsDoc = Document.Document<typeof schemaDefinition, "schoolClassForumPosts">;
export type SchoolClassForumReactionsDoc = Document.Document<typeof schemaDefinition, "schoolClassForumReactions">;
export type SchoolClassForumReadStatesDoc = Document.Document<typeof schemaDefinition, "schoolClassForumReadStates">;
export type SchoolClassForumsDoc = Document.Document<typeof schemaDefinition, "schoolClassForums">;
export type SchoolClassInviteCodesDoc = Document.Document<typeof schemaDefinition, "schoolClassInviteCodes">;
export type SchoolClassMaterialGroupsDoc = Document.Document<typeof schemaDefinition, "schoolClassMaterialGroups">;
export type SchoolClassMembersDoc = Document.Document<typeof schemaDefinition, "schoolClassMembers">;
export type SchoolClassesDoc = Document.Document<typeof schemaDefinition, "schoolClasses">;
export type SchoolInviteCodesDoc = Document.Document<typeof schemaDefinition, "schoolInviteCodes">;
export type SchoolMembersDoc = Document.Document<typeof schemaDefinition, "schoolMembers">;
export type SchoolsDoc = Document.Document<typeof schemaDefinition, "schools">;
export type SnapshotBatchesDoc = Document.Document<typeof schemaDefinition, "snapshotBatches">;
export type SubscriptionsDoc = Document.Document<typeof schemaDefinition, "subscriptions">;
export type TenantGrantsDoc = Document.Document<typeof schemaDefinition, "tenantGrants">;
export type TenantInvitesDoc = Document.Document<typeof schemaDefinition, "tenantInvites">;
export type TenantPeopleDoc = Document.Document<typeof schemaDefinition, "tenantPeople">;
export type TenantUnitsDoc = Document.Document<typeof schemaDefinition, "tenantUnits">;
export type TenantsDoc = Document.Document<typeof schemaDefinition, "tenants">;
export type TryoutAttemptPlacementsDoc = Document.Document<typeof schemaDefinition, "tryoutAttemptPlacements">;
export type TryoutAttemptsDoc = Document.Document<typeof schemaDefinition, "tryoutAttempts">;
export type TryoutCatalogDoc = Document.Document<typeof schemaDefinition, "tryoutCatalog">;
export type TryoutPlacementsDoc = Document.Document<typeof schemaDefinition, "tryoutPlacements">;
export type TryoutResponsesDoc = Document.Document<typeof schemaDefinition, "tryoutResponses">;
export type TryoutRuntimeBundlesDoc = Document.Document<typeof schemaDefinition, "tryoutRuntimeBundles">;
export type TryoutScoresDoc = Document.Document<typeof schemaDefinition, "tryoutScores">;
export type TryoutSectionAttemptsDoc = Document.Document<typeof schemaDefinition, "tryoutSectionAttempts">;
export type TryoutSetProgressDoc = Document.Document<typeof schemaDefinition, "tryoutSetProgress">;
export type UserLearningRecentsDoc = Document.Document<typeof schemaDefinition, "userLearningRecents">;
export type UsersDoc = Document.Document<typeof schemaDefinition, "users">;
export type WelcomeEmailIntentsDoc = Document.Document<typeof schemaDefinition, "welcomeEmailIntents">;

export interface Docs {
  accountConsentDecisions: AccountConsentDecisionsDoc;
  accountConsents: AccountConsentsDoc;
  accountDeletionAttemptCancellations: AccountDeletionAttemptCancellationsDoc;
  accountDeletionPreparations: AccountDeletionPreparationsDoc;
  accountDeletionReceipts: AccountDeletionReceiptsDoc;
  accountDeletionSchoolTransfers: AccountDeletionSchoolTransfersDoc;
  articleBuckets: ArticleBucketsDoc;
  articleCatalog: ArticleCatalogDoc;
  articleCategories: ArticleCategoriesDoc;
  bookmarkCollections: BookmarkCollectionsDoc;
  bookmarks: BookmarksDoc;
  chats: ChatsDoc;
  commentVotes: CommentVotesDoc;
  comments: CommentsDoc;
  contentAnalyticsPartitions: ContentAnalyticsPartitionsDoc;
  contentArtifactFacts: ContentArtifactFactsDoc;
  contentArtifacts: ContentArtifactsDoc;
  contentBindings: ContentBindingsDoc;
  contentHeads: ContentHeadsDoc;
  contentIndex: ContentIndexDoc;
  contentItems: ContentItemsDoc;
  contentKeys: ContentKeysDoc;
  contentModelBuilds: ContentModelBuildsDoc;
  contentPaths: ContentPathsDoc;
  contentReleases: ContentReleasesDoc;
  contentSnapshots: ContentSnapshotsDoc;
  contentState: ContentStateDoc;
  creditResetPeriods: CreditResetPeriodsDoc;
  creditTransactions: CreditTransactionsDoc;
  curriculumRoutes: CurriculumRoutesDoc;
  customerDeletionTombstones: CustomerDeletionTombstonesDoc;
  customers: CustomersDoc;
  irtCalibrationRuns: IrtCalibrationRunsDoc;
  irtScaleItems: IrtScaleItemsDoc;
  irtScaleVersions: IrtScaleVersionsDoc;
  journalEntries: JournalEntriesDoc;
  learningEngagementQueue: LearningEngagementQueueDoc;
  learningPopularityCounters: LearningPopularityCountersDoc;
  learningPopularityCycles: LearningPopularityCyclesDoc;
  learningPopularitySignals: LearningPopularitySignalsDoc;
  learningPopularityViewerSignals: LearningPopularityViewerSignalsDoc;
  learningPreferences: LearningPreferencesDoc;
  learningViews: LearningViewsDoc;
  materialBuckets: MaterialBucketsDoc;
  materialCatalog: MaterialCatalogDoc;
  ninaMemories: NinaMemoriesDoc;
  ninaSummaries: NinaSummariesDoc;
  ninaTurns: NinaTurnsDoc;
  ninaUploads: NinaUploadsDoc;
  onboardingProfiles: OnboardingProfilesDoc;
  programBuckets: ProgramBucketsDoc;
  programCatalog: ProgramCatalogDoc;
  quranRows: QuranRowsDoc;
  quranSearch: QuranSearchDoc;
  schoolActivityLogs: SchoolActivityLogsDoc;
  schoolClassForumPendingUploads: SchoolClassForumPendingUploadsDoc;
  schoolClassForumPostAttachments: SchoolClassForumPostAttachmentsDoc;
  schoolClassForumPostReactions: SchoolClassForumPostReactionsDoc;
  schoolClassForumPosts: SchoolClassForumPostsDoc;
  schoolClassForumReactions: SchoolClassForumReactionsDoc;
  schoolClassForumReadStates: SchoolClassForumReadStatesDoc;
  schoolClassForums: SchoolClassForumsDoc;
  schoolClassInviteCodes: SchoolClassInviteCodesDoc;
  schoolClassMaterialGroups: SchoolClassMaterialGroupsDoc;
  schoolClassMembers: SchoolClassMembersDoc;
  schoolClasses: SchoolClassesDoc;
  schoolInviteCodes: SchoolInviteCodesDoc;
  schoolMembers: SchoolMembersDoc;
  schools: SchoolsDoc;
  snapshotBatches: SnapshotBatchesDoc;
  subscriptions: SubscriptionsDoc;
  tenantGrants: TenantGrantsDoc;
  tenantInvites: TenantInvitesDoc;
  tenantPeople: TenantPeopleDoc;
  tenantUnits: TenantUnitsDoc;
  tenants: TenantsDoc;
  tryoutAttemptPlacements: TryoutAttemptPlacementsDoc;
  tryoutAttempts: TryoutAttemptsDoc;
  tryoutCatalog: TryoutCatalogDoc;
  tryoutPlacements: TryoutPlacementsDoc;
  tryoutResponses: TryoutResponsesDoc;
  tryoutRuntimeBundles: TryoutRuntimeBundlesDoc;
  tryoutScores: TryoutScoresDoc;
  tryoutSectionAttempts: TryoutSectionAttemptsDoc;
  tryoutSetProgress: TryoutSetProgressDoc;
  userLearningRecents: UserLearningRecentsDoc;
  users: UsersDoc;
  welcomeEmailIntents: WelcomeEmailIntentsDoc;
}
