import { GroupSpec, Spec } from "@confect/core";
import analytics_capture from "../analytics/capture.spec";
import analytics_erasure_action from "../analytics/erasure/action.spec";
import analytics_erasure_workflow from "../analytics/erasure/workflow.spec";
import auth_actions from "../auth/actions.spec";
import auth_cleanup from "../auth/cleanup.spec";
import auth_deletion from "../auth/deletion.spec";
import auth_deletion_recovery from "../auth/deletion/recovery.spec";
import auth_deletion_verification from "../auth/deletion/verification.spec";
import auth_lifecycle from "../auth/lifecycle.spec";
import auth_queries from "../auth/queries.spec";
import chats_mutations from "../chats/mutations.spec";
import chats_queries from "../chats/queries.spec";
import classes_forums_attachments_upload from "../classes/forums/attachments/upload.spec";
import classes_forums_internalMutations from "../classes/forums/internalMutations.spec";
import classes_forums_mutations_forums from "../classes/forums/mutations/forums.spec";
import classes_forums_mutations_posts from "../classes/forums/mutations/posts.spec";
import classes_forums_mutations_reactions from "../classes/forums/mutations/reactions.spec";
import classes_forums_mutations_readState from "../classes/forums/mutations/readState.spec";
import classes_forums_mutations_uploads from "../classes/forums/mutations/uploads.spec";
import classes_forums_queries_forums from "../classes/forums/queries/forums.spec";
import classes_forums_queries_pages from "../classes/forums/queries/pages.spec";
import classes_materials_mutations from "../classes/materials/mutations.spec";
import classes_materials_queries from "../classes/materials/queries.spec";
import classes_mutations from "../classes/mutations.spec";
import classes_queries from "../classes/queries.spec";
import classes_roster from "../classes/roster.spec";
import comments_mutations from "../comments/mutations.spec";
import comments_queries from "../comments/queries.spec";
import consents_current from "../consents/current.spec";
import contentRelease_accept from "../contentRelease/accept.spec";
import contentRelease_activate from "../contentRelease/activate.spec";
import contentRelease_article from "../contentRelease/article.spec";
import contentRelease_article_internal from "../contentRelease/article/internal.spec";
import contentRelease_artifact_backfill from "../contentRelease/artifact/backfill.spec";
import contentRelease_artifacts from "../contentRelease/artifacts.spec";
import contentRelease_cleanup from "../contentRelease/cleanup.spec";
import contentRelease_compact from "../contentRelease/compact.spec";
import contentRelease_envelope from "../contentRelease/envelope.spec";
import contentRelease_heads from "../contentRelease/heads.spec";
import contentRelease_ingress_dispatch from "../contentRelease/ingress/dispatch.spec";
import contentRelease_items from "../contentRelease/items.spec";
import contentRelease_manifest from "../contentRelease/manifest.spec";
import contentRelease_material from "../contentRelease/material.spec";
import contentRelease_models from "../contentRelease/models.spec";
import contentRelease_ownership from "../contentRelease/ownership.spec";
import contentRelease_page from "../contentRelease/page.spec";
import contentRelease_program from "../contentRelease/program.spec";
import contentRelease_proof_catalog from "../contentRelease/proof/catalog.spec";
import contentRelease_proof_commit from "../contentRelease/proof/commit.spec";
import contentRelease_proof_poll from "../contentRelease/proof/poll.spec";
import contentRelease_proof_read from "../contentRelease/proof/read.spec";
import contentRelease_proof_routes from "../contentRelease/proof/routes.spec";
import contentRelease_proof_verify from "../contentRelease/proof/verify.spec";
import contentRelease_proof_workflow from "../contentRelease/proof/workflow.spec";
import contentRelease_quran from "../contentRelease/quran.spec";
import contentRelease_recovery from "../contentRelease/recovery.spec";
import contentRelease_reference from "../contentRelease/reference.spec";
import contentRelease_reference_internal from "../contentRelease/reference/internal.spec";
import contentRelease_rollback from "../contentRelease/rollback.spec";
import contentRelease_routes from "../contentRelease/routes.spec";
import contentRelease_runtime_active from "../contentRelease/runtime/active.spec";
import contentRelease_runtime_publication_internal from "../contentRelease/runtime/publication/internal.spec";
import contentRelease_runtime_tryout_dispatch from "../contentRelease/runtime/tryout/dispatch.spec";
import contentRelease_runtime_tryout_internal from "../contentRelease/runtime/tryout/internal.spec";
import contentRelease_snapshot_batch from "../contentRelease/snapshot/batch.spec";
import contentRelease_snapshot_manifest from "../contentRelease/snapshot/manifest.spec";
import contentRelease_snapshot_read from "../contentRelease/snapshot/read.spec";
import contentRelease_status from "../contentRelease/status.spec";
import contentRelease_tryout from "../contentRelease/tryout.spec";
import contentRelease_verify from "../contentRelease/verify.spec";
import contents_mutations_analytics from "../contents/mutations/analytics.spec";
import contents_mutations_popularity from "../contents/mutations/popularity.spec";
import contents_mutations_views from "../contents/mutations/views.spec";
import contents_queries_recent from "../contents/queries/recent.spec";
import contents_queries_search from "../contents/queries/search.spec";
import contents_queries_trending from "../contents/queries/trending.spec";
import credits_mutations from "../credits/mutations.spec";
import customers_actions_internal from "../customers/actions/internal.spec";
import customers_actions_sessions from "../customers/actions/sessions.spec";
import customers_checkout_admission from "../customers/checkout/admission.spec";
import customers_deletion_cleanup from "../customers/deletion/cleanup.spec";
import customers_deletion_workflow from "../customers/deletion/workflow.spec";
import customers_integrity_internal from "../customers/integrity/internal.spec";
import customers_mutations_internal from "../customers/mutations/internal.spec";
import customers_queries_internal_customer from "../customers/queries/internal/customer.spec";
import emails_retention from "../emails/retention.spec";
import emails_welcome_delivery from "../emails/welcome/delivery.spec";
import emails_welcome_internal from "../emails/welcome/internal.spec";
import emails_welcome_reconciliation from "../emails/welcome/reconciliation.spec";
import emails_welcome_workflow from "../emails/welcome/workflow.spec";
import learningPreferences_mutations from "../learningPreferences/mutations.spec";
import learningPreferences_queries from "../learningPreferences/queries.spec";
import nina_conversation from "../nina/conversation.spec";
import nina_focus from "../nina/focus.spec";
import nina_lifecycle from "../nina/lifecycle.spec";
import nina_memory from "../nina/memory.spec";
import nina_messages from "../nina/messages.spec";
import nina_presentation from "../nina/presentation.spec";
import nina_response from "../nina/response.spec";
import nina_summaries from "../nina/summaries.spec";
import nina_turns from "../nina/turns.spec";
import nina_uploads from "../nina/uploads.spec";
import nina_usage from "../nina/usage.spec";
import onboarding_mutations from "../onboarding/mutations.spec";
import onboarding_queries from "../onboarding/queries.spec";
import privacy_recovery from "../privacy/recovery.spec";
import routes_agent_quota from "../routes/agent/quota.spec";
import schools_mutations from "../schools/mutations.spec";
import schools_queries from "../schools/queries.spec";
import storage from "../storage.spec";
import subscriptions_mutations from "../subscriptions/mutations.spec";
import subscriptions_queries from "../subscriptions/queries.spec";
import triggers_chats_cleanup from "../triggers/chats/cleanup.spec";
import triggers_comments_cleanup from "../triggers/comments/cleanup.spec";
import triggers_materials_cleanup from "../triggers/materials/cleanup.spec";
import triggers_schools_cleanup from "../triggers/schools/cleanup.spec";
import tryouts_mutations_access from "../tryouts/mutations/access.spec";
import tryouts_mutations_attempts from "../tryouts/mutations/attempts.spec";
import tryouts_mutations_expiry from "../tryouts/mutations/expiry.spec";
import tryouts_mutations_responses from "../tryouts/mutations/responses.spec";
import tryouts_mutations_sections from "../tryouts/mutations/sections.spec";
import tryouts_queries_access from "../tryouts/queries/access.spec";
import tryouts_queries_attempt from "../tryouts/queries/attempt.spec";
import tryouts_queries_attemptPage from "../tryouts/queries/attemptPage.spec";
import tryouts_queries_catalog from "../tryouts/queries/catalog.spec";
import tryouts_queries_content from "../tryouts/queries/content.spec";
import tryouts_queries_history from "../tryouts/queries/history.spec";
import tryouts_queries_runtime from "../tryouts/queries/runtime.spec";
import tryouts_queries_sets from "../tryouts/queries/sets.spec";
import tryouts_runtime_signed from "../tryouts/runtime/signed.spec";
import users_mutations from "../users/mutations.spec";
import users_queries from "../users/queries.spec";

const spec: Spec.Spec<{
  readonly analytics: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "analytics", never, GroupSpec.NamedAt<typeof analytics_capture, "capture"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "erasure", never, GroupSpec.NamedAt<typeof analytics_erasure_action, "action"> | GroupSpec.NamedAt<typeof analytics_erasure_workflow, "workflow">>, "erasure">>, "analytics">;
  readonly auth: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "auth", never, GroupSpec.NamedAt<typeof auth_actions, "actions"> | GroupSpec.NamedAt<typeof auth_cleanup, "cleanup"> | GroupSpec.NamedAt<GroupSpec.AddGroups<typeof auth_deletion, GroupSpec.NamedAt<typeof auth_deletion_recovery, "recovery"> | GroupSpec.NamedAt<typeof auth_deletion_verification, "verification">>, "deletion"> | GroupSpec.NamedAt<typeof auth_lifecycle, "lifecycle"> | GroupSpec.NamedAt<typeof auth_queries, "queries">>, "auth">;
  readonly chats: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "chats", never, GroupSpec.NamedAt<typeof chats_mutations, "mutations"> | GroupSpec.NamedAt<typeof chats_queries, "queries">>, "chats">;
  readonly classes: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "classes", never, GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "forums", never, GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "attachments", never, GroupSpec.NamedAt<typeof classes_forums_attachments_upload, "upload">>, "attachments"> | GroupSpec.NamedAt<typeof classes_forums_internalMutations, "internalMutations"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "mutations", never, GroupSpec.NamedAt<typeof classes_forums_mutations_forums, "forums"> | GroupSpec.NamedAt<typeof classes_forums_mutations_posts, "posts"> | GroupSpec.NamedAt<typeof classes_forums_mutations_reactions, "reactions"> | GroupSpec.NamedAt<typeof classes_forums_mutations_readState, "readState"> | GroupSpec.NamedAt<typeof classes_forums_mutations_uploads, "uploads">>, "mutations"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "queries", never, GroupSpec.NamedAt<typeof classes_forums_queries_forums, "forums"> | GroupSpec.NamedAt<typeof classes_forums_queries_pages, "pages">>, "queries">>, "forums"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "materials", never, GroupSpec.NamedAt<typeof classes_materials_mutations, "mutations"> | GroupSpec.NamedAt<typeof classes_materials_queries, "queries">>, "materials"> | GroupSpec.NamedAt<typeof classes_mutations, "mutations"> | GroupSpec.NamedAt<typeof classes_queries, "queries"> | GroupSpec.NamedAt<typeof classes_roster, "roster">>, "classes">;
  readonly comments: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "comments", never, GroupSpec.NamedAt<typeof comments_mutations, "mutations"> | GroupSpec.NamedAt<typeof comments_queries, "queries">>, "comments">;
  readonly consents: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "consents", never, GroupSpec.NamedAt<typeof consents_current, "current">>, "consents">;
  readonly contentRelease: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "contentRelease", never, GroupSpec.NamedAt<typeof contentRelease_accept, "accept"> | GroupSpec.NamedAt<typeof contentRelease_activate, "activate"> | GroupSpec.NamedAt<GroupSpec.AddGroups<typeof contentRelease_article, GroupSpec.NamedAt<typeof contentRelease_article_internal, "internal">>, "article"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "artifact", never, GroupSpec.NamedAt<typeof contentRelease_artifact_backfill, "backfill">>, "artifact"> | GroupSpec.NamedAt<typeof contentRelease_artifacts, "artifacts"> | GroupSpec.NamedAt<typeof contentRelease_cleanup, "cleanup"> | GroupSpec.NamedAt<typeof contentRelease_compact, "compact"> | GroupSpec.NamedAt<typeof contentRelease_envelope, "envelope"> | GroupSpec.NamedAt<typeof contentRelease_heads, "heads"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "ingress", never, GroupSpec.NamedAt<typeof contentRelease_ingress_dispatch, "dispatch">>, "ingress"> | GroupSpec.NamedAt<typeof contentRelease_items, "items"> | GroupSpec.NamedAt<typeof contentRelease_manifest, "manifest"> | GroupSpec.NamedAt<typeof contentRelease_material, "material"> | GroupSpec.NamedAt<typeof contentRelease_models, "models"> | GroupSpec.NamedAt<typeof contentRelease_ownership, "ownership"> | GroupSpec.NamedAt<typeof contentRelease_page, "page"> | GroupSpec.NamedAt<typeof contentRelease_program, "program"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "proof", never, GroupSpec.NamedAt<typeof contentRelease_proof_catalog, "catalog"> | GroupSpec.NamedAt<typeof contentRelease_proof_commit, "commit"> | GroupSpec.NamedAt<typeof contentRelease_proof_poll, "poll"> | GroupSpec.NamedAt<typeof contentRelease_proof_read, "read"> | GroupSpec.NamedAt<typeof contentRelease_proof_routes, "routes"> | GroupSpec.NamedAt<typeof contentRelease_proof_verify, "verify"> | GroupSpec.NamedAt<typeof contentRelease_proof_workflow, "workflow">>, "proof"> | GroupSpec.NamedAt<typeof contentRelease_quran, "quran"> | GroupSpec.NamedAt<typeof contentRelease_recovery, "recovery"> | GroupSpec.NamedAt<GroupSpec.AddGroups<typeof contentRelease_reference, GroupSpec.NamedAt<typeof contentRelease_reference_internal, "internal">>, "reference"> | GroupSpec.NamedAt<typeof contentRelease_rollback, "rollback"> | GroupSpec.NamedAt<typeof contentRelease_routes, "routes"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "runtime", never, GroupSpec.NamedAt<typeof contentRelease_runtime_active, "active"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "publication", never, GroupSpec.NamedAt<typeof contentRelease_runtime_publication_internal, "internal">>, "publication"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "tryout", never, GroupSpec.NamedAt<typeof contentRelease_runtime_tryout_dispatch, "dispatch"> | GroupSpec.NamedAt<typeof contentRelease_runtime_tryout_internal, "internal">>, "tryout">>, "runtime"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "snapshot", never, GroupSpec.NamedAt<typeof contentRelease_snapshot_batch, "batch"> | GroupSpec.NamedAt<typeof contentRelease_snapshot_manifest, "manifest"> | GroupSpec.NamedAt<typeof contentRelease_snapshot_read, "read">>, "snapshot"> | GroupSpec.NamedAt<typeof contentRelease_status, "status"> | GroupSpec.NamedAt<typeof contentRelease_tryout, "tryout"> | GroupSpec.NamedAt<typeof contentRelease_verify, "verify">>, "contentRelease">;
  readonly contents: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "contents", never, GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "mutations", never, GroupSpec.NamedAt<typeof contents_mutations_analytics, "analytics"> | GroupSpec.NamedAt<typeof contents_mutations_popularity, "popularity"> | GroupSpec.NamedAt<typeof contents_mutations_views, "views">>, "mutations"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "queries", never, GroupSpec.NamedAt<typeof contents_queries_recent, "recent"> | GroupSpec.NamedAt<typeof contents_queries_search, "search"> | GroupSpec.NamedAt<typeof contents_queries_trending, "trending">>, "queries">>, "contents">;
  readonly credits: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "credits", never, GroupSpec.NamedAt<typeof credits_mutations, "mutations">>, "credits">;
  readonly customers: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "customers", never, GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "actions", never, GroupSpec.NamedAt<typeof customers_actions_internal, "internal"> | GroupSpec.NamedAt<typeof customers_actions_sessions, "sessions">>, "actions"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "checkout", never, GroupSpec.NamedAt<typeof customers_checkout_admission, "admission">>, "checkout"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "deletion", never, GroupSpec.NamedAt<typeof customers_deletion_cleanup, "cleanup"> | GroupSpec.NamedAt<typeof customers_deletion_workflow, "workflow">>, "deletion"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "integrity", never, GroupSpec.NamedAt<typeof customers_integrity_internal, "internal">>, "integrity"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "mutations", never, GroupSpec.NamedAt<typeof customers_mutations_internal, "internal">>, "mutations"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "queries", never, GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "internal", never, GroupSpec.NamedAt<typeof customers_queries_internal_customer, "customer">>, "internal">>, "queries">>, "customers">;
  readonly emails: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "emails", never, GroupSpec.NamedAt<typeof emails_retention, "retention"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "welcome", never, GroupSpec.NamedAt<typeof emails_welcome_delivery, "delivery"> | GroupSpec.NamedAt<typeof emails_welcome_internal, "internal"> | GroupSpec.NamedAt<typeof emails_welcome_reconciliation, "reconciliation"> | GroupSpec.NamedAt<typeof emails_welcome_workflow, "workflow">>, "welcome">>, "emails">;
  readonly learningPreferences: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "learningPreferences", never, GroupSpec.NamedAt<typeof learningPreferences_mutations, "mutations"> | GroupSpec.NamedAt<typeof learningPreferences_queries, "queries">>, "learningPreferences">;
  readonly nina: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "nina", never, GroupSpec.NamedAt<typeof nina_conversation, "conversation"> | GroupSpec.NamedAt<typeof nina_focus, "focus"> | GroupSpec.NamedAt<typeof nina_lifecycle, "lifecycle"> | GroupSpec.NamedAt<typeof nina_memory, "memory"> | GroupSpec.NamedAt<typeof nina_messages, "messages"> | GroupSpec.NamedAt<typeof nina_presentation, "presentation"> | GroupSpec.NamedAt<typeof nina_response, "response"> | GroupSpec.NamedAt<typeof nina_summaries, "summaries"> | GroupSpec.NamedAt<typeof nina_turns, "turns"> | GroupSpec.NamedAt<typeof nina_uploads, "uploads"> | GroupSpec.NamedAt<typeof nina_usage, "usage">>, "nina">;
  readonly onboarding: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "onboarding", never, GroupSpec.NamedAt<typeof onboarding_mutations, "mutations"> | GroupSpec.NamedAt<typeof onboarding_queries, "queries">>, "onboarding">;
  readonly privacy: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "privacy", never, GroupSpec.NamedAt<typeof privacy_recovery, "recovery">>, "privacy">;
  readonly routes: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "routes", never, GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "agent", never, GroupSpec.NamedAt<typeof routes_agent_quota, "quota">>, "agent">>, "routes">;
  readonly schools: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "schools", never, GroupSpec.NamedAt<typeof schools_mutations, "mutations"> | GroupSpec.NamedAt<typeof schools_queries, "queries">>, "schools">;
  readonly storage: GroupSpec.NamedAt<typeof storage, "storage">;
  readonly subscriptions: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "subscriptions", never, GroupSpec.NamedAt<typeof subscriptions_mutations, "mutations"> | GroupSpec.NamedAt<typeof subscriptions_queries, "queries">>, "subscriptions">;
  readonly triggers: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "triggers", never, GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "chats", never, GroupSpec.NamedAt<typeof triggers_chats_cleanup, "cleanup">>, "chats"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "comments", never, GroupSpec.NamedAt<typeof triggers_comments_cleanup, "cleanup">>, "comments"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "materials", never, GroupSpec.NamedAt<typeof triggers_materials_cleanup, "cleanup">>, "materials"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "schools", never, GroupSpec.NamedAt<typeof triggers_schools_cleanup, "cleanup">>, "schools">>, "triggers">;
  readonly tryouts: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "tryouts", never, GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "mutations", never, GroupSpec.NamedAt<typeof tryouts_mutations_access, "access"> | GroupSpec.NamedAt<typeof tryouts_mutations_attempts, "attempts"> | GroupSpec.NamedAt<typeof tryouts_mutations_expiry, "expiry"> | GroupSpec.NamedAt<typeof tryouts_mutations_responses, "responses"> | GroupSpec.NamedAt<typeof tryouts_mutations_sections, "sections">>, "mutations"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "queries", never, GroupSpec.NamedAt<typeof tryouts_queries_access, "access"> | GroupSpec.NamedAt<typeof tryouts_queries_attempt, "attempt"> | GroupSpec.NamedAt<typeof tryouts_queries_attemptPage, "attemptPage"> | GroupSpec.NamedAt<typeof tryouts_queries_catalog, "catalog"> | GroupSpec.NamedAt<typeof tryouts_queries_content, "content"> | GroupSpec.NamedAt<typeof tryouts_queries_history, "history"> | GroupSpec.NamedAt<typeof tryouts_queries_runtime, "runtime"> | GroupSpec.NamedAt<typeof tryouts_queries_sets, "sets">>, "queries"> | GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "runtime", never, GroupSpec.NamedAt<typeof tryouts_runtime_signed, "signed">>, "runtime">>, "tryouts">;
  readonly users: GroupSpec.NamedAt<GroupSpec.GroupSpec<"Convex", "users", never, GroupSpec.NamedAt<typeof users_mutations, "mutations"> | GroupSpec.NamedAt<typeof users_queries, "queries">>, "users">;
}> = Spec.make().addAt("analytics", GroupSpec.makeAt("analytics").addGroupAt("capture", analytics_capture).addGroupAt("erasure", GroupSpec.makeAt("erasure").addGroupAt("action", analytics_erasure_action).addGroupAt("workflow", analytics_erasure_workflow))).addAt("auth", GroupSpec.makeAt("auth").addGroupAt("actions", auth_actions).addGroupAt("cleanup", auth_cleanup).addGroupAt("deletion", auth_deletion.addGroupAt("recovery", auth_deletion_recovery).addGroupAt("verification", auth_deletion_verification)).addGroupAt("lifecycle", auth_lifecycle).addGroupAt("queries", auth_queries)).addAt("chats", GroupSpec.makeAt("chats").addGroupAt("mutations", chats_mutations).addGroupAt("queries", chats_queries)).addAt("classes", GroupSpec.makeAt("classes").addGroupAt("forums", GroupSpec.makeAt("forums").addGroupAt("attachments", GroupSpec.makeAt("attachments").addGroupAt("upload", classes_forums_attachments_upload)).addGroupAt("internalMutations", classes_forums_internalMutations).addGroupAt("mutations", GroupSpec.makeAt("mutations").addGroupAt("forums", classes_forums_mutations_forums).addGroupAt("posts", classes_forums_mutations_posts).addGroupAt("reactions", classes_forums_mutations_reactions).addGroupAt("readState", classes_forums_mutations_readState).addGroupAt("uploads", classes_forums_mutations_uploads)).addGroupAt("queries", GroupSpec.makeAt("queries").addGroupAt("forums", classes_forums_queries_forums).addGroupAt("pages", classes_forums_queries_pages))).addGroupAt("materials", GroupSpec.makeAt("materials").addGroupAt("mutations", classes_materials_mutations).addGroupAt("queries", classes_materials_queries)).addGroupAt("mutations", classes_mutations).addGroupAt("queries", classes_queries).addGroupAt("roster", classes_roster)).addAt("comments", GroupSpec.makeAt("comments").addGroupAt("mutations", comments_mutations).addGroupAt("queries", comments_queries)).addAt("consents", GroupSpec.makeAt("consents").addGroupAt("current", consents_current)).addAt("contentRelease", GroupSpec.makeAt("contentRelease").addGroupAt("accept", contentRelease_accept).addGroupAt("activate", contentRelease_activate).addGroupAt("article", contentRelease_article.addGroupAt("internal", contentRelease_article_internal)).addGroupAt("artifact", GroupSpec.makeAt("artifact").addGroupAt("backfill", contentRelease_artifact_backfill)).addGroupAt("artifacts", contentRelease_artifacts).addGroupAt("cleanup", contentRelease_cleanup).addGroupAt("compact", contentRelease_compact).addGroupAt("envelope", contentRelease_envelope).addGroupAt("heads", contentRelease_heads).addGroupAt("ingress", GroupSpec.makeAt("ingress").addGroupAt("dispatch", contentRelease_ingress_dispatch)).addGroupAt("items", contentRelease_items).addGroupAt("manifest", contentRelease_manifest).addGroupAt("material", contentRelease_material).addGroupAt("models", contentRelease_models).addGroupAt("ownership", contentRelease_ownership).addGroupAt("page", contentRelease_page).addGroupAt("program", contentRelease_program).addGroupAt("proof", GroupSpec.makeAt("proof").addGroupAt("catalog", contentRelease_proof_catalog).addGroupAt("commit", contentRelease_proof_commit).addGroupAt("poll", contentRelease_proof_poll).addGroupAt("read", contentRelease_proof_read).addGroupAt("routes", contentRelease_proof_routes).addGroupAt("verify", contentRelease_proof_verify).addGroupAt("workflow", contentRelease_proof_workflow)).addGroupAt("quran", contentRelease_quran).addGroupAt("recovery", contentRelease_recovery).addGroupAt("reference", contentRelease_reference.addGroupAt("internal", contentRelease_reference_internal)).addGroupAt("rollback", contentRelease_rollback).addGroupAt("routes", contentRelease_routes).addGroupAt("runtime", GroupSpec.makeAt("runtime").addGroupAt("active", contentRelease_runtime_active).addGroupAt("publication", GroupSpec.makeAt("publication").addGroupAt("internal", contentRelease_runtime_publication_internal)).addGroupAt("tryout", GroupSpec.makeAt("tryout").addGroupAt("dispatch", contentRelease_runtime_tryout_dispatch).addGroupAt("internal", contentRelease_runtime_tryout_internal))).addGroupAt("snapshot", GroupSpec.makeAt("snapshot").addGroupAt("batch", contentRelease_snapshot_batch).addGroupAt("manifest", contentRelease_snapshot_manifest).addGroupAt("read", contentRelease_snapshot_read)).addGroupAt("status", contentRelease_status).addGroupAt("tryout", contentRelease_tryout).addGroupAt("verify", contentRelease_verify)).addAt("contents", GroupSpec.makeAt("contents").addGroupAt("mutations", GroupSpec.makeAt("mutations").addGroupAt("analytics", contents_mutations_analytics).addGroupAt("popularity", contents_mutations_popularity).addGroupAt("views", contents_mutations_views)).addGroupAt("queries", GroupSpec.makeAt("queries").addGroupAt("recent", contents_queries_recent).addGroupAt("search", contents_queries_search).addGroupAt("trending", contents_queries_trending))).addAt("credits", GroupSpec.makeAt("credits").addGroupAt("mutations", credits_mutations)).addAt("customers", GroupSpec.makeAt("customers").addGroupAt("actions", GroupSpec.makeAt("actions").addGroupAt("internal", customers_actions_internal).addGroupAt("sessions", customers_actions_sessions)).addGroupAt("checkout", GroupSpec.makeAt("checkout").addGroupAt("admission", customers_checkout_admission)).addGroupAt("deletion", GroupSpec.makeAt("deletion").addGroupAt("cleanup", customers_deletion_cleanup).addGroupAt("workflow", customers_deletion_workflow)).addGroupAt("integrity", GroupSpec.makeAt("integrity").addGroupAt("internal", customers_integrity_internal)).addGroupAt("mutations", GroupSpec.makeAt("mutations").addGroupAt("internal", customers_mutations_internal)).addGroupAt("queries", GroupSpec.makeAt("queries").addGroupAt("internal", GroupSpec.makeAt("internal").addGroupAt("customer", customers_queries_internal_customer)))).addAt("emails", GroupSpec.makeAt("emails").addGroupAt("retention", emails_retention).addGroupAt("welcome", GroupSpec.makeAt("welcome").addGroupAt("delivery", emails_welcome_delivery).addGroupAt("internal", emails_welcome_internal).addGroupAt("reconciliation", emails_welcome_reconciliation).addGroupAt("workflow", emails_welcome_workflow))).addAt("learningPreferences", GroupSpec.makeAt("learningPreferences").addGroupAt("mutations", learningPreferences_mutations).addGroupAt("queries", learningPreferences_queries)).addAt("nina", GroupSpec.makeAt("nina").addGroupAt("conversation", nina_conversation).addGroupAt("focus", nina_focus).addGroupAt("lifecycle", nina_lifecycle).addGroupAt("memory", nina_memory).addGroupAt("messages", nina_messages).addGroupAt("presentation", nina_presentation).addGroupAt("response", nina_response).addGroupAt("summaries", nina_summaries).addGroupAt("turns", nina_turns).addGroupAt("uploads", nina_uploads).addGroupAt("usage", nina_usage)).addAt("onboarding", GroupSpec.makeAt("onboarding").addGroupAt("mutations", onboarding_mutations).addGroupAt("queries", onboarding_queries)).addAt("privacy", GroupSpec.makeAt("privacy").addGroupAt("recovery", privacy_recovery)).addAt("routes", GroupSpec.makeAt("routes").addGroupAt("agent", GroupSpec.makeAt("agent").addGroupAt("quota", routes_agent_quota))).addAt("schools", GroupSpec.makeAt("schools").addGroupAt("mutations", schools_mutations).addGroupAt("queries", schools_queries)).addAt("storage", storage).addAt("subscriptions", GroupSpec.makeAt("subscriptions").addGroupAt("mutations", subscriptions_mutations).addGroupAt("queries", subscriptions_queries)).addAt("triggers", GroupSpec.makeAt("triggers").addGroupAt("chats", GroupSpec.makeAt("chats").addGroupAt("cleanup", triggers_chats_cleanup)).addGroupAt("comments", GroupSpec.makeAt("comments").addGroupAt("cleanup", triggers_comments_cleanup)).addGroupAt("materials", GroupSpec.makeAt("materials").addGroupAt("cleanup", triggers_materials_cleanup)).addGroupAt("schools", GroupSpec.makeAt("schools").addGroupAt("cleanup", triggers_schools_cleanup))).addAt("tryouts", GroupSpec.makeAt("tryouts").addGroupAt("mutations", GroupSpec.makeAt("mutations").addGroupAt("access", tryouts_mutations_access).addGroupAt("attempts", tryouts_mutations_attempts).addGroupAt("expiry", tryouts_mutations_expiry).addGroupAt("responses", tryouts_mutations_responses).addGroupAt("sections", tryouts_mutations_sections)).addGroupAt("queries", GroupSpec.makeAt("queries").addGroupAt("access", tryouts_queries_access).addGroupAt("attempt", tryouts_queries_attempt).addGroupAt("attemptPage", tryouts_queries_attemptPage).addGroupAt("catalog", tryouts_queries_catalog).addGroupAt("content", tryouts_queries_content).addGroupAt("history", tryouts_queries_history).addGroupAt("runtime", tryouts_queries_runtime).addGroupAt("sets", tryouts_queries_sets)).addGroupAt("runtime", GroupSpec.makeAt("runtime").addGroupAt("signed", tryouts_runtime_signed))).addAt("users", GroupSpec.makeAt("users").addGroupAt("mutations", users_mutations).addGroupAt("queries", users_queries));

export default spec;
