import {
  SchoolAssessmentChoices,
  SchoolAssessmentQuestionBankEntries,
  SchoolAssessmentQuestionBanks,
  SchoolAssessmentQuestions,
  SchoolAssessmentRubricCriteria,
  SchoolAssessmentSections,
  SchoolAssessments,
  SchoolAssessmentVersionChoices,
  SchoolAssessmentVersionQuestions,
  SchoolAssessmentVersionRubricCriteria,
  SchoolAssessmentVersionSections,
  SchoolAssessmentVersions,
} from "@repo/backend/confect/modules/school/assessmentsTables/authoring";
import {
  SchoolAssessmentAssignments,
  SchoolAssessmentAssignmentTargets,
  SchoolAssessmentAttemptEvents,
  SchoolAssessmentAttemptSessions,
  SchoolAssessmentAttempts,
  SchoolAssessmentClassStats,
  SchoolAssessmentEssayGrades,
  SchoolAssessmentFinalGrades,
  SchoolAssessmentFlags,
  SchoolAssessmentLeaderboardEntries,
  SchoolAssessmentQuestionStats,
  SchoolAssessmentResponses,
  SchoolAssessmentSectionAttempts,
  SchoolAssessmentStudentStats,
} from "@repo/backend/confect/modules/school/assessmentsTables/delivery";
import {
  SchoolAssessmentImportDrafts,
  SchoolAssessmentImportJobs,
} from "@repo/backend/confect/modules/school/assessmentsTables/imports";

/** All assessment tables registered with the Confect schema. */
export const tables = [
  SchoolAssessments,
  SchoolAssessmentVersions,
  SchoolAssessmentSections,
  SchoolAssessmentVersionSections,
  SchoolAssessmentQuestions,
  SchoolAssessmentVersionQuestions,
  SchoolAssessmentChoices,
  SchoolAssessmentVersionChoices,
  SchoolAssessmentRubricCriteria,
  SchoolAssessmentVersionRubricCriteria,
  SchoolAssessmentQuestionBanks,
  SchoolAssessmentQuestionBankEntries,
  SchoolAssessmentAssignments,
  SchoolAssessmentAssignmentTargets,
  SchoolAssessmentAttempts,
  SchoolAssessmentSectionAttempts,
  SchoolAssessmentResponses,
  SchoolAssessmentEssayGrades,
  SchoolAssessmentFinalGrades,
  SchoolAssessmentAttemptSessions,
  SchoolAssessmentAttemptEvents,
  SchoolAssessmentFlags,
  SchoolAssessmentStudentStats,
  SchoolAssessmentQuestionStats,
  SchoolAssessmentClassStats,
  SchoolAssessmentLeaderboardEntries,
  SchoolAssessmentImportJobs,
  SchoolAssessmentImportDrafts,
] as const;
