import { type BundledLanguage, bundledLanguages } from "shiki";

const LANGUAGE_EXTENSION_OVERRIDES: Partial<Record<BundledLanguage, string>> = {
  "1c-query": "1cq",
  "actionscript-3": "as",
  "angular-html": "html",
  "angular-ts": "ts",
  apache: "conf",
  apex: "cls",
  asciidoc: "adoc",
  ballerina: "bal",
  bash: "sh",
  batch: "bat",
  bibtex: "bib",
  bird2: "bird",
  blade: "blade.php",
  "c#": "cs",
  "c++": "cpp",
  cadence: "cdc",
  clarity: "clar",
  clojure: "clj",
  "closure-templates": "soy",
  cobol: "cob",
  codeowners: "CODEOWNERS",
  codeql: "ql",
  coffeescript: "coffee",
  "common-lisp": "lisp",
  console: "sh",
  coq: "v",
  crystal: "cr",
  csharp: "cs",
  cypher: "cql",
  docker: "dockerfile",
  dotenv: "env",
  "dream-maker": "dm",
  elisp: "el",
  elixir: "ex",
  "emacs-lisp": "el",
  erlang: "erl",
  "f#": "fs",
  fennel: "fnl",
  fluent: "ftl",
  "fortran-fixed-form": "f",
  "fortran-free-form": "f90",
  fsharp: "fs",
  gdresource: "tres",
  gdscript: "gd",
  genie: "gs",
  gherkin: "feature",
  "git-commit": "gitcommit",
  "git-rebase": "gitrebase",
  gjs: "js",
  "glimmer-js": "js",
  "glimmer-ts": "ts",
  gnuplot: "plt",
  handlebars: "hbs",
  haskell: "hs",
  haxe: "hx",
  "html-derivative": "html",
  javascript: "js",
  julia: "jl",
  kotlin: "kt",
  kusto: "kql",
  latex: "tex",
  lean4: "lean",
  llvm: "ll",
  make: "mak",
  makefile: "mak",
  markdown: "md",
  matlab: "m",
  mediawiki: "wiki",
  mermaid: "mmd",
  mips: "s",
  mipsasm: "s",
  moonbit: "moon",
  nextflow: "nf",
  "nextflow-groovy": "nf",
  nginx: "conf",
  nushell: "nu",
  objc: "m",
  "objective-c": "m",
  "objective-cpp": "mm",
  ocaml: "ml",
  openscad: "scad",
  pascal: "pas",
  perl: "pl",
  perl6: "p6",
  plsql: "pls",
  postcss: "pcss",
  powerquery: "pq",
  powershell: "ps1",
  prolog: "pl",
  protobuf: "proto",
  puppet: "pp",
  purescript: "purs",
  python: "py",
  racket: "rkt",
  razor: "cshtml",
  riscv: "s",
  rosmsg: "msg",
  ruby: "rb",
  rust: "rs",
  scheme: "scm",
  shaderlab: "shader",
  shell: "sh",
  shellscript: "sh",
  shellsession: "sh",
  smalltalk: "st",
  solidity: "sol",
  sparql: "rq",
  splunk: "spl",
  "ssh-config": "config",
  stata: "do",
  stylus: "styl",
  surrealql: "surql",
  "system-verilog": "sv",
  systemd: "service",
  talonscript: "talon",
  terraform: "tf",
  "ts-tags": "ts",
  turtle: "ttl",
  typescript: "ts",
  typespec: "tsp",
  typst: "typ",
  verilog: "v",
  viml: "vim",
  vimscript: "vim",
  "vue-html": "html",
  "vue-vine": "vine",
  vyper: "vy",
  wenyan: "wy",
  wikitext: "wiki",
  wolfram: "wl",
  zenscript: "zs",
  文言: "wy",
};

function isBundledLanguage(language: string): language is BundledLanguage {
  return Object.hasOwn(bundledLanguages, language);
}

/** Resolves a Shiki language to a useful downloaded-file extension. */
export function getCodeFileExtension(language: string | undefined) {
  if (!(language && isBundledLanguage(language))) {
    return "txt";
  }

  return LANGUAGE_EXTENSION_OVERRIDES[language] ?? language;
}
