import registeredFunctions from "@repo/backend/confect/_generated/registered/notifications";

export const setDisabledNotificationTypes = registeredFunctions.notifications.mutations.setDisabledNotificationTypes;
export const setNotificationEntityMute = registeredFunctions.notifications.mutations.setNotificationEntityMute;
export const updateNotificationPreferences = registeredFunctions.notifications.mutations.updateNotificationPreferences;
