export const FORUM_BOTTOM_PREFETCH_VIEWPORTS = 0.75;
export const FORUM_MAX_BUFFERED_OLDER_PAGES = 2;
export const FORUM_SCROLL_SETTLE_DELAY = 80;
export const FORUM_TOP_PREFETCH_VIEWPORTS = 1;
export const FORUM_VIRTUAL_BUFFER_SIZE = 400;
