name: 📖 Documentation Improvement
description: 📝 Help us make our docs clearer, better, and more helpful!
title: "📖 [DOCS] "
labels: ["📖 documentation", "✨ enhancement", "🔍 needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📚 Thanks for helping improve our documentation!
        
        📝 **Great docs make great products!** Your suggestions help everyone understand and use nakafa better.
        💡 **Clear is kind:** The clearer our docs, the easier it is for everyone to learn and contribute.
        
  - type: dropdown
    id: docs-type
    attributes:
      label: 📋 What type of documentation needs improvement?
      description: Help us understand which area needs attention
      options:
        - 🏠 README Files - Main project documentation
        - 🚀 Getting Started Guide - Setup and installation instructions
        - 🔧 API Documentation - Technical API reference
        - 🎓 User Guide - How to use features and functionality
        - 👨‍💻 Contributing Guide - Instructions for contributors
        - 📚 Educational Content Guide - Content creation guidelines
        - 🎨 Design System Docs - UI components and styling guide
        - 🌍 Internationalization Docs - Translation and localization guide
        - 🔒 Security Documentation - Security guidelines and practices
        - 📱 Deployment Guide - Hosting and deployment instructions
        - 🤷 Other/Not Sure - Something else or multiple areas
      default: 10
    validations:
      required: true
      
  - type: textarea
    id: current-problem
    attributes:
      label: 🤔 What's confusing or missing?
      description: Describe the current issue with the documentation
      placeholder: |
        Example: "The Getting Started guide mentions installing dependencies with 'npm install', but doesn't explain what to do if you're using pnpm instead. Also, the setup steps skip over creating environment variables, which caused me to get stuck for hours..."
    validations:
      required: true
      
  - type: textarea
    id: suggested-improvement
    attributes:
      label: ✨ How can we make it better?
      description: Share your specific suggestions for improvement
      placeholder: |
        💡 Your improvement ideas (e.g.):
        - Add a section about package manager alternatives (npm, yarn, pnpm)
        - Include step-by-step screenshots for environment setup
        - Add troubleshooting section for common setup issues
        - Provide examples for different operating systems
        - Add links to related documentation
    validations:
      required: true
      
  - type: dropdown
    id: target-audience
    attributes:
      label: 👥 Who would benefit from this improvement?
      description: Help us understand the target audience
      options:
        - 🆕 New Users - People just getting started
        - 🎓 Students - Learning and educational users
        - 👨‍🏫 Teachers - Educators using the platform
        - 👨‍💻 Developers - Technical contributors and maintainers
        - 🎨 Designers - UI/UX contributors
        - 📝 Content Creators - People adding educational content
        - 🌍 International Users - Non-English or multilingual users
        - 👥 Everyone - All users would benefit
      default: 7
    validations:
      required: true
      
  - type: dropdown
    id: impact-level
    attributes:
      label: 🎯 How much impact would this have?
      description: Help us prioritize documentation improvements
      options:
        - 🔥 High Impact - Major blocker for many users
        - ⚡ Medium Impact - Noticeable improvement for several users
        - 💡 Low Impact - Nice quality-of-life improvement
        - 🌱 Future Consideration - Useful but not urgent
      default: 1
    validations:
      required: true
      
  - type: textarea
    id: current-workaround
    attributes:
      label: 🔄 Current Workaround
      description: How are people currently handling this issue?
      placeholder: |
        🤔 What do people do now? For example:
        - Ask questions in Discord/discussions
        - Figure it out through trial and error
        - Look at source code for answers
        - Search through GitHub issues
        - Give up and use something else
    validations:
      required: false
      
  - type: textarea
    id: examples-references
    attributes:
      label: 🌟 Examples & References
      description: Share examples of great documentation or specific content to add
      placeholder: |
        📚 Examples that might help:
        - Links to well-written docs from other projects
        - Screenshots or drafts of improved content
        - Specific code examples or explanations
        - References to documentation standards
    validations:
      required: false
      
  - type: textarea
    id: specific-location
    attributes:
      label: 📍 Where exactly needs improvement?
      description: Help us find the specific location that needs work
      placeholder: |
        🎯 Specific locations (be as detailed as possible):
        - File path: e.g., README.md, docs/getting-started.md
        - Section: e.g., "Installation" section, "API Reference" table
        - URL: e.g., https://nakafa.com/docs/setup
        - Line numbers: if you know the specific lines
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: 💬 Additional Context
      description: Any other thoughts, ideas, or context?
      placeholder: "✨ Screenshots, user feedback you've seen, related issues, or any other helpful context..."
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Documentation Check
      description: Making sure we're aligned on creating helpful documentation
      options:
        - label: 🔍 I've checked that this specific improvement hasn't already been suggested
          required: true
        - label: 📚 I've read through the current documentation to understand the context
          required: true
        - label: 🌍 I've considered how this would work for users with different experience levels
          required: true
        - label: 🤝 I'm willing to help review or test the improved documentation
          required: false 