name: Feature Request
description: Propose a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this solve?
      placeholder: As a student, I find it hard to track my learning progress
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should it work?
      placeholder: A dashboard showing completion progress, time spent, and achievements
    validations:
      required: true
  - type: textarea
    id: user-story
    attributes:
      label: User story (optional)
      description: How would someone use this?
      placeholder: As a [user type], I want to [action] so that [benefit]
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered (optional)
      description: Workarounds or similar features elsewhere
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Must-have
        - High
        - Medium
        - Low
      default: 1
    validations:
      required: true
  - type: textarea
    id: mockups
    attributes:
      label: Mockups or examples (optional)
      description: Images, links, or descriptions