import "server-only";
import { keys } from "@repo/analytics/keys";
import { Option, pipe, Schema } from "effect";

type CookieHeader = string | string[] | null | undefined;
const COOKIE_SPLIT_PATTERN = /;\s*/;
const decodeUriComponent = Option.liftThrowable(decodeURIComponent);
const postHogCookiePayloadSchema = Schema.fromJsonString(
  Schema.Struct({ distinct_id: Schema.NonEmptyString })
);
const decodePostHogCookiePayload = Schema.decodeUnknownOption(
  postHogCookiePayloadSchema
);
let analyticsKeys: ReturnType<typeof keys> | undefined;
/** Lazily validates analytics configuration only when attribution is needed. */
function getAnalyticsKeys() {
  analyticsKeys ??= keys();
  return analyticsKeys;
}
/** Normalize a request cookie header into one semicolon-delimited string. */
function normalizeCookieHeader(cookieHeader: CookieHeader) {
  if (Array.isArray(cookieHeader)) {
    return cookieHeader.join("; ");
  }
  return cookieHeader ?? "";
}
/** Match the PostHog browser token normalization used in cookie names. */
function normalizePostHogTokenForCookieName(token: string) {
  return token
    .replaceAll("+", "PL")
    .replaceAll("/", "SL")
    .replaceAll("=", "EQ");
}
/** Return the persistence cookie name generated by the PostHog Web SDK. */
function getPostHogCookieName() {
  const runtimeKeys = getAnalyticsKeys();
  return `ph_${normalizePostHogTokenForCookieName(runtimeKeys.NEXT_PUBLIC_POSTHOG_KEY)}_posthog`;
}
/** Extract one cookie value from a normalized cookie header string. */
function getCookieValue(cookieHeader: string, cookieName: string) {
  const cookiePrefix = `${cookieName}=`;
  for (const cookie of cookieHeader.split(COOKIE_SPLIT_PATTERN)) {
    if (cookie.startsWith(cookiePrefix)) {
      return cookie.slice(cookiePrefix.length);
    }
  }
  return;
}
/** Parse the PostHog persistence payload and return its distinct id. */
function parseDistinctIdFromCookieValue(cookieValue: string) {
  return pipe(
    decodeUriComponent(cookieValue),
    Option.flatMap(decodePostHogCookiePayload),
    Option.map((payload) => payload.distinct_id),
    Option.getOrUndefined
  );
}
/** Read the PostHog browser distinct id from a request cookie header. */
export function extractDistinctIdFromPostHogCookie(cookieHeader: CookieHeader) {
  const normalizedCookieHeader = normalizeCookieHeader(cookieHeader);
  if (!normalizedCookieHeader) {
    return;
  }
  const cookieValue = getCookieValue(
    normalizedCookieHeader,
    getPostHogCookieName()
  );
  if (!cookieValue) {
    return;
  }
  return parseDistinctIdFromCookieValue(cookieValue);
}
