import "server-only";

import { keys } from "@repo/analytics/keys";
import { PostHog } from "posthog-node";

type CookieHeader = string | string[] | null | undefined;
type ServerExceptionProperties = Record<string | number, unknown>;

const COOKIE_SPLIT_PATTERN = /;\s*/;

export const analytics = new PostHog(keys().NEXT_PUBLIC_POSTHOG_KEY, {
  host: keys().POSTHOG_PROXY_HOST,

  // Don't batch events and flush immediately - we're running in a serverless environment
  flushAt: 1,
  flushInterval: 0,
});

/**
 * Normalize a request cookie header into one semicolon-delimited string.
 */
function normalizeCookieHeader(cookieHeader: CookieHeader) {
  if (Array.isArray(cookieHeader)) {
    return cookieHeader.join("; ");
  }

  return cookieHeader ?? "";
}

/**
 * Match PostHog's client-side token normalization for persistence cookie names.
 *
 * Source of truth:
 * `packages/analytics/node_modules/posthog-js/lib/src/posthog-persistence.js`
 * `parseName()`.
 *
 * Related docs:
 * https://posthog.com/docs/error-tracking/installation/nextjs
 */
function normalizePostHogTokenForCookieName(token: string) {
  return token
    .replaceAll("+", "PL")
    .replaceAll("/", "SL")
    .replaceAll("=", "EQ");
}

/**
 * Return the persistence cookie name generated by the PostHog Web SDK.
 *
 * Source of truth:
 * `packages/analytics/node_modules/posthog-js/lib/src/posthog-persistence.js`
 * `parseName()` returns `ph_${token}_posthog` when `persistence_name` is not set.
 *
 * Related docs:
 * https://posthog.com/docs/error-tracking/installation/nextjs
 */
function getPostHogCookieName() {
  return `ph_${normalizePostHogTokenForCookieName(keys().NEXT_PUBLIC_POSTHOG_KEY)}_posthog`;
}

/**
 * Extract one cookie value from a normalized cookie header string.
 */
function getCookieValue(cookieHeader: string, cookieName: string) {
  for (const cookie of cookieHeader.split(COOKIE_SPLIT_PATTERN)) {
    const separatorIndex = cookie.indexOf("=");

    if (separatorIndex === -1) {
      continue;
    }

    if (cookie.slice(0, separatorIndex) === cookieName) {
      return cookie.slice(separatorIndex + 1);
    }
  }

  return undefined;
}

/**
 * Parse the PostHog persistence cookie payload and return its `distinct_id`.
 *
 * Source of truth:
 * `packages/analytics/node_modules/posthog-js/lib/src/posthog-core.js`
 * stores `distinct_id` in persistence, and the cookie payload is URL-encoded JSON.
 *
 * Related docs:
 * https://posthog.com/docs/error-tracking/installation/nextjs
 */
function parseDistinctIdFromCookieValue(cookieValue: string) {
  try {
    const payload = JSON.parse(decodeURIComponent(cookieValue));

    if (
      typeof payload === "object" &&
      payload !== null &&
      "distinct_id" in payload &&
      typeof payload.distinct_id === "string" &&
      payload.distinct_id.length > 0
    ) {
      return payload.distinct_id;
    }
  } catch {
    return undefined;
  }

  return undefined;
}

/**
 * Read the PostHog browser `distinct_id` from a request cookie header.
 *
 * Docs:
 * https://posthog.com/docs/error-tracking/installation/nextjs
 */
export function extractDistinctIdFromPostHogCookie(cookieHeader: CookieHeader) {
  const normalizedCookieHeader = normalizeCookieHeader(cookieHeader);

  if (!normalizedCookieHeader) {
    return undefined;
  }

  const cookieValue = getCookieValue(
    normalizedCookieHeader,
    getPostHogCookieName()
  );

  if (!cookieValue) {
    return undefined;
  }

  return parseDistinctIdFromCookieValue(cookieValue);
}

/**
 * Capture one server-side exception and wait for PostHog to enqueue it.
 *
 * Docs:
 * https://posthog.com/docs/error-tracking/capture
 * https://posthog.com/docs/error-tracking/installation/nextjs
 */
export async function captureServerException(
  error: unknown,
  distinctId?: string,
  additionalProperties?: ServerExceptionProperties
) {
  await analytics.captureExceptionImmediate(
    error,
    distinctId,
    additionalProperties
  );
}
