const MIN_FORUM_THREAD_TEXT_LENGTH = 3;
const DEFAULT_FORUM_POST_WINDOW = 15;
const MAX_FORUM_POST_WINDOW = 50;
const MAX_FORUM_TRANSCRIPT_POSTS = 500;
const MAX_FORUM_POST_ATTACHMENTS = 10;
const MAX_FORUM_ATTACHMENT_BYTES = 10 * 1024 * 1024;
const MAX_FORUM_POST_MENTIONS = 20;
const MAX_FORUM_REACTION_VARIANTS = 20;
const MAX_FORUM_REACTION_VALUE_LENGTH = 32;
const FORUM_REACTION_PREVIEW_LIMIT = 10;
const FORUM_REACTION_PREVIEW_BATCH_LIMIT = 20;
const STUDENT_FORUM_TAGS = ["general", "question"];
const FORUM_ATTACHMENT_ALLOWED_MIME_TYPES = [
  "application/msword",
  "application/octet-stream",
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "text/plain",
];
const FORUM_ATTACHMENT_ALLOWED_EXTENSIONS = [".doc", ".docx", ".pdf", ".txt"];

export {
  DEFAULT_FORUM_POST_WINDOW,
  FORUM_ATTACHMENT_ALLOWED_EXTENSIONS,
  FORUM_ATTACHMENT_ALLOWED_MIME_TYPES,
  FORUM_REACTION_PREVIEW_BATCH_LIMIT,
  FORUM_REACTION_PREVIEW_LIMIT,
  MAX_FORUM_ATTACHMENT_BYTES,
  MAX_FORUM_POST_ATTACHMENTS,
  MAX_FORUM_POST_MENTIONS,
  MAX_FORUM_POST_WINDOW,
  MAX_FORUM_REACTION_VALUE_LENGTH,
  MAX_FORUM_REACTION_VARIANTS,
  MAX_FORUM_TRANSCRIPT_POSTS,
  MIN_FORUM_THREAD_TEXT_LENGTH,
  STUDENT_FORUM_TAGS,
};
