import { mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { scopedRegistries } from "@repo/backend/scripts/codegen/scopedRegistry.config";
import {
  getUnknownMessage,
  ScriptFailureError,
} from "@repo/backend/scripts/lib/errors";
import { Effect } from "effect";

const moduleFileName = fileURLToPath(import.meta.url);
const moduleDir = path.dirname(moduleFileName);
const backendDirectory = path.resolve(moduleDir, "../..");
const scopedRegisteredFunctionsDirectory = path.resolve(
  backendDirectory,
  "confect/_generated/registered"
);
const generatedFileHeader =
  "// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.\n";

/** Generates per-group Confect registries for Convex function modules. */
export const writeScopedRegisteredFunctions = Effect.fn(
  "codegen.writeScopedRegisteredFunctions"
)(function* () {
  yield* Effect.tryPromise({
    try: () => mkdir(scopedRegisteredFunctionsDirectory, { recursive: true }),
    catch: (error) =>
      new ScriptFailureError({ message: getUnknownMessage(error) }),
  });

  const staleFiles = yield* collectStaleScopedRegistryFiles();
  let changedFileCount = 0;

  for (const file of staleFiles) {
    yield* Effect.tryPromise({
      try: () => unlink(file),
      catch: (error) =>
        new ScriptFailureError({ message: getUnknownMessage(error) }),
    });
    changedFileCount += 1;
  }

  for (const registry of scopedRegistries) {
    const file = path.join(
      scopedRegisteredFunctionsDirectory,
      `${registry.group}.ts`
    );
    const source = getScopedRegisteredFunctionsSource(registry);
    const changed = yield* writeFileWhenChanged(file, source);

    if (changed) {
      changedFileCount += 1;
    }
  }

  return changedFileCount;
});

/** Returns generated scoped registry files that no longer match a group. */
const collectStaleScopedRegistryFiles = Effect.fn(
  "codegen.collectStaleScopedRegistryFiles"
)(function* () {
  const entries = yield* Effect.tryPromise({
    try: () =>
      readdir(scopedRegisteredFunctionsDirectory, { withFileTypes: true }),
    catch: (error) =>
      new ScriptFailureError({ message: getUnknownMessage(error) }),
  });
  const expectedFiles = new Set(
    scopedRegistries.map((registry) => `${registry.group}.ts`)
  );

  return entries
    .filter((entry) => entry.isFile() && !expectedFiles.has(entry.name))
    .map((entry) => path.join(scopedRegisteredFunctionsDirectory, entry.name));
});

/** Writes one file only when content changes. */
const writeFileWhenChanged = Effect.fn("codegen.writeFileWhenChanged")(
  function* (file: string, source: string) {
    const current = yield* Effect.tryPromise({
      try: () => readFile(file, "utf8"),
      catch: (error) =>
        new ScriptFailureError({ message: getUnknownMessage(error) }),
    }).pipe(Effect.catchAll(() => Effect.succeed(null)));

    if (current === source) {
      return false;
    }

    yield* Effect.tryPromise({
      try: () => writeFile(file, source),
      catch: (error) =>
        new ScriptFailureError({ message: getUnknownMessage(error) }),
    });
    return true;
  }
);

/** Builds one scoped registry source file. */
function getScopedRegisteredFunctionsSource(
  registry: (typeof scopedRegistries)[number]
) {
  return `${generatedFileHeader}import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { ${registry.layer} } from "${registry.layerImport}";
import { ${registry.spec} } from "${registry.specImport}";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(${registry.spec}));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(${registry.layer}), Impl.finalize),
  RegisteredConvexFunction.make
);
`;
}
