import { Schema } from "effect";

export const mathOperations = [
  "apart",
  "cancel",
  "circle",
  "combination",
  "compare",
  "cumulative_probability",
  "determinant",
  "differentiate",
  "distance",
  "distribution",
  "domain",
  "eigen_analysis",
  "eigenvalues",
  "eigenvectors",
  "evaluate",
  "expected_value",
  "expand",
  "factor",
  "gcd",
  "integrate",
  "intersection",
  "inverse",
  "interval_probability",
  "is_prime",
  "lcm",
  "limit",
  "line",
  "linear_system",
  "matrix_multiply",
  "mean",
  "median",
  "midpoint",
  "mode",
  "modular",
  "permutation",
  "point_probability",
  "prime_factorization",
  "product",
  "quartiles",
  "rank",
  "rationalize",
  "roots",
  "rref",
  "series",
  "simplify",
  "slope",
  "solve",
  "standard_deviation",
  "summation",
  "tail_probability",
  "together",
  "variance",
  "variance_probability",
  "z_score",
] as const;

export const MathOperationSchema = Schema.Literal(
  ...mathOperations
).annotations({
  description: "Supported deterministic math operation.",
});

export type MathOperation = Schema.Schema.Type<typeof MathOperationSchema>;
