import {
  Array as Arr,
  Effect,
  Order,
  Record as Rec,
  Result,
  Schema,
  String as Str,
} from "effect";
import {
  isIdentifier,
  isShorthandPropertyAssignment,
  type SourceFile,
} from "typescript/unstable/ast";
import type { API } from "typescript/unstable/sync";
import { globalCandidates } from "#scripts/check/globals";
import { nativeCandidates } from "#scripts/check/native";
import { covers, RULES, Rule } from "#scripts/check/rules";
import { effectRunnerViolation } from "#scripts/check/runtime";
import { shapeCandidates } from "#scripts/check/shapes";
import {
  descendants,
  openCompiler,
  type parseSources,
  projectConfig,
  type RepositorySource,
  TestCompilerError,
} from "#scripts/check/source";

/** One construct that breaks an Effect-native rule at a line of an authored module. */
export const Finding = Schema.Struct({
  file: Schema.String,
  line: Schema.Int,
  rule: Rule,
});

const TEST_MODULE_PATTERN = /\.test\.ts$/u;
const GENERATED_PATTERN = /\b(?:auto-?generated|@generated)\b/iu;
const FINDING_ORDER = Order.Struct({
  file: Order.String,
  line: Order.Number,
  rule: Order.String,
});

/** Keeps each test in its own native project so lexical bindings stay local. */
const inspectTest = Effect.fn("RepositoryPolicy.inspectEffectTest")(function* (
  api: API,
  index: number,
  file: string
) {
  const configFile = `/test-policy/${index}/tsconfig.json`;
  const compilerFailure = (cause: unknown) =>
    new TestCompilerError({ cause, message: `Unable to inspect ${file}.` });
  const snapshot = yield* Effect.acquireRelease(
    Effect.try({
      try: () =>
        api.updateSnapshot({
          openProjects: [configFile],
          closeProjects:
            index === 0 ? [] : [`/test-policy/${index - 1}/tsconfig.json`],
        }),
      catch: compilerFailure,
    }),
    (resource) => Effect.sync(() => resource.dispose())
  );
  const { project, sourceFile } = yield* Effect.try({
    try: () => {
      const project = snapshot.getProject(configFile);
      return {
        project,
        sourceFile: project?.program.getSourceFile(
          `/test-policy/${index}/case.test.ts`
        ),
      };
    },
    catch: compilerFailure,
  });
  if (project === undefined || sourceFile === undefined) {
    return yield* compilerFailure("The native test project is missing.");
  }
  return yield* Effect.try({
    try: () => {
      const nodes = descendants(sourceFile);
      const identifiers = Arr.filter(
        descendants(sourceFile, false),
        isIdentifier
      );
      const symbols = project.checker.getSymbolAtLocation(identifiers);
      const lexicalSymbols = new Map(Arr.zip(identifiers, symbols));
      for (const node of nodes) {
        if (isShorthandPropertyAssignment(node) && isIdentifier(node.name)) {
          lexicalSymbols.set(
            node.name,
            project.checker.getShorthandAssignmentValueSymbol(node)
          );
        }
      }
      return effectRunnerViolation(nodes, lexicalSymbols)
        ? [
            `${file}: return the Effect to @effect/vitest instead of running it.`,
          ]
        : [];
    },
    catch: compilerFailure,
  });
}, Effect.scoped);

/** Reports authored tests using one scoped, Effect-patched native compiler. */
export const effectTestViolations = Effect.fn("RepositoryPolicy.effectTests")(
  function* (sources: readonly (typeof RepositorySource.Type)[]) {
    const tests = Arr.filter(sources, ({ file }) =>
      TEST_MODULE_PATTERN.test(file)
    );
    if (Arr.isReadonlyArrayEmpty(tests)) {
      return [];
    }
    const config = yield* projectConfig(["case.test.ts"]);
    const api = yield* openCompiler(
      Rec.fromEntries(
        Arr.flatMap(tests, ({ sourceText }, index) => [
          [`/test-policy/${index}/case.test.ts`, sourceText],
          [`/test-policy/${index}/tsconfig.json`, config],
        ])
      ),
      "Unable to start the native test compiler."
    );
    return Arr.flatten(
      yield* Effect.forEach(
        tests,
        ({ file }, index) => inspectTest(api, index, file),
        { concurrency: 1 }
      )
    );
  },
  Effect.scoped
);

/** Describes each finding with the Effect replacement its rule names. */
export function findingMessages(findings: readonly (typeof Finding.Type)[]) {
  return Arr.map(
    findings,
    ({ file, line, rule }) =>
      `${file}:${line}: ${RULES[rule].message} (${rule})`
  );
}

/** Whether a module opens with a comment that marks it as generated by a tool. */
function isGenerated(sourceFile: SourceFile) {
  const [first] = sourceFile.statements;
  const header =
    first === undefined
      ? sourceFile.text
      : Str.slice(0, first.getStart(sourceFile))(sourceFile.text);
  return GENERATED_PATTERN.test(header);
}

/**
 * Finds every Effect-native rule a parsed authored module breaks. A construct
 * that names a platform global counts only when the compiler proves no import
 * or local declaration shadows the name, and an array method counts only when
 * its receiver is a value rather than an imported module.
 */
export const effectFindings = Effect.fn("RepositoryPolicy.effectFindings")(
  function* ({
    bind,
    modules,
  }: Effect.Success<ReturnType<typeof parseSources>>) {
    const candidates = Arr.flatMap(modules, ({ file, sourceFile }) => {
      if (isGenerated(sourceFile)) {
        return [];
      }
      const nodes = descendants(sourceFile);
      return Arr.filterMap(
        Arr.flatten([
          globalCandidates(sourceFile, nodes),
          nativeCandidates(sourceFile, nodes),
          shapeCandidates(file, sourceFile, nodes),
        ]),
        (found) =>
          covers(found.rule, file, sourceFile)
            ? Result.succeed({ ...found, file })
            : Result.failVoid
      );
    });
    const [unbound, bound] = Arr.partition(candidates, (found) =>
      found.reference === undefined
        ? Result.fail(found)
        : Result.succeed({ ...found, reference: found.reference })
    );
    const bindings = yield* bind(Arr.map(bound, ({ reference }) => reference));
    const kept = Arr.filterMap(Arr.zip(bound, bindings), ([found, binding]) =>
      Arr.contains(found.accepts, binding)
        ? Result.succeed(found)
        : Result.failVoid
    );
    return Arr.sort(
      Arr.map(
        Arr.appendAll(unbound, kept),
        ({ file, line, rule }): typeof Finding.Type => ({ file, line, rule })
      ),
      FINDING_ORDER
    );
  }
);
