import { NodeServices } from "@effect/platform-node";
import { assert, describe, it } from "@effect/vitest";
import { Array as Arr, Effect, FileSystem, Path, Record as Rec } from "effect";
import { inspectExports, publishedDirectories } from "#scripts/check/exports";
import { parseSources } from "#scripts/check/source";

const MODULE = "packages/shop/cart.ts";
const READER = "packages/shop/checkout.ts";

/** Names the report of one unused export. */
function report(line: number, name: string, file = MODULE) {
  return `${file}:${line}: no other module names ${name}: remove its \`export\`, or delete the declaration when this module does not use it either (unused-export)`;
}

/**
 * Inspects fixture modules with the export policy alone. `others` holds the
 * text of modules that no rule judges, and `published` the directories of the
 * published workspaces.
 */
function inspect(
  files: Readonly<Record<string, string>>,
  others: readonly string[] = [],
  published: readonly string[] = []
) {
  const sources = Arr.map(Rec.toEntries(files), ([file, sourceText]) => ({
    file,
    sourceText,
  }));
  return Effect.scoped(
    Effect.map(parseSources(sources), ({ modules }) =>
      inspectExports(
        modules,
        Arr.appendAll(
          Arr.map(sources, ({ sourceText }) => sourceText),
          others
        ),
        published
      )
    )
  );
}

/** Writes manifests below one temporary repository root. */
const repository = Effect.fn("ExportTest.repository")(function* (
  manifests: Readonly<Record<string, string>>
) {
  const fileSystem = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const root = yield* fileSystem.makeTempDirectoryScoped({
    prefix: "export-policy-",
  });
  const files = yield* Effect.forEach(
    Rec.toEntries(manifests),
    ([file, content]) =>
      Effect.as(
        Effect.andThen(
          fileSystem.makeDirectory(path.dirname(path.join(root, file)), {
            recursive: true,
          }),
          fileSystem.writeFileString(path.join(root, file), content)
        ),
        path.join(root, file)
      )
  );
  return { files, root };
});

describe("Unused export policy", () => {
  it.effect("reports each kind of declaration that nothing else names", () =>
    Effect.gen(function* () {
      assert.deepStrictEqual(
        yield* inspect({
          [MODULE]: `export const total = 1, tax = 2;
export function add() {}
export class Basket {}
export interface Line {}
export type Price = number;
export enum Step { First }
const local = 3;
export { local as shared };
`,
        }),
        [
          report(1, "total"),
          report(1, "tax"),
          report(2, "add"),
          report(3, "Basket"),
          report(4, "Line"),
          report(5, "Price"),
          report(6, "Step"),
          report(8, "shared"),
        ]
      );
    })
  );

  it.effect("accepts a name that a second module mentions", () =>
    Effect.gen(function* () {
      const files = {
        [MODULE]: "export const total = 1;\nexport type Price = number;\n",
      };
      assert.deepStrictEqual(
        yield* inspect({
          ...files,
          [READER]:
            'import { type Price, total } from "./cart";\nconst price: Price = total;\n',
        }),
        []
      );
      assert.deepStrictEqual(
        yield* inspect(files, [
          'import { total } from "../cart";\nexport type { Price } from "../cart";\n',
        ]),
        []
      );
    })
  );

  it.effect("judges only names that a module can import", () =>
    Effect.gen(function* () {
      assert.deepStrictEqual(
        yield* inspect({
          [MODULE]: `const total = 1;
const source = { tax: 2 };
export default function add() {}
export { total as default };
export { Price } from "./price";
export * from "./price";
export const { tax } = source;
`,
        }),
        []
      );
    })
  );

  it.effect("leaves modules whose exports are read by name elsewhere", () =>
    Effect.gen(function* () {
      const text = "export const maxDuration = 60;\n";
      assert.deepStrictEqual(
        yield* inspect(
          {
            "apps/www/app/[locale]/(app)/lesson/page.tsx": text,
            "apps/api/app/route.ts": text,
            "apps/www/proxy.ts": text,
            "apps/www/vercel.ts": text,
            "packages/design-system/components/ui/table.tsx": text,
            "packages/cli/src/client.ts": text,
            "packages/shop/tables.ts": `// @generated by a tool\n${text}`,
          },
          [],
          ["packages/cli/"]
        ),
        []
      );
      assert.deepStrictEqual(
        yield* inspect({
          "apps/www/components/app/page.tsx": text,
          "packages/shop/proxy.ts": "export const proxied = 1;\n",
        }),
        [
          report(1, "maxDuration", "apps/www/components/app/page.tsx"),
          report(1, "proxied", "packages/shop/proxy.ts"),
        ]
      );
    })
  );

  it.effect("names each workspace whose manifest is not private", () =>
    Effect.gen(function* () {
      const { files, root } = yield* repository({
        "apps/www/package.json": '{"name":"www","private":true}\n',
        "packages/cli/package.json": '{"name":"@shop/cli"}\n',
        "packages/kit/package.json": '{"name":"@shop/kit","private":false}\n',
        "packages/kit/fixture/package.json": '{"name":"nested"}\n',
        "packages/kit/client.ts": "export const client = 1;\n",
      });
      assert.deepStrictEqual(yield* publishedDirectories(root, files), [
        "packages/cli/",
        "packages/kit/",
      ]);
    }).pipe(Effect.provide(NodeServices.layer))
  );

  it.effect("fails when a workspace manifest is not a manifest", () =>
    Effect.gen(function* () {
      const { files, root } = yield* repository({
        "packages/kit/package.json": '{"private":"yes"}\n',
      });
      const error = yield* Effect.flip(publishedDirectories(root, files));
      assert.strictEqual(error._tag, "RepositoryReadError");
      assert.strictEqual(
        error.message,
        "Unable to read packages/kit/package.json as a package manifest."
      );
    }).pipe(Effect.provide(NodeServices.layer))
  );
});
