import { assert, describe, it } from "@effect/vitest";
import { Array as Arr, Effect } from "effect";
import { inspectModuleSize } from "#scripts/check/size";
import { parseSources } from "#scripts/check/source";

const MODULE = "apps/www/lib/example.ts";

/** Builds a module of `count` lines, each one a statement. */
function moduleOf(count: number, header = "") {
  return `${header}${Arr.join(
    Arr.makeBy(count, (index) => `export const value${index} = ${index};`),
    "\n"
  )}\n`;
}

/** Inspects one module with the size policy alone. */
function inspect(sourceText: string) {
  return Effect.scoped(
    Effect.map(parseSources([{ file: MODULE, sourceText }]), ({ modules }) =>
      Arr.flatMap(modules, (parsed) =>
        inspectModuleSize(parsed.file, parsed.sourceFile)
      )
    )
  );
}

describe("Module size policy", () => {
  it.effect("accepts a module of exactly the limit", () =>
    Effect.gen(function* () {
      assert.deepStrictEqual(yield* inspect(moduleOf(500)), []);
    })
  );

  it.effect("reports a module that is one line longer, with its count", () =>
    Effect.gen(function* () {
      assert.deepStrictEqual(yield* inspect(moduleOf(501)), [
        `${MODULE}: split this module by capability: it has 501 lines, and a hand-written module has at most 500.`,
      ]);
    })
  );

  it.effect("leaves a module that a tool generated alone", () =>
    Effect.gen(function* () {
      assert.deepStrictEqual(
        yield* inspect(moduleOf(600, "// @generated by a tool\n")),
        []
      );
    })
  );
});
