/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as analytics_capture from "../analytics/capture.js";
import type * as analytics_events from "../analytics/events.js";
import type * as assessments_helpers_access from "../assessments/helpers/access.js";
import type * as assessments_helpers_attempts from "../assessments/helpers/attempts.js";
import type * as assessments_helpers_authoring from "../assessments/helpers/authoring.js";
import type * as assessments_helpers_bank from "../assessments/helpers/bank.js";
import type * as assessments_helpers_content from "../assessments/helpers/content.js";
import type * as assessments_helpers_publishing from "../assessments/helpers/publishing.js";
import type * as assessments_mutations_internal_publishing from "../assessments/mutations/internal/publishing.js";
import type * as assessments_mutations_public_assign from "../assessments/mutations/public/assign.js";
import type * as assessments_mutations_public_bank from "../assessments/mutations/public/bank.js";
import type * as assessments_mutations_public_create from "../assessments/mutations/public/create.js";
import type * as assessments_mutations_public_delete from "../assessments/mutations/public/delete.js";
import type * as assessments_mutations_public_questions from "../assessments/mutations/public/questions.js";
import type * as assessments_mutations_public_reorder from "../assessments/mutations/public/reorder.js";
import type * as assessments_mutations_public_save from "../assessments/mutations/public/save.js";
import type * as assessments_mutations_public_sections from "../assessments/mutations/public/sections.js";
import type * as assessments_mutations_public_start from "../assessments/mutations/public/start.js";
import type * as assessments_mutations_public_submit from "../assessments/mutations/public/submit.js";
import type * as assessments_mutations_public_update from "../assessments/mutations/public/update.js";
import type * as assessments_mutations_public_version from "../assessments/mutations/public/version.js";
import type * as assessments_queries_public_assignment from "../assessments/queries/public/assignment.js";
import type * as assessments_queries_public_authoring from "../assessments/queries/public/authoring.js";
import type * as assessments_queries_public_bank from "../assessments/queries/public/bank.js";
import type * as assessments_queries_public_list from "../assessments/queries/public/list.js";
import type * as assessments_seed from "../assessments/seed.js";
import type * as assessments_validators from "../assessments/validators.js";
import type * as audioStudies_actions from "../audioStudies/actions.js";
import type * as audioStudies_constants from "../audioStudies/constants.js";
import type * as audioStudies_content_spec from "../audioStudies/content/spec.js";
import type * as audioStudies_contentAudios_impl from "../audioStudies/contentAudios/impl.js";
import type * as audioStudies_contentAudios_spec from "../audioStudies/contentAudios/spec.js";
import type * as audioStudies_generation_impl from "../audioStudies/generation/impl.js";
import type * as audioStudies_generation_spec from "../audioStudies/generation/spec.js";
import type * as audioStudies_helpers_sources from "../audioStudies/helpers/sources.js";
import type * as audioStudies_mutations_contentAudios from "../audioStudies/mutations/contentAudios.js";
import type * as audioStudies_mutations_queue from "../audioStudies/mutations/queue.js";
import type * as audioStudies_queries_internal from "../audioStudies/queries/internal.js";
import type * as audioStudies_queries_public from "../audioStudies/queries/public.js";
import type * as audioStudies_queries_public_impl from "../audioStudies/queries/public/impl.js";
import type * as audioStudies_queries_public_spec from "../audioStudies/queries/public/spec.js";
import type * as audioStudies_workflows from "../audioStudies/workflows.js";
import type * as auth_actions from "../auth/actions.js";
import type * as auth_cleanup from "../auth/cleanup.js";
import type * as auth_client from "../auth/client.js";
import type * as auth_lifecycle from "../auth/lifecycle.js";
import type * as auth_queries from "../auth/queries.js";
import type * as auth_reader from "../auth/reader.js";
import type * as auth_runtime from "../auth/runtime.js";
import type * as auth_username_availability from "../auth/username/availability.js";
import type * as auth_username_plugin from "../auth/username/plugin.js";
import type * as auth_username_policy from "../auth/username/policy.js";
import type * as auth_username_request from "../auth/username/request.js";
import type * as chats_actions from "../chats/actions.js";
import type * as chats_assistantResponses_impl from "../chats/assistantResponses/impl.js";
import type * as chats_constants from "../chats/constants.js";
import type * as chats_context from "../chats/context.js";
import type * as chats_helpers from "../chats/helpers.js";
import type * as chats_messageParts_dbToUi from "../chats/messageParts/dbToUi.js";
import type * as chats_messageParts_providerMetadata from "../chats/messageParts/providerMetadata.js";
import type * as chats_messageParts_shared from "../chats/messageParts/shared.js";
import type * as chats_messageParts_uiToDb from "../chats/messageParts/uiToDb.js";
import type * as chats_mutations from "../chats/mutations.js";
import type * as chats_queries from "../chats/queries.js";
import type * as chats_read from "../chats/read.js";
import type * as chats_traces_impl from "../chats/traces/impl.js";
import type * as chats_traces_mutations from "../chats/traces/mutations.js";
import type * as chats_traces_queries from "../chats/traces/queries.js";
import type * as chats_traces_spec from "../chats/traces/spec.js";
import type * as chats_utils from "../chats/utils.js";
import type * as classes_constants from "../classes/constants.js";
import type * as classes_forums_aggregate from "../classes/forums/aggregate.js";
import type * as classes_forums_attachments_impl from "../classes/forums/attachments/impl.js";
import type * as classes_forums_attachments_spec from "../classes/forums/attachments/spec.js";
import type * as classes_forums_internalMutations from "../classes/forums/internalMutations.js";
import type * as classes_forums_mutations_forums from "../classes/forums/mutations/forums.js";
import type * as classes_forums_mutations_posts from "../classes/forums/mutations/posts.js";
import type * as classes_forums_mutations_reactions from "../classes/forums/mutations/reactions.js";
import type * as classes_forums_mutations_readState from "../classes/forums/mutations/readState.js";
import type * as classes_forums_mutations_uploads from "../classes/forums/mutations/uploads.js";
import type * as classes_forums_queries_forums from "../classes/forums/queries/forums.js";
import type * as classes_forums_queries_pages from "../classes/forums/queries/pages.js";
import type * as classes_forums_utils_access from "../classes/forums/utils/access.js";
import type * as classes_forums_utils_constants from "../classes/forums/utils/constants.js";
import type * as classes_forums_utils_mentions from "../classes/forums/utils/mentions.js";
import type * as classes_forums_utils_postReactions from "../classes/forums/utils/postReactions.js";
import type * as classes_forums_utils_posts from "../classes/forums/utils/posts.js";
import type * as classes_forums_utils_reactions from "../classes/forums/utils/reactions.js";
import type * as classes_forums_utils_readStateWrite from "../classes/forums/utils/readStateWrite.js";
import type * as classes_forums_utils_unreadCounts from "../classes/forums/utils/unreadCounts.js";
import type * as classes_forums_validators from "../classes/forums/validators.js";
import type * as classes_materials_mutations from "../classes/materials/mutations.js";
import type * as classes_materials_queries from "../classes/materials/queries.js";
import type * as classes_materials_utils from "../classes/materials/utils.js";
import type * as classes_mutations from "../classes/mutations.js";
import type * as classes_queries from "../classes/queries.js";
import type * as classes_utils from "../classes/utils.js";
import type * as classes_validators from "../classes/validators.js";
import type * as comments_mutations from "../comments/mutations.js";
import type * as comments_queries from "../comments/queries.js";
import type * as contentSync_constants from "../contentSync/constants.js";
import type * as contentSync_integrity_graph from "../contentSync/integrity/graph.js";
import type * as contentSync_integrity_tryouts from "../contentSync/integrity/tryouts.js";
import type * as contentSync_lib_errors from "../contentSync/lib/errors.js";
import type * as contentSync_lib_syncHelpers from "../contentSync/lib/syncHelpers.js";
import type * as contentSync_lib_syncValues from "../contentSync/lib/syncValues.js";
import type * as contentSync_mutations_articles from "../contentSync/mutations/articles.js";
import type * as contentSync_mutations_authors from "../contentSync/mutations/authors.js";
import type * as contentSync_mutations_curriculum from "../contentSync/mutations/curriculum.js";
import type * as contentSync_mutations_quran from "../contentSync/mutations/quran.js";
import type * as contentSync_mutations_readModels_routes from "../contentSync/mutations/readModels/routes.js";
import type * as contentSync_mutations_readModels_stale from "../contentSync/mutations/readModels/stale.js";
import type * as contentSync_mutations_routes from "../contentSync/mutations/routes.js";
import type * as contentSync_mutations_tryouts from "../contentSync/mutations/tryouts.js";
import type * as contentSync_queries_authors from "../contentSync/queries/authors.js";
import type * as contentSync_queries_counts from "../contentSync/queries/counts.js";
import type * as contentSync_queries_integrity from "../contentSync/queries/integrity.js";
import type * as contentSync_queries_stale from "../contentSync/queries/stale.js";
import type * as contentSync_reset_impl from "../contentSync/reset/impl.js";
import type * as contentSync_reset_internal from "../contentSync/reset/internal.js";
import type * as contentSync_reset_spec from "../contentSync/reset/spec.js";
import type * as contentSync_tables from "../contentSync/tables.js";
import type * as contentSync_tryouts_impl from "../contentSync/tryouts/impl.js";
import type * as contentSync_tryouts_irt from "../contentSync/tryouts/irt.js";
import type * as contentSync_tryouts_questionBank from "../contentSync/tryouts/questionBank.js";
import type * as contentSync_tryouts_route from "../contentSync/tryouts/route.js";
import type * as contentSync_tryouts_spec from "../contentSync/tryouts/spec.js";
import type * as contentSync_tryouts_stale from "../contentSync/tryouts/stale.js";
import type * as contents_actions_queue from "../contents/actions/queue.js";
import type * as contents_analytics_impl from "../contents/analytics/impl.js";
import type * as contents_analytics_spec from "../contents/analytics/spec.js";
import type * as contents_audioQueue_impl from "../contents/audioQueue/impl.js";
import type * as contents_audioQueue_spec from "../contents/audioQueue/spec.js";
import type * as contents_constants from "../contents/constants.js";
import type * as contents_context from "../contents/context.js";
import type * as contents_graph from "../contents/graph.js";
import type * as contents_helpers_partitions from "../contents/helpers/partitions.js";
import type * as contents_helpers_popularity from "../contents/helpers/popularity.js";
import type * as contents_helpers_routes_write from "../contents/helpers/routes/write.js";
import type * as contents_helpers_search_constants from "../contents/helpers/search/constants.js";
import type * as contents_helpers_search_documents from "../contents/helpers/search/documents.js";
import type * as contents_helpers_search_excerpt from "../contents/helpers/search/excerpt.js";
import type * as contents_helpers_search_input from "../contents/helpers/search/input.js";
import type * as contents_helpers_search_rank from "../contents/helpers/search/rank.js";
import type * as contents_helpers_search_read from "../contents/helpers/search/read.js";
import type * as contents_helpers_search_result from "../contents/helpers/search/result.js";
import type * as contents_helpers_search_write from "../contents/helpers/search/write.js";
import type * as contents_metrics_apply from "../contents/metrics/apply.js";
import type * as contents_metrics_batch from "../contents/metrics/batch.js";
import type * as contents_metrics_refresh from "../contents/metrics/refresh.js";
import type * as contents_mutations_analytics from "../contents/mutations/analytics.js";
import type * as contents_mutations_audio from "../contents/mutations/audio.js";
import type * as contents_mutations_popularity from "../contents/mutations/popularity.js";
import type * as contents_mutations_search from "../contents/mutations/search.js";
import type * as contents_mutations_views from "../contents/mutations/views.js";
import type * as contents_popularity from "../contents/popularity.js";
import type * as contents_queries_audio from "../contents/queries/audio.js";
import type * as contents_queries_recent from "../contents/queries/recent.js";
import type * as contents_queries_runtime from "../contents/queries/runtime.js";
import type * as contents_queries_search from "../contents/queries/search.js";
import type * as contents_rankings from "../contents/rankings.js";
import type * as contents_runtime_api from "../contents/runtime/api.js";
import type * as contents_runtime_articles from "../contents/runtime/articles.js";
import type * as contents_runtime_catalog from "../contents/runtime/catalog.js";
import type * as contents_runtime_curriculum from "../contents/runtime/curriculum.js";
import type * as contents_runtime_quran from "../contents/runtime/quran.js";
import type * as contents_runtime_routes from "../contents/runtime/routes.js";
import type * as contents_runtime_shared from "../contents/runtime/shared.js";
import type * as contents_runtime_spec from "../contents/runtime/spec.js";
import type * as contents_validators from "../contents/validators.js";
import type * as contents_views_context from "../contents/views/context.js";
import type * as contents_views_impl from "../contents/views/impl.js";
import type * as contents_views_recent from "../contents/views/recent.js";
import type * as contents_views_signals from "../contents/views/signals.js";
import type * as contents_views_spec from "../contents/views/spec.js";
import type * as credits_constants from "../credits/constants.js";
import type * as credits_helpers_state from "../credits/helpers/state.js";
import type * as credits_mutations from "../credits/mutations.js";
import type * as crons from "../crons.js";
import type * as curriculumLessons_queries from "../curriculumLessons/queries.js";
import type * as curriculumLessons_trending_impl from "../curriculumLessons/trending/impl.js";
import type * as curriculumLessons_trending_spec from "../curriculumLessons/trending/spec.js";
import type * as customers_actions_internal from "../customers/actions/internal.js";
import type * as customers_actions_public from "../customers/actions/public.js";
import type * as customers_checkout_impl from "../customers/checkout/impl.js";
import type * as customers_checkout_localization from "../customers/checkout/localization.js";
import type * as customers_checkout_spec from "../customers/checkout/spec.js";
import type * as customers_integrity_internal from "../customers/integrity/internal.js";
import type * as customers_mutations_internal from "../customers/mutations/internal.js";
import type * as customers_polar_impl from "../customers/polar/impl.js";
import type * as customers_polar_live from "../customers/polar/live.js";
import type * as customers_polar_spec from "../customers/polar/spec.js";
import type * as customers_queries_internal_customer from "../customers/queries/internal/customer.js";
import type * as customers_records from "../customers/records.js";
import type * as customers_sync_impl from "../customers/sync/impl.js";
import type * as customers_sync_spec from "../customers/sync/spec.js";
import type * as emails_mutations from "../emails/mutations.js";
import type * as functions from "../functions.js";
import type * as http from "../http.js";
import type * as learningPreferences_impl from "../learningPreferences/impl.js";
import type * as learningPreferences_mutations from "../learningPreferences/mutations.js";
import type * as learningPreferences_queries from "../learningPreferences/queries.js";
import type * as learningPrograms_catalog from "../learningPrograms/catalog.js";
import type * as learningPrograms_impl from "../learningPrograms/impl.js";
import type * as learningPrograms_mutations from "../learningPrograms/mutations.js";
import type * as learningPrograms_omitted from "../learningPrograms/omitted.js";
import type * as learningPrograms_queries from "../learningPrograms/queries.js";
import type * as learningPrograms_sources from "../learningPrograms/sources.js";
import type * as learningPrograms_sync from "../learningPrograms/sync.js";
import type * as lib_attempts from "../lib/attempts.js";
import type * as lib_effect from "../lib/effect.js";
import type * as lib_helpers_auth from "../lib/helpers/auth.js";
import type * as lib_helpers_chat from "../lib/helpers/chat.js";
import type * as lib_helpers_class from "../lib/helpers/class.js";
import type * as lib_helpers_invite from "../lib/helpers/invite.js";
import type * as lib_helpers_permissions from "../lib/helpers/permissions.js";
import type * as lib_helpers_school from "../lib/helpers/school.js";
import type * as lib_helpers_user from "../lib/helpers/user.js";
import type * as lib_images from "../lib/images.js";
import type * as lib_validators_audio from "../lib/validators/audio.js";
import type * as lib_validators_contents from "../lib/validators/contents.js";
import type * as lib_validators_trending from "../lib/validators/trending.js";
import type * as lib_validators_user from "../lib/validators/user.js";
import type * as lib_validators_vv from "../lib/validators/vv.js";
import type * as notifications_mutations from "../notifications/mutations.js";
import type * as notifications_queries from "../notifications/queries.js";
import type * as polyfills from "../polyfills.js";
import type * as posthog from "../posthog.js";
import type * as routes_constants from "../routes/constants.js";
import type * as routes_middleware_requestId from "../routes/middleware/requestId.js";
import type * as routes_polar from "../routes/polar.js";
import type * as routes_v1_index from "../routes/v1/index.js";
import type * as schools_mutations from "../schools/mutations.js";
import type * as schools_queries from "../schools/queries.js";
import type * as schools_utils from "../schools/utils.js";
import type * as schools_validators from "../schools/validators.js";
import type * as subscriptions_mutations from "../subscriptions/mutations.js";
import type * as subscriptions_queries from "../subscriptions/queries.js";
import type * as subscriptions_records_impl from "../subscriptions/records/impl.js";
import type * as subscriptions_records_spec from "../subscriptions/records/spec.js";
import type * as subscriptions_utils from "../subscriptions/utils.js";
import type * as triggers_chats_chats from "../triggers/chats/chats.js";
import type * as triggers_chats_cleanup from "../triggers/chats/cleanup.js";
import type * as triggers_chats_messages from "../triggers/chats/messages.js";
import type * as triggers_comments_cleanup from "../triggers/comments/cleanup.js";
import type * as triggers_comments_commentVotes from "../triggers/comments/commentVotes.js";
import type * as triggers_comments_comments from "../triggers/comments/comments.js";
import type * as triggers_contents_popularity from "../triggers/contents/popularity.js";
import type * as triggers_contents_views from "../triggers/contents/views.js";
import type * as triggers_forums_postReactions from "../triggers/forums/postReactions.js";
import type * as triggers_forums_posts from "../triggers/forums/posts.js";
import type * as triggers_forums_reactions from "../triggers/forums/reactions.js";
import type * as triggers_helpers_classes from "../triggers/helpers/classes.js";
import type * as triggers_helpers_forumPosts from "../triggers/helpers/forumPosts.js";
import type * as triggers_helpers_metadata from "../triggers/helpers/metadata.js";
import type * as triggers_helpers_notifications from "../triggers/helpers/notifications.js";
import type * as triggers_materials_cleanup from "../triggers/materials/cleanup.js";
import type * as triggers_materials_groups from "../triggers/materials/groups.js";
import type * as triggers_materials_materials from "../triggers/materials/materials.js";
import type * as triggers_notifications_notifications from "../triggers/notifications/notifications.js";
import type * as triggers_schools_classMembers from "../triggers/schools/classMembers.js";
import type * as triggers_schools_classes from "../triggers/schools/classes.js";
import type * as triggers_schools_cleanup from "../triggers/schools/cleanup.js";
import type * as triggers_schools_members from "../triggers/schools/members.js";
import type * as triggers_schools_schools from "../triggers/schools/schools.js";
import type * as triggers_subscriptions_impl from "../triggers/subscriptions/impl.js";
import type * as triggers_subscriptions_spec from "../triggers/subscriptions/spec.js";
import type * as triggers_subscriptions_subscriptions from "../triggers/subscriptions/subscriptions.js";
import type * as tryouts_mutations_attempts from "../tryouts/mutations/attempts.js";
import type * as tryouts_mutations_expiry from "../tryouts/mutations/expiry.js";
import type * as tryouts_mutations_sections from "../tryouts/mutations/sections.js";
import type * as tryouts_queries_attempt from "../tryouts/queries/attempt.js";
import type * as tryouts_queries_catalog from "../tryouts/queries/catalog.js";
import type * as tryouts_queries_catalogModel from "../tryouts/queries/catalogModel.js";
import type * as tryouts_queries_parents from "../tryouts/queries/parents.js";
import type * as tryouts_queries_sets from "../tryouts/queries/sets.js";
import type * as tryouts_questions from "../tryouts/questions.js";
import type * as tryouts_read from "../tryouts/read.js";
import type * as tryouts_runtime_access from "../tryouts/runtime/access.js";
import type * as tryouts_runtime_finish from "../tryouts/runtime/finish.js";
import type * as tryouts_runtime_irt from "../tryouts/runtime/irt.js";
import type * as tryouts_runtime_placement from "../tryouts/runtime/placement.js";
import type * as tryouts_runtime_result from "../tryouts/runtime/result.js";
import type * as tryouts_runtime_score from "../tryouts/runtime/score.js";
import type * as tryouts_runtime_sectionAttempt from "../tryouts/runtime/sectionAttempt.js";
import type * as users_mutations from "../users/mutations.js";
import type * as users_queries from "../users/queries.js";
import type * as users_roles from "../users/roles.js";
import type * as utils_error from "../utils/error.js";
import type * as utils_id from "../utils/id.js";
import type * as utils_logger from "../utils/logger.js";
import type * as utils_number from "../utils/number.js";
import type * as utils_polar_client from "../utils/polar/client.js";
import type * as utils_polar_config from "../utils/polar/config.js";
import type * as utils_polar_env from "../utils/polar/env.js";
import type * as utils_polar_products from "../utils/polar/products.js";
import type * as utils_polar_webhook from "../utils/polar/webhook.js";
import type * as utils_site from "../utils/site.js";
import type * as utils_text from "../utils/text.js";
import type * as utils_type from "../utils/type.js";
import type * as workflow from "../workflow.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "analytics/capture": typeof analytics_capture;
  "analytics/events": typeof analytics_events;
  "assessments/helpers/access": typeof assessments_helpers_access;
  "assessments/helpers/attempts": typeof assessments_helpers_attempts;
  "assessments/helpers/authoring": typeof assessments_helpers_authoring;
  "assessments/helpers/bank": typeof assessments_helpers_bank;
  "assessments/helpers/content": typeof assessments_helpers_content;
  "assessments/helpers/publishing": typeof assessments_helpers_publishing;
  "assessments/mutations/internal/publishing": typeof assessments_mutations_internal_publishing;
  "assessments/mutations/public/assign": typeof assessments_mutations_public_assign;
  "assessments/mutations/public/bank": typeof assessments_mutations_public_bank;
  "assessments/mutations/public/create": typeof assessments_mutations_public_create;
  "assessments/mutations/public/delete": typeof assessments_mutations_public_delete;
  "assessments/mutations/public/questions": typeof assessments_mutations_public_questions;
  "assessments/mutations/public/reorder": typeof assessments_mutations_public_reorder;
  "assessments/mutations/public/save": typeof assessments_mutations_public_save;
  "assessments/mutations/public/sections": typeof assessments_mutations_public_sections;
  "assessments/mutations/public/start": typeof assessments_mutations_public_start;
  "assessments/mutations/public/submit": typeof assessments_mutations_public_submit;
  "assessments/mutations/public/update": typeof assessments_mutations_public_update;
  "assessments/mutations/public/version": typeof assessments_mutations_public_version;
  "assessments/queries/public/assignment": typeof assessments_queries_public_assignment;
  "assessments/queries/public/authoring": typeof assessments_queries_public_authoring;
  "assessments/queries/public/bank": typeof assessments_queries_public_bank;
  "assessments/queries/public/list": typeof assessments_queries_public_list;
  "assessments/seed": typeof assessments_seed;
  "assessments/validators": typeof assessments_validators;
  "audioStudies/actions": typeof audioStudies_actions;
  "audioStudies/constants": typeof audioStudies_constants;
  "audioStudies/content/spec": typeof audioStudies_content_spec;
  "audioStudies/contentAudios/impl": typeof audioStudies_contentAudios_impl;
  "audioStudies/contentAudios/spec": typeof audioStudies_contentAudios_spec;
  "audioStudies/generation/impl": typeof audioStudies_generation_impl;
  "audioStudies/generation/spec": typeof audioStudies_generation_spec;
  "audioStudies/helpers/sources": typeof audioStudies_helpers_sources;
  "audioStudies/mutations/contentAudios": typeof audioStudies_mutations_contentAudios;
  "audioStudies/mutations/queue": typeof audioStudies_mutations_queue;
  "audioStudies/queries/internal": typeof audioStudies_queries_internal;
  "audioStudies/queries/public": typeof audioStudies_queries_public;
  "audioStudies/queries/public/impl": typeof audioStudies_queries_public_impl;
  "audioStudies/queries/public/spec": typeof audioStudies_queries_public_spec;
  "audioStudies/workflows": typeof audioStudies_workflows;
  "auth/actions": typeof auth_actions;
  "auth/cleanup": typeof auth_cleanup;
  "auth/client": typeof auth_client;
  "auth/lifecycle": typeof auth_lifecycle;
  "auth/queries": typeof auth_queries;
  "auth/reader": typeof auth_reader;
  "auth/runtime": typeof auth_runtime;
  "auth/username/availability": typeof auth_username_availability;
  "auth/username/plugin": typeof auth_username_plugin;
  "auth/username/policy": typeof auth_username_policy;
  "auth/username/request": typeof auth_username_request;
  "chats/actions": typeof chats_actions;
  "chats/assistantResponses/impl": typeof chats_assistantResponses_impl;
  "chats/constants": typeof chats_constants;
  "chats/context": typeof chats_context;
  "chats/helpers": typeof chats_helpers;
  "chats/messageParts/dbToUi": typeof chats_messageParts_dbToUi;
  "chats/messageParts/providerMetadata": typeof chats_messageParts_providerMetadata;
  "chats/messageParts/shared": typeof chats_messageParts_shared;
  "chats/messageParts/uiToDb": typeof chats_messageParts_uiToDb;
  "chats/mutations": typeof chats_mutations;
  "chats/queries": typeof chats_queries;
  "chats/read": typeof chats_read;
  "chats/traces/impl": typeof chats_traces_impl;
  "chats/traces/mutations": typeof chats_traces_mutations;
  "chats/traces/queries": typeof chats_traces_queries;
  "chats/traces/spec": typeof chats_traces_spec;
  "chats/utils": typeof chats_utils;
  "classes/constants": typeof classes_constants;
  "classes/forums/aggregate": typeof classes_forums_aggregate;
  "classes/forums/attachments/impl": typeof classes_forums_attachments_impl;
  "classes/forums/attachments/spec": typeof classes_forums_attachments_spec;
  "classes/forums/internalMutations": typeof classes_forums_internalMutations;
  "classes/forums/mutations/forums": typeof classes_forums_mutations_forums;
  "classes/forums/mutations/posts": typeof classes_forums_mutations_posts;
  "classes/forums/mutations/reactions": typeof classes_forums_mutations_reactions;
  "classes/forums/mutations/readState": typeof classes_forums_mutations_readState;
  "classes/forums/mutations/uploads": typeof classes_forums_mutations_uploads;
  "classes/forums/queries/forums": typeof classes_forums_queries_forums;
  "classes/forums/queries/pages": typeof classes_forums_queries_pages;
  "classes/forums/utils/access": typeof classes_forums_utils_access;
  "classes/forums/utils/constants": typeof classes_forums_utils_constants;
  "classes/forums/utils/mentions": typeof classes_forums_utils_mentions;
  "classes/forums/utils/postReactions": typeof classes_forums_utils_postReactions;
  "classes/forums/utils/posts": typeof classes_forums_utils_posts;
  "classes/forums/utils/reactions": typeof classes_forums_utils_reactions;
  "classes/forums/utils/readStateWrite": typeof classes_forums_utils_readStateWrite;
  "classes/forums/utils/unreadCounts": typeof classes_forums_utils_unreadCounts;
  "classes/forums/validators": typeof classes_forums_validators;
  "classes/materials/mutations": typeof classes_materials_mutations;
  "classes/materials/queries": typeof classes_materials_queries;
  "classes/materials/utils": typeof classes_materials_utils;
  "classes/mutations": typeof classes_mutations;
  "classes/queries": typeof classes_queries;
  "classes/utils": typeof classes_utils;
  "classes/validators": typeof classes_validators;
  "comments/mutations": typeof comments_mutations;
  "comments/queries": typeof comments_queries;
  "contentSync/constants": typeof contentSync_constants;
  "contentSync/integrity/graph": typeof contentSync_integrity_graph;
  "contentSync/integrity/tryouts": typeof contentSync_integrity_tryouts;
  "contentSync/lib/errors": typeof contentSync_lib_errors;
  "contentSync/lib/syncHelpers": typeof contentSync_lib_syncHelpers;
  "contentSync/lib/syncValues": typeof contentSync_lib_syncValues;
  "contentSync/mutations/articles": typeof contentSync_mutations_articles;
  "contentSync/mutations/authors": typeof contentSync_mutations_authors;
  "contentSync/mutations/curriculum": typeof contentSync_mutations_curriculum;
  "contentSync/mutations/quran": typeof contentSync_mutations_quran;
  "contentSync/mutations/readModels/routes": typeof contentSync_mutations_readModels_routes;
  "contentSync/mutations/readModels/stale": typeof contentSync_mutations_readModels_stale;
  "contentSync/mutations/routes": typeof contentSync_mutations_routes;
  "contentSync/mutations/tryouts": typeof contentSync_mutations_tryouts;
  "contentSync/queries/authors": typeof contentSync_queries_authors;
  "contentSync/queries/counts": typeof contentSync_queries_counts;
  "contentSync/queries/integrity": typeof contentSync_queries_integrity;
  "contentSync/queries/stale": typeof contentSync_queries_stale;
  "contentSync/reset/impl": typeof contentSync_reset_impl;
  "contentSync/reset/internal": typeof contentSync_reset_internal;
  "contentSync/reset/spec": typeof contentSync_reset_spec;
  "contentSync/tables": typeof contentSync_tables;
  "contentSync/tryouts/impl": typeof contentSync_tryouts_impl;
  "contentSync/tryouts/irt": typeof contentSync_tryouts_irt;
  "contentSync/tryouts/questionBank": typeof contentSync_tryouts_questionBank;
  "contentSync/tryouts/route": typeof contentSync_tryouts_route;
  "contentSync/tryouts/spec": typeof contentSync_tryouts_spec;
  "contentSync/tryouts/stale": typeof contentSync_tryouts_stale;
  "contents/actions/queue": typeof contents_actions_queue;
  "contents/analytics/impl": typeof contents_analytics_impl;
  "contents/analytics/spec": typeof contents_analytics_spec;
  "contents/audioQueue/impl": typeof contents_audioQueue_impl;
  "contents/audioQueue/spec": typeof contents_audioQueue_spec;
  "contents/constants": typeof contents_constants;
  "contents/context": typeof contents_context;
  "contents/graph": typeof contents_graph;
  "contents/helpers/partitions": typeof contents_helpers_partitions;
  "contents/helpers/popularity": typeof contents_helpers_popularity;
  "contents/helpers/routes/write": typeof contents_helpers_routes_write;
  "contents/helpers/search/constants": typeof contents_helpers_search_constants;
  "contents/helpers/search/documents": typeof contents_helpers_search_documents;
  "contents/helpers/search/excerpt": typeof contents_helpers_search_excerpt;
  "contents/helpers/search/input": typeof contents_helpers_search_input;
  "contents/helpers/search/rank": typeof contents_helpers_search_rank;
  "contents/helpers/search/read": typeof contents_helpers_search_read;
  "contents/helpers/search/result": typeof contents_helpers_search_result;
  "contents/helpers/search/write": typeof contents_helpers_search_write;
  "contents/metrics/apply": typeof contents_metrics_apply;
  "contents/metrics/batch": typeof contents_metrics_batch;
  "contents/metrics/refresh": typeof contents_metrics_refresh;
  "contents/mutations/analytics": typeof contents_mutations_analytics;
  "contents/mutations/audio": typeof contents_mutations_audio;
  "contents/mutations/popularity": typeof contents_mutations_popularity;
  "contents/mutations/search": typeof contents_mutations_search;
  "contents/mutations/views": typeof contents_mutations_views;
  "contents/popularity": typeof contents_popularity;
  "contents/queries/audio": typeof contents_queries_audio;
  "contents/queries/recent": typeof contents_queries_recent;
  "contents/queries/runtime": typeof contents_queries_runtime;
  "contents/queries/search": typeof contents_queries_search;
  "contents/rankings": typeof contents_rankings;
  "contents/runtime/api": typeof contents_runtime_api;
  "contents/runtime/articles": typeof contents_runtime_articles;
  "contents/runtime/catalog": typeof contents_runtime_catalog;
  "contents/runtime/curriculum": typeof contents_runtime_curriculum;
  "contents/runtime/quran": typeof contents_runtime_quran;
  "contents/runtime/routes": typeof contents_runtime_routes;
  "contents/runtime/shared": typeof contents_runtime_shared;
  "contents/runtime/spec": typeof contents_runtime_spec;
  "contents/validators": typeof contents_validators;
  "contents/views/context": typeof contents_views_context;
  "contents/views/impl": typeof contents_views_impl;
  "contents/views/recent": typeof contents_views_recent;
  "contents/views/signals": typeof contents_views_signals;
  "contents/views/spec": typeof contents_views_spec;
  "credits/constants": typeof credits_constants;
  "credits/helpers/state": typeof credits_helpers_state;
  "credits/mutations": typeof credits_mutations;
  crons: typeof crons;
  "curriculumLessons/queries": typeof curriculumLessons_queries;
  "curriculumLessons/trending/impl": typeof curriculumLessons_trending_impl;
  "curriculumLessons/trending/spec": typeof curriculumLessons_trending_spec;
  "customers/actions/internal": typeof customers_actions_internal;
  "customers/actions/public": typeof customers_actions_public;
  "customers/checkout/impl": typeof customers_checkout_impl;
  "customers/checkout/localization": typeof customers_checkout_localization;
  "customers/checkout/spec": typeof customers_checkout_spec;
  "customers/integrity/internal": typeof customers_integrity_internal;
  "customers/mutations/internal": typeof customers_mutations_internal;
  "customers/polar/impl": typeof customers_polar_impl;
  "customers/polar/live": typeof customers_polar_live;
  "customers/polar/spec": typeof customers_polar_spec;
  "customers/queries/internal/customer": typeof customers_queries_internal_customer;
  "customers/records": typeof customers_records;
  "customers/sync/impl": typeof customers_sync_impl;
  "customers/sync/spec": typeof customers_sync_spec;
  "emails/mutations": typeof emails_mutations;
  functions: typeof functions;
  http: typeof http;
  "learningPreferences/impl": typeof learningPreferences_impl;
  "learningPreferences/mutations": typeof learningPreferences_mutations;
  "learningPreferences/queries": typeof learningPreferences_queries;
  "learningPrograms/catalog": typeof learningPrograms_catalog;
  "learningPrograms/impl": typeof learningPrograms_impl;
  "learningPrograms/mutations": typeof learningPrograms_mutations;
  "learningPrograms/omitted": typeof learningPrograms_omitted;
  "learningPrograms/queries": typeof learningPrograms_queries;
  "learningPrograms/sources": typeof learningPrograms_sources;
  "learningPrograms/sync": typeof learningPrograms_sync;
  "lib/attempts": typeof lib_attempts;
  "lib/effect": typeof lib_effect;
  "lib/helpers/auth": typeof lib_helpers_auth;
  "lib/helpers/chat": typeof lib_helpers_chat;
  "lib/helpers/class": typeof lib_helpers_class;
  "lib/helpers/invite": typeof lib_helpers_invite;
  "lib/helpers/permissions": typeof lib_helpers_permissions;
  "lib/helpers/school": typeof lib_helpers_school;
  "lib/helpers/user": typeof lib_helpers_user;
  "lib/images": typeof lib_images;
  "lib/validators/audio": typeof lib_validators_audio;
  "lib/validators/contents": typeof lib_validators_contents;
  "lib/validators/trending": typeof lib_validators_trending;
  "lib/validators/user": typeof lib_validators_user;
  "lib/validators/vv": typeof lib_validators_vv;
  "notifications/mutations": typeof notifications_mutations;
  "notifications/queries": typeof notifications_queries;
  polyfills: typeof polyfills;
  posthog: typeof posthog;
  "routes/constants": typeof routes_constants;
  "routes/middleware/requestId": typeof routes_middleware_requestId;
  "routes/polar": typeof routes_polar;
  "routes/v1/index": typeof routes_v1_index;
  "schools/mutations": typeof schools_mutations;
  "schools/queries": typeof schools_queries;
  "schools/utils": typeof schools_utils;
  "schools/validators": typeof schools_validators;
  "subscriptions/mutations": typeof subscriptions_mutations;
  "subscriptions/queries": typeof subscriptions_queries;
  "subscriptions/records/impl": typeof subscriptions_records_impl;
  "subscriptions/records/spec": typeof subscriptions_records_spec;
  "subscriptions/utils": typeof subscriptions_utils;
  "triggers/chats/chats": typeof triggers_chats_chats;
  "triggers/chats/cleanup": typeof triggers_chats_cleanup;
  "triggers/chats/messages": typeof triggers_chats_messages;
  "triggers/comments/cleanup": typeof triggers_comments_cleanup;
  "triggers/comments/commentVotes": typeof triggers_comments_commentVotes;
  "triggers/comments/comments": typeof triggers_comments_comments;
  "triggers/contents/popularity": typeof triggers_contents_popularity;
  "triggers/contents/views": typeof triggers_contents_views;
  "triggers/forums/postReactions": typeof triggers_forums_postReactions;
  "triggers/forums/posts": typeof triggers_forums_posts;
  "triggers/forums/reactions": typeof triggers_forums_reactions;
  "triggers/helpers/classes": typeof triggers_helpers_classes;
  "triggers/helpers/forumPosts": typeof triggers_helpers_forumPosts;
  "triggers/helpers/metadata": typeof triggers_helpers_metadata;
  "triggers/helpers/notifications": typeof triggers_helpers_notifications;
  "triggers/materials/cleanup": typeof triggers_materials_cleanup;
  "triggers/materials/groups": typeof triggers_materials_groups;
  "triggers/materials/materials": typeof triggers_materials_materials;
  "triggers/notifications/notifications": typeof triggers_notifications_notifications;
  "triggers/schools/classMembers": typeof triggers_schools_classMembers;
  "triggers/schools/classes": typeof triggers_schools_classes;
  "triggers/schools/cleanup": typeof triggers_schools_cleanup;
  "triggers/schools/members": typeof triggers_schools_members;
  "triggers/schools/schools": typeof triggers_schools_schools;
  "triggers/subscriptions/impl": typeof triggers_subscriptions_impl;
  "triggers/subscriptions/spec": typeof triggers_subscriptions_spec;
  "triggers/subscriptions/subscriptions": typeof triggers_subscriptions_subscriptions;
  "tryouts/mutations/attempts": typeof tryouts_mutations_attempts;
  "tryouts/mutations/expiry": typeof tryouts_mutations_expiry;
  "tryouts/mutations/sections": typeof tryouts_mutations_sections;
  "tryouts/queries/attempt": typeof tryouts_queries_attempt;
  "tryouts/queries/catalog": typeof tryouts_queries_catalog;
  "tryouts/queries/catalogModel": typeof tryouts_queries_catalogModel;
  "tryouts/queries/parents": typeof tryouts_queries_parents;
  "tryouts/queries/sets": typeof tryouts_queries_sets;
  "tryouts/questions": typeof tryouts_questions;
  "tryouts/read": typeof tryouts_read;
  "tryouts/runtime/access": typeof tryouts_runtime_access;
  "tryouts/runtime/finish": typeof tryouts_runtime_finish;
  "tryouts/runtime/irt": typeof tryouts_runtime_irt;
  "tryouts/runtime/placement": typeof tryouts_runtime_placement;
  "tryouts/runtime/result": typeof tryouts_runtime_result;
  "tryouts/runtime/score": typeof tryouts_runtime_score;
  "tryouts/runtime/sectionAttempt": typeof tryouts_runtime_sectionAttempt;
  "users/mutations": typeof users_mutations;
  "users/queries": typeof users_queries;
  "users/roles": typeof users_roles;
  "utils/error": typeof utils_error;
  "utils/id": typeof utils_id;
  "utils/logger": typeof utils_logger;
  "utils/number": typeof utils_number;
  "utils/polar/client": typeof utils_polar_client;
  "utils/polar/config": typeof utils_polar_config;
  "utils/polar/env": typeof utils_polar_env;
  "utils/polar/products": typeof utils_polar_products;
  "utils/polar/webhook": typeof utils_polar_webhook;
  "utils/site": typeof utils_site;
  "utils/text": typeof utils_text;
  "utils/type": typeof utils_type;
  workflow: typeof workflow;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("@repo/backend/convex/betterAuth/_generated/component.js").ComponentApi<"betterAuth">;
  workflow: import("@convex-dev/workflow/_generated/component.js").ComponentApi<"workflow">;
  irtCalibrationSyncWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"irtCalibrationSyncWorkpool">;
  irtScalePublicationQueueWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"irtScalePublicationQueueWorkpool">;
  tryoutLeaderboardWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"tryoutLeaderboardWorkpool">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
  posthog: import("@posthog/convex/_generated/component.js").ComponentApi<"posthog">;
  tryoutLeaderboard: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"tryoutLeaderboard">;
  globalLeaderboard: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"globalLeaderboard">;
  forumPostsBySequence: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"forumPostsBySequence">;
  forumPostsByAuthorSequence: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"forumPostsByAuthorSequence">;
  learningPopularityRankings: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"learningPopularityRankings">;
};
