/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as analytics_capture from "../analytics/capture.js";
import type * as analytics_erasure_action from "../analytics/erasure/action.js";
import type * as analytics_erasure_policy from "../analytics/erasure/policy.js";
import type * as analytics_erasure_request from "../analytics/erasure/request.js";
import type * as analytics_erasure_workflow from "../analytics/erasure/workflow.js";
import type * as analytics_events from "../analytics/events.js";
import type * as auth_actions from "../auth/actions.js";
import type * as auth_cleanup from "../auth/cleanup.js";
import type * as auth_cleanup_consents from "../auth/cleanup/consents.js";
import type * as auth_cleanup_impl from "../auth/cleanup/impl.js";
import type * as auth_cleanup_learning from "../auth/cleanup/learning.js";
import type * as auth_cleanup_notifications from "../auth/cleanup/notifications.js";
import type * as auth_cleanup_schoolCommunity from "../auth/cleanup/schoolCommunity.js";
import type * as auth_cleanup_schools from "../auth/cleanup/schools.js";
import type * as auth_cleanup_social from "../auth/cleanup/social.js";
import type * as auth_cleanup_spec from "../auth/cleanup/spec.js";
import type * as auth_cleanup_tryouts from "../auth/cleanup/tryouts.js";
import type * as auth_client from "../auth/client.js";
import type * as auth_deletion from "../auth/deletion.js";
import type * as auth_deletion_attemptCancellation from "../auth/deletion/attemptCancellation.js";
import type * as auth_deletion_cancel from "../auth/deletion/cancel.js";
import type * as auth_deletion_claim from "../auth/deletion/claim.js";
import type * as auth_deletion_commit from "../auth/deletion/commit.js";
import type * as auth_deletion_constants from "../auth/deletion/constants.js";
import type * as auth_deletion_finalize from "../auth/deletion/finalize.js";
import type * as auth_deletion_prepare from "../auth/deletion/prepare.js";
import type * as auth_deletion_receipt from "../auth/deletion/receipt.js";
import type * as auth_deletion_recovery from "../auth/deletion/recovery.js";
import type * as auth_deletion_spec from "../auth/deletion/spec.js";
import type * as auth_deletion_state from "../auth/deletion/state.js";
import type * as auth_deletion_successor from "../auth/deletion/successor.js";
import type * as auth_deletion_tombstone from "../auth/deletion/tombstone.js";
import type * as auth_deletion_verification from "../auth/deletion/verification.js";
import type * as auth_lifecycle from "../auth/lifecycle.js";
import type * as auth_queries from "../auth/queries.js";
import type * as auth_reader from "../auth/reader.js";
import type * as auth_runtime from "../auth/runtime.js";
import type * as auth_username_availability from "../auth/username/availability.js";
import type * as auth_username_plugin from "../auth/username/plugin.js";
import type * as auth_username_policy from "../auth/username/policy.js";
import type * as auth_username_request from "../auth/username/request.js";
import type * as chats_actions from "../chats/actions.js";
import type * as chats_assistantResponses from "../chats/assistantResponses.js";
import type * as chats_assistantResponses_impl from "../chats/assistantResponses/impl.js";
import type * as chats_constants from "../chats/constants.js";
import type * as chats_context from "../chats/context.js";
import type * as chats_helpers from "../chats/helpers.js";
import type * as chats_messageParts_dbToUi from "../chats/messageParts/dbToUi.js";
import type * as chats_messageParts_providerMetadata from "../chats/messageParts/providerMetadata.js";
import type * as chats_messageParts_shared from "../chats/messageParts/shared.js";
import type * as chats_messageParts_uiToDb from "../chats/messageParts/uiToDb.js";
import type * as chats_mutations from "../chats/mutations.js";
import type * as chats_nakafa from "../chats/nakafa.js";
import type * as chats_queries from "../chats/queries.js";
import type * as chats_read from "../chats/read.js";
import type * as chats_traces_impl from "../chats/traces/impl.js";
import type * as chats_traces_mutations from "../chats/traces/mutations.js";
import type * as chats_traces_queries from "../chats/traces/queries.js";
import type * as chats_traces_spec from "../chats/traces/spec.js";
import type * as chats_utils from "../chats/utils.js";
import type * as classes_constants from "../classes/constants.js";
import type * as classes_forums_aggregate from "../classes/forums/aggregate.js";
import type * as classes_forums_attachments_constants from "../classes/forums/attachments/constants.js";
import type * as classes_forums_attachments_impl from "../classes/forums/attachments/impl.js";
import type * as classes_forums_attachments_route from "../classes/forums/attachments/route.js";
import type * as classes_forums_attachments_spec from "../classes/forums/attachments/spec.js";
import type * as classes_forums_attachments_upload from "../classes/forums/attachments/upload.js";
import type * as classes_forums_cleanup from "../classes/forums/cleanup.js";
import type * as classes_forums_internalMutations from "../classes/forums/internalMutations.js";
import type * as classes_forums_mutations_forums from "../classes/forums/mutations/forums.js";
import type * as classes_forums_mutations_posts from "../classes/forums/mutations/posts.js";
import type * as classes_forums_mutations_reactions from "../classes/forums/mutations/reactions.js";
import type * as classes_forums_mutations_readState from "../classes/forums/mutations/readState.js";
import type * as classes_forums_mutations_uploads from "../classes/forums/mutations/uploads.js";
import type * as classes_forums_queries_forums from "../classes/forums/queries/forums.js";
import type * as classes_forums_queries_pages from "../classes/forums/queries/pages.js";
import type * as classes_forums_utils_access from "../classes/forums/utils/access.js";
import type * as classes_forums_utils_constants from "../classes/forums/utils/constants.js";
import type * as classes_forums_utils_mentions from "../classes/forums/utils/mentions.js";
import type * as classes_forums_utils_postReactions from "../classes/forums/utils/postReactions.js";
import type * as classes_forums_utils_posts from "../classes/forums/utils/posts.js";
import type * as classes_forums_utils_reactions from "../classes/forums/utils/reactions.js";
import type * as classes_forums_utils_readStateWrite from "../classes/forums/utils/readStateWrite.js";
import type * as classes_forums_utils_unreadCounts from "../classes/forums/utils/unreadCounts.js";
import type * as classes_forums_validators from "../classes/forums/validators.js";
import type * as classes_materials_mutations from "../classes/materials/mutations.js";
import type * as classes_materials_queries from "../classes/materials/queries.js";
import type * as classes_materials_utils from "../classes/materials/utils.js";
import type * as classes_mutations from "../classes/mutations.js";
import type * as classes_queries from "../classes/queries.js";
import type * as classes_utils from "../classes/utils.js";
import type * as classes_validators from "../classes/validators.js";
import type * as comments_mutations from "../comments/mutations.js";
import type * as comments_queries from "../comments/queries.js";
import type * as consents_current from "../consents/current.js";
import type * as consents_impl from "../consents/impl.js";
import type * as contentRelease_abort from "../contentRelease/abort.js";
import type * as contentRelease_abort_budget from "../contentRelease/abort/budget.js";
import type * as contentRelease_abort_rows from "../contentRelease/abort/rows.js";
import type * as contentRelease_abort_runtime from "../contentRelease/abort/runtime.js";
import type * as contentRelease_accept from "../contentRelease/accept.js";
import type * as contentRelease_activate from "../contentRelease/activate.js";
import type * as contentRelease_activation_candidate from "../contentRelease/activation/candidate.js";
import type * as contentRelease_activation_complete from "../contentRelease/activation/complete.js";
import type * as contentRelease_activation_model from "../contentRelease/activation/model.js";
import type * as contentRelease_activation_recovery from "../contentRelease/activation/recovery.js";
import type * as contentRelease_activation_spec from "../contentRelease/activation/spec.js";
import type * as contentRelease_activation_validate from "../contentRelease/activation/validate.js";
import type * as contentRelease_article from "../contentRelease/article.js";
import type * as contentRelease_article_agent from "../contentRelease/article/agent.js";
import type * as contentRelease_article_bucket from "../contentRelease/article/bucket.js";
import type * as contentRelease_article_cursor from "../contentRelease/article/cursor.js";
import type * as contentRelease_article_discovery from "../contentRelease/article/discovery.js";
import type * as contentRelease_article_internal from "../contentRelease/article/internal.js";
import type * as contentRelease_article_limits from "../contentRelease/article/limits.js";
import type * as contentRelease_article_model from "../contentRelease/article/model.js";
import type * as contentRelease_article_order from "../contentRelease/article/order.js";
import type * as contentRelease_article_owner from "../contentRelease/article/owner.js";
import type * as contentRelease_article_ownership from "../contentRelease/article/ownership.js";
import type * as contentRelease_article_partition from "../contentRelease/article/partition.js";
import type * as contentRelease_article_read from "../contentRelease/article/read.js";
import type * as contentRelease_article_route from "../contentRelease/article/route.js";
import type * as contentRelease_article_sitemap from "../contentRelease/article/sitemap.js";
import type * as contentRelease_article_spec from "../contentRelease/article/spec.js";
import type * as contentRelease_article_sync from "../contentRelease/article/sync.js";
import type * as contentRelease_article_validation from "../contentRelease/article/validation.js";
import type * as contentRelease_article_verify from "../contentRelease/article/verify.js";
import type * as contentRelease_article_write from "../contentRelease/article/write.js";
import type * as contentRelease_artifact_store from "../contentRelease/artifact/store.js";
import type * as contentRelease_artifacts from "../contentRelease/artifacts.js";
import type * as contentRelease_base from "../contentRelease/base.js";
import type * as contentRelease_batch from "../contentRelease/batch.js";
import type * as contentRelease_bucket from "../contentRelease/bucket.js";
import type * as contentRelease_catalog from "../contentRelease/catalog.js";
import type * as contentRelease_cleanup from "../contentRelease/cleanup.js";
import type * as contentRelease_compact from "../contentRelease/compact.js";
import type * as contentRelease_compact_artifacts from "../contentRelease/compact/artifacts.js";
import type * as contentRelease_compact_rows from "../contentRelease/compact/rows.js";
import type * as contentRelease_compact_runtime from "../contentRelease/compact/runtime.js";
import type * as contentRelease_compact_state from "../contentRelease/compact/state.js";
import type * as contentRelease_cursor from "../contentRelease/cursor.js";
import type * as contentRelease_digest from "../contentRelease/digest.js";
import type * as contentRelease_document from "../contentRelease/document.js";
import type * as contentRelease_envelope from "../contentRelease/envelope.js";
import type * as contentRelease_error from "../contentRelease/error.js";
import type * as contentRelease_heads from "../contentRelease/heads.js";
import type * as contentRelease_http_body from "../contentRelease/http/body.js";
import type * as contentRelease_http_runtime_batch from "../contentRelease/http/runtime/batch.js";
import type * as contentRelease_http_runtime_protected from "../contentRelease/http/runtime/protected.js";
import type * as contentRelease_http_runtime_public from "../contentRelease/http/runtime/public.js";
import type * as contentRelease_http_runtime_request from "../contentRelease/http/runtime/request.js";
import type * as contentRelease_http_runtime_response from "../contentRelease/http/runtime/response.js";
import type * as contentRelease_http_secret from "../contentRelease/http/secret.js";
import type * as contentRelease_ingress_call from "../contentRelease/ingress/call.js";
import type * as contentRelease_ingress_current from "../contentRelease/ingress/current.js";
import type * as contentRelease_ingress_decode from "../contentRelease/ingress/decode.js";
import type * as contentRelease_ingress_dispatch from "../contentRelease/ingress/dispatch.js";
import type * as contentRelease_ingress_envelope from "../contentRelease/ingress/envelope.js";
import type * as contentRelease_ingress_failure from "../contentRelease/ingress/failure.js";
import type * as contentRelease_ingress_group from "../contentRelease/ingress/group.js";
import type * as contentRelease_ingress_key from "../contentRelease/ingress/key.js";
import type * as contentRelease_ingress_lifecycle from "../contentRelease/ingress/lifecycle.js";
import type * as contentRelease_ingress_models from "../contentRelease/ingress/models.js";
import type * as contentRelease_ingress_read from "../contentRelease/ingress/read.js";
import type * as contentRelease_ingress_response from "../contentRelease/ingress/response.js";
import type * as contentRelease_ingress_rollback from "../contentRelease/ingress/rollback.js";
import type * as contentRelease_ingress_route from "../contentRelease/ingress/route.js";
import type * as contentRelease_ingress_runtime_bundle from "../contentRelease/ingress/runtime/bundle.js";
import type * as contentRelease_ingress_snapshot from "../contentRelease/ingress/snapshot.js";
import type * as contentRelease_ingress_stage from "../contentRelease/ingress/stage.js";
import type * as contentRelease_item from "../contentRelease/item.js";
import type * as contentRelease_items from "../contentRelease/items.js";
import type * as contentRelease_manifest from "../contentRelease/manifest.js";
import type * as contentRelease_material from "../contentRelease/material.js";
import type * as contentRelease_material_bucket from "../contentRelease/material/bucket.js";
import type * as contentRelease_material_discovery from "../contentRelease/material/discovery.js";
import type * as contentRelease_material_identity from "../contentRelease/material/identity.js";
import type * as contentRelease_material_limits from "../contentRelease/material/limits.js";
import type * as contentRelease_material_model from "../contentRelease/material/model.js";
import type * as contentRelease_material_owner from "../contentRelease/material/owner.js";
import type * as contentRelease_material_page from "../contentRelease/material/page.js";
import type * as contentRelease_material_partition from "../contentRelease/material/partition.js";
import type * as contentRelease_material_route from "../contentRelease/material/route.js";
import type * as contentRelease_material_sitemap from "../contentRelease/material/sitemap.js";
import type * as contentRelease_material_spec from "../contentRelease/material/spec.js";
import type * as contentRelease_material_state from "../contentRelease/material/state.js";
import type * as contentRelease_material_sync from "../contentRelease/material/sync.js";
import type * as contentRelease_material_topic from "../contentRelease/material/topic.js";
import type * as contentRelease_material_validation from "../contentRelease/material/validation.js";
import type * as contentRelease_material_verify from "../contentRelease/material/verify.js";
import type * as contentRelease_material_write from "../contentRelease/material/write.js";
import type * as contentRelease_model from "../contentRelease/model.js";
import type * as contentRelease_models from "../contentRelease/models.js";
import type * as contentRelease_models_article from "../contentRelease/models/article.js";
import type * as contentRelease_models_build from "../contentRelease/models/build.js";
import type * as contentRelease_models_impact from "../contentRelease/models/impact.js";
import type * as contentRelease_models_items from "../contentRelease/models/items.js";
import type * as contentRelease_models_material from "../contentRelease/models/material.js";
import type * as contentRelease_models_page from "../contentRelease/models/page.js";
import type * as contentRelease_models_phase from "../contentRelease/models/phase.js";
import type * as contentRelease_models_search from "../contentRelease/models/search.js";
import type * as contentRelease_models_slot from "../contentRelease/models/slot.js";
import type * as contentRelease_models_spec from "../contentRelease/models/spec.js";
import type * as contentRelease_ownership from "../contentRelease/ownership.js";
import type * as contentRelease_page from "../contentRelease/page.js";
import type * as contentRelease_page_catalog from "../contentRelease/page/catalog.js";
import type * as contentRelease_page_limits from "../contentRelease/page/limits.js";
import type * as contentRelease_paging from "../contentRelease/paging.js";
import type * as contentRelease_parse from "../contentRelease/parse.js";
import type * as contentRelease_partner_cursor from "../contentRelease/partner/cursor.js";
import type * as contentRelease_partner_page from "../contentRelease/partner/page.js";
import type * as contentRelease_program from "../contentRelease/program.js";
import type * as contentRelease_program_bucket from "../contentRelease/program/bucket.js";
import type * as contentRelease_program_catalog from "../contentRelease/program/catalog.js";
import type * as contentRelease_program_context from "../contentRelease/program/context.js";
import type * as contentRelease_program_limits from "../contentRelease/program/limits.js";
import type * as contentRelease_program_model from "../contentRelease/program/model.js";
import type * as contentRelease_program_owner from "../contentRelease/program/owner.js";
import type * as contentRelease_program_page from "../contentRelease/program/page.js";
import type * as contentRelease_program_partition from "../contentRelease/program/partition.js";
import type * as contentRelease_program_path from "../contentRelease/program/path.js";
import type * as contentRelease_program_route from "../contentRelease/program/route.js";
import type * as contentRelease_program_sitemap from "../contentRelease/program/sitemap.js";
import type * as contentRelease_program_verify from "../contentRelease/program/verify.js";
import type * as contentRelease_projection from "../contentRelease/projection.js";
import type * as contentRelease_proof_artifact from "../contentRelease/proof/artifact.js";
import type * as contentRelease_proof_budget from "../contentRelease/proof/budget.js";
import type * as contentRelease_proof_catalog from "../contentRelease/proof/catalog.js";
import type * as contentRelease_proof_commit from "../contentRelease/proof/commit.js";
import type * as contentRelease_proof_content from "../contentRelease/proof/content.js";
import type * as contentRelease_proof_coordinator from "../contentRelease/proof/coordinator.js";
import type * as contentRelease_proof_failure from "../contentRelease/proof/failure.js";
import type * as contentRelease_proof_poll from "../contentRelease/proof/poll.js";
import type * as contentRelease_proof_read from "../contentRelease/proof/read.js";
import type * as contentRelease_proof_routes from "../contentRelease/proof/routes.js";
import type * as contentRelease_proof_snapshot from "../contentRelease/proof/snapshot.js";
import type * as contentRelease_proof_spec from "../contentRelease/proof/spec.js";
import type * as contentRelease_proof_stream from "../contentRelease/proof/stream.js";
import type * as contentRelease_proof_verify from "../contentRelease/proof/verify.js";
import type * as contentRelease_proof_workflow from "../contentRelease/proof/workflow.js";
import type * as contentRelease_quran from "../contentRelease/quran.js";
import type * as contentRelease_quran_attribution from "../contentRelease/quran/attribution.js";
import type * as contentRelease_quran_bismillah from "../contentRelease/quran/bismillah.js";
import type * as contentRelease_quran_catalog from "../contentRelease/quran/catalog.js";
import type * as contentRelease_quran_chunks from "../contentRelease/quran/chunks.js";
import type * as contentRelease_quran_document from "../contentRelease/quran/document.js";
import type * as contentRelease_quran_facts from "../contentRelease/quran/facts.js";
import type * as contentRelease_quran_input from "../contentRelease/quran/input.js";
import type * as contentRelease_quran_interpretation from "../contentRelease/quran/interpretation.js";
import type * as contentRelease_quran_limits from "../contentRelease/quran/limits.js";
import type * as contentRelease_quran_markdown from "../contentRelease/quran/markdown.js";
import type * as contentRelease_quran_owner from "../contentRelease/quran/owner.js";
import type * as contentRelease_quran_reference from "../contentRelease/quran/reference.js";
import type * as contentRelease_quran_row from "../contentRelease/quran/row.js";
import type * as contentRelease_quran_sources from "../contentRelease/quran/sources.js";
import type * as contentRelease_quran_spec from "../contentRelease/quran/spec.js";
import type * as contentRelease_quran_surah from "../contentRelease/quran/surah.js";
import type * as contentRelease_quran_translation from "../contentRelease/quran/translation.js";
import type * as contentRelease_quran_verify from "../contentRelease/quran/verify.js";
import type * as contentRelease_quran_view from "../contentRelease/quran/view.js";
import type * as contentRelease_receipt from "../contentRelease/receipt.js";
import type * as contentRelease_recovery from "../contentRelease/recovery.js";
import type * as contentRelease_reference from "../contentRelease/reference.js";
import type * as contentRelease_reference_agent from "../contentRelease/reference/agent.js";
import type * as contentRelease_reference_input from "../contentRelease/reference/input.js";
import type * as contentRelease_reference_internal from "../contentRelease/reference/internal.js";
import type * as contentRelease_reference_read from "../contentRelease/reference/read.js";
import type * as contentRelease_reference_spec from "../contentRelease/reference/spec.js";
import type * as contentRelease_renderer from "../contentRelease/renderer.js";
import type * as contentRelease_retention from "../contentRelease/retention.js";
import type * as contentRelease_rollback from "../contentRelease/rollback.js";
import type * as contentRelease_rollback_state from "../contentRelease/rollback/state.js";
import type * as contentRelease_rollback_stored from "../contentRelease/rollback/stored.js";
import type * as contentRelease_route from "../contentRelease/route.js";
import type * as contentRelease_routes from "../contentRelease/routes.js";
import type * as contentRelease_runtime_active from "../contentRelease/runtime/active.js";
import type * as contentRelease_runtime_origin from "../contentRelease/runtime/origin.js";
import type * as contentRelease_runtime_pin from "../contentRelease/runtime/pin.js";
import type * as contentRelease_runtime_protected_dispatch from "../contentRelease/runtime/protected/dispatch.js";
import type * as contentRelease_runtime_protected_internal from "../contentRelease/runtime/protected/internal.js";
import type * as contentRelease_runtime_public_batch from "../contentRelease/runtime/public/batch.js";
import type * as contentRelease_runtime_public_dispatch from "../contentRelease/runtime/public/dispatch.js";
import type * as contentRelease_runtime_public_internal from "../contentRelease/runtime/public/internal.js";
import type * as contentRelease_runtime_result from "../contentRelease/runtime/result.js";
import type * as contentRelease_runtime_snapshot from "../contentRelease/runtime/snapshot.js";
import type * as contentRelease_scope_family from "../contentRelease/scope/family.js";
import type * as contentRelease_scope_route from "../contentRelease/scope/route.js";
import type * as contentRelease_search_input from "../contentRelease/search/input.js";
import type * as contentRelease_search_owner from "../contentRelease/search/owner.js";
import type * as contentRelease_search_spec from "../contentRelease/search/spec.js";
import type * as contentRelease_search_sync from "../contentRelease/search/sync.js";
import type * as contentRelease_search_validation from "../contentRelease/search/validation.js";
import type * as contentRelease_search_verify from "../contentRelease/search/verify.js";
import type * as contentRelease_search_write from "../contentRelease/search/write.js";
import type * as contentRelease_sitemap from "../contentRelease/sitemap.js";
import type * as contentRelease_snapshot from "../contentRelease/snapshot.js";
import type * as contentRelease_snapshot_batch from "../contentRelease/snapshot/batch.js";
import type * as contentRelease_snapshot_cleanup from "../contentRelease/snapshot/cleanup.js";
import type * as contentRelease_snapshot_manifest from "../contentRelease/snapshot/manifest.js";
import type * as contentRelease_snapshot_program from "../contentRelease/snapshot/program.js";
import type * as contentRelease_snapshot_quran from "../contentRelease/snapshot/quran.js";
import type * as contentRelease_snapshot_read from "../contentRelease/snapshot/read.js";
import type * as contentRelease_snapshot_request from "../contentRelease/snapshot/request.js";
import type * as contentRelease_snapshot_retention from "../contentRelease/snapshot/retention.js";
import type * as contentRelease_snapshot_rows from "../contentRelease/snapshot/rows.js";
import type * as contentRelease_snapshot_tryout from "../contentRelease/snapshot/tryout.js";
import type * as contentRelease_spec from "../contentRelease/spec.js";
import type * as contentRelease_status from "../contentRelease/status.js";
import type * as contentRelease_sync from "../contentRelease/sync.js";
import type * as contentRelease_tryout from "../contentRelease/tryout.js";
import type * as contentRelease_tryout_binding from "../contentRelease/tryout/binding.js";
import type * as contentRelease_tryout_catalog from "../contentRelease/tryout/catalog.js";
import type * as contentRelease_tryout_facts from "../contentRelease/tryout/facts.js";
import type * as contentRelease_tryout_limits from "../contentRelease/tryout/limits.js";
import type * as contentRelease_tryout_owner from "../contentRelease/tryout/owner.js";
import type * as contentRelease_tryout_runtime from "../contentRelease/tryout/runtime.js";
import type * as contentRelease_tryout_section from "../contentRelease/tryout/section.js";
import type * as contentRelease_tryout_set from "../contentRelease/tryout/set.js";
import type * as contentRelease_tryout_sitemap from "../contentRelease/tryout/sitemap.js";
import type * as contentRelease_tryout_taxonomy from "../contentRelease/tryout/taxonomy.js";
import type * as contentRelease_tryout_verify from "../contentRelease/tryout/verify.js";
import type * as contentRelease_verify from "../contentRelease/verify.js";
import type * as contentRelease_verify_delete from "../contentRelease/verify/delete.js";
import type * as contentRelease_verify_item from "../contentRelease/verify/item.js";
import type * as contentRelease_verify_upsert from "../contentRelease/verify/upsert.js";
import type * as contentRelease_wire from "../contentRelease/wire.js";
import type * as contents_analytics_impl from "../contents/analytics/impl.js";
import type * as contents_analytics_spec from "../contents/analytics/spec.js";
import type * as contents_constants from "../contents/constants.js";
import type * as contents_context from "../contents/context.js";
import type * as contents_graph from "../contents/graph.js";
import type * as contents_helpers_partitions from "../contents/helpers/partitions.js";
import type * as contents_helpers_search_documents from "../contents/helpers/search/documents.js";
import type * as contents_helpers_search_excerpt from "../contents/helpers/search/excerpt.js";
import type * as contents_helpers_search_groups from "../contents/helpers/search/groups.js";
import type * as contents_helpers_search_input from "../contents/helpers/search/input.js";
import type * as contents_helpers_search_published from "../contents/helpers/search/published.js";
import type * as contents_helpers_search_quran_authenticate from "../contents/helpers/search/quran/authenticate.js";
import type * as contents_helpers_search_quran_candidates from "../contents/helpers/search/quran/candidates.js";
import type * as contents_helpers_search_quran_read from "../contents/helpers/search/quran/read.js";
import type * as contents_helpers_search_rank from "../contents/helpers/search/rank.js";
import type * as contents_helpers_search_read from "../contents/helpers/search/read.js";
import type * as contents_helpers_search_result from "../contents/helpers/search/result.js";
import type * as contents_helpers_search_terms from "../contents/helpers/search/terms.js";
import type * as contents_helpers_search_tryout from "../contents/helpers/search/tryout.js";
import type * as contents_metrics_apply from "../contents/metrics/apply.js";
import type * as contents_metrics_batch from "../contents/metrics/batch.js";
import type * as contents_metrics_refresh from "../contents/metrics/refresh.js";
import type * as contents_mutations_analytics from "../contents/mutations/analytics.js";
import type * as contents_mutations_popularity from "../contents/mutations/popularity.js";
import type * as contents_mutations_views from "../contents/mutations/views.js";
import type * as contents_popularity from "../contents/popularity.js";
import type * as contents_queries_recent from "../contents/queries/recent.js";
import type * as contents_queries_search from "../contents/queries/search.js";
import type * as contents_queries_trending from "../contents/queries/trending.js";
import type * as contents_rankings from "../contents/rankings.js";
import type * as contents_trending_impl from "../contents/trending/impl.js";
import type * as contents_trending_spec from "../contents/trending/spec.js";
import type * as contents_views_context from "../contents/views/context.js";
import type * as contents_views_impl from "../contents/views/impl.js";
import type * as contents_views_recent from "../contents/views/recent.js";
import type * as contents_views_signals from "../contents/views/signals.js";
import type * as contents_views_spec from "../contents/views/spec.js";
import type * as contents_views_target from "../contents/views/target.js";
import type * as credits_constants from "../credits/constants.js";
import type * as credits_helpers_state from "../credits/helpers/state.js";
import type * as credits_mutations from "../credits/mutations.js";
import type * as crons from "../crons.js";
import type * as customers_actions_internal from "../customers/actions/internal.js";
import type * as customers_actions_public from "../customers/actions/public.js";
import type * as customers_checkout_admission from "../customers/checkout/admission.js";
import type * as customers_checkout_impl from "../customers/checkout/impl.js";
import type * as customers_checkout_localization from "../customers/checkout/localization.js";
import type * as customers_checkout_session from "../customers/checkout/session.js";
import type * as customers_checkout_spec from "../customers/checkout/spec.js";
import type * as customers_deletion_billing from "../customers/deletion/billing.js";
import type * as customers_deletion_billingState from "../customers/deletion/billingState.js";
import type * as customers_deletion_cleanup from "../customers/deletion/cleanup.js";
import type * as customers_deletion_workflow from "../customers/deletion/workflow.js";
import type * as customers_integrity_internal from "../customers/integrity/internal.js";
import type * as customers_mutations_internal from "../customers/mutations/internal.js";
import type * as customers_mutations_spec from "../customers/mutations/spec.js";
import type * as customers_polar_impl from "../customers/polar/impl.js";
import type * as customers_polar_live from "../customers/polar/live.js";
import type * as customers_polar_spec from "../customers/polar/spec.js";
import type * as customers_polar_target from "../customers/polar/target.js";
import type * as customers_polar_webhook from "../customers/polar/webhook.js";
import type * as customers_queries_internal_customer from "../customers/queries/internal/customer.js";
import type * as customers_records from "../customers/records.js";
import type * as customers_sync_impl from "../customers/sync/impl.js";
import type * as customers_sync_settlement from "../customers/sync/settlement.js";
import type * as customers_sync_spec from "../customers/sync/spec.js";
import type * as emails_client from "../emails/client.js";
import type * as emails_deletion from "../emails/deletion.js";
import type * as emails_delivery from "../emails/delivery.js";
import type * as emails_retention from "../emails/retention.js";
import type * as emails_welcome from "../emails/welcome.js";
import type * as functions from "../functions.js";
import type * as http from "../http.js";
import type * as learningPreferences_impl from "../learningPreferences/impl.js";
import type * as learningPreferences_mutations from "../learningPreferences/mutations.js";
import type * as learningPreferences_program from "../learningPreferences/program.js";
import type * as learningPreferences_queries from "../learningPreferences/queries.js";
import type * as lib_attempts from "../lib/attempts.js";
import type * as lib_effect from "../lib/effect.js";
import type * as lib_helpers_auth from "../lib/helpers/auth.js";
import type * as lib_helpers_chat from "../lib/helpers/chat.js";
import type * as lib_helpers_class from "../lib/helpers/class.js";
import type * as lib_helpers_invite from "../lib/helpers/invite.js";
import type * as lib_helpers_permissions from "../lib/helpers/permissions.js";
import type * as lib_helpers_school from "../lib/helpers/school.js";
import type * as lib_helpers_user from "../lib/helpers/user.js";
import type * as lib_images from "../lib/images.js";
import type * as lib_validators_contents from "../lib/validators/contents.js";
import type * as lib_validators_trending from "../lib/validators/trending.js";
import type * as lib_validators_user from "../lib/validators/user.js";
import type * as lib_validators_vv from "../lib/validators/vv.js";
import type * as notifications_mutations from "../notifications/mutations.js";
import type * as notifications_queries from "../notifications/queries.js";
import type * as onboarding_impl from "../onboarding/impl.js";
import type * as onboarding_mutations from "../onboarding/mutations.js";
import type * as onboarding_queries from "../onboarding/queries.js";
import type * as onboarding_spec from "../onboarding/spec.js";
import type * as onboarding_values from "../onboarding/values.js";
import type * as polyfills from "../polyfills.js";
import type * as privacy_recovery from "../privacy/recovery.js";
import type * as privacy_spec from "../privacy/spec.js";
import type * as routes_agent_api from "../routes/agent/api.js";
import type * as routes_agent_content from "../routes/agent/content.js";
import type * as routes_agent_guard from "../routes/agent/guard.js";
import type * as routes_agent_input from "../routes/agent/input.js";
import type * as routes_agent_limit from "../routes/agent/limit.js";
import type * as routes_agent_mcp_guard from "../routes/agent/mcp/guard.js";
import type * as routes_agent_mcp_input from "../routes/agent/mcp/input.js";
import type * as routes_agent_mcp_response from "../routes/agent/mcp/response.js";
import type * as routes_agent_mcp_route from "../routes/agent/mcp/route.js";
import type * as routes_agent_quran from "../routes/agent/quran.js";
import type * as routes_agent_response from "../routes/agent/response.js";
import type * as routes_agent_runtime from "../routes/agent/runtime.js";
import type * as routes_agent_search from "../routes/agent/search.js";
import type * as routes_agent_security from "../routes/agent/security.js";
import type * as routes_constants from "../routes/constants.js";
import type * as routes_middleware_requestId from "../routes/middleware/requestId.js";
import type * as routes_polar from "../routes/polar.js";
import type * as schools_mutations from "../schools/mutations.js";
import type * as schools_queries from "../schools/queries.js";
import type * as schools_slug from "../schools/slug.js";
import type * as schools_utils from "../schools/utils.js";
import type * as schools_validators from "../schools/validators.js";
import type * as subscriptions_mutations from "../subscriptions/mutations.js";
import type * as subscriptions_queries from "../subscriptions/queries.js";
import type * as subscriptions_records_impl from "../subscriptions/records/impl.js";
import type * as subscriptions_records_spec from "../subscriptions/records/spec.js";
import type * as subscriptions_utils from "../subscriptions/utils.js";
import type * as triggers_chats_chats from "../triggers/chats/chats.js";
import type * as triggers_chats_cleanup from "../triggers/chats/cleanup.js";
import type * as triggers_chats_messages from "../triggers/chats/messages.js";
import type * as triggers_comments_cleanup from "../triggers/comments/cleanup.js";
import type * as triggers_comments_commentVotes from "../triggers/comments/commentVotes.js";
import type * as triggers_comments_comments from "../triggers/comments/comments.js";
import type * as triggers_contents_popularity from "../triggers/contents/popularity.js";
import type * as triggers_contents_views from "../triggers/contents/views.js";
import type * as triggers_forums_postReactions from "../triggers/forums/postReactions.js";
import type * as triggers_forums_posts from "../triggers/forums/posts.js";
import type * as triggers_forums_reactions from "../triggers/forums/reactions.js";
import type * as triggers_helpers_classes from "../triggers/helpers/classes.js";
import type * as triggers_helpers_forumPosts from "../triggers/helpers/forumPosts.js";
import type * as triggers_helpers_metadata from "../triggers/helpers/metadata.js";
import type * as triggers_helpers_notifications from "../triggers/helpers/notifications.js";
import type * as triggers_materials_cleanup from "../triggers/materials/cleanup.js";
import type * as triggers_materials_groups from "../triggers/materials/groups.js";
import type * as triggers_materials_materials from "../triggers/materials/materials.js";
import type * as triggers_notifications_notifications from "../triggers/notifications/notifications.js";
import type * as triggers_schools_classMembers from "../triggers/schools/classMembers.js";
import type * as triggers_schools_classes from "../triggers/schools/classes.js";
import type * as triggers_schools_cleanup from "../triggers/schools/cleanup.js";
import type * as triggers_schools_members from "../triggers/schools/members.js";
import type * as triggers_schools_schools from "../triggers/schools/schools.js";
import type * as triggers_subscriptions_impl from "../triggers/subscriptions/impl.js";
import type * as triggers_subscriptions_spec from "../triggers/subscriptions/spec.js";
import type * as triggers_subscriptions_subscriptions from "../triggers/subscriptions/subscriptions.js";
import type * as triggers_tryouts_scores from "../triggers/tryouts/scores.js";
import type * as tryouts_access_impl from "../tryouts/access/impl.js";
import type * as tryouts_access_source from "../tryouts/access/source.js";
import type * as tryouts_access_subscription from "../tryouts/access/subscription.js";
import type * as tryouts_attemptPage_impl from "../tryouts/attemptPage/impl.js";
import type * as tryouts_attemptPage_spec from "../tryouts/attemptPage/spec.js";
import type * as tryouts_catalog_destination from "../tryouts/catalog/destination.js";
import type * as tryouts_catalog_featured from "../tryouts/catalog/featured.js";
import type * as tryouts_catalog_hierarchy from "../tryouts/catalog/hierarchy.js";
import type * as tryouts_catalog_metadata from "../tryouts/catalog/metadata.js";
import type * as tryouts_catalog_published from "../tryouts/catalog/published.js";
import type * as tryouts_catalog_row from "../tryouts/catalog/row.js";
import type * as tryouts_catalog_selection from "../tryouts/catalog/selection.js";
import type * as tryouts_catalog_spec from "../tryouts/catalog/spec.js";
import type * as tryouts_mutations_access from "../tryouts/mutations/access.js";
import type * as tryouts_mutations_attempts from "../tryouts/mutations/attempts.js";
import type * as tryouts_mutations_expiry from "../tryouts/mutations/expiry.js";
import type * as tryouts_mutations_responses from "../tryouts/mutations/responses.js";
import type * as tryouts_mutations_sections from "../tryouts/mutations/sections.js";
import type * as tryouts_progress_size from "../tryouts/progress/size.js";
import type * as tryouts_progress_write from "../tryouts/progress/write.js";
import type * as tryouts_queries_access from "../tryouts/queries/access.js";
import type * as tryouts_queries_attempt from "../tryouts/queries/attempt.js";
import type * as tryouts_queries_attemptPage from "../tryouts/queries/attemptPage.js";
import type * as tryouts_queries_catalog from "../tryouts/queries/catalog.js";
import type * as tryouts_queries_catalogModel from "../tryouts/queries/catalogModel.js";
import type * as tryouts_queries_history from "../tryouts/queries/history.js";
import type * as tryouts_queries_runtime from "../tryouts/queries/runtime.js";
import type * as tryouts_queries_sets from "../tryouts/queries/sets.js";
import type * as tryouts_questions from "../tryouts/questions.js";
import type * as tryouts_response_contract from "../tryouts/response/contract.js";
import type * as tryouts_response_evaluation from "../tryouts/response/evaluation.js";
import type * as tryouts_response_integrity from "../tryouts/response/integrity.js";
import type * as tryouts_response_legacy from "../tryouts/response/legacy.js";
import type * as tryouts_response_migrate from "../tryouts/response/migrate.js";
import type * as tryouts_response_model from "../tryouts/response/model.js";
import type * as tryouts_response_spec from "../tryouts/response/spec.js";
import type * as tryouts_response_validation from "../tryouts/response/validation.js";
import type * as tryouts_response_write from "../tryouts/response/write.js";
import type * as tryouts_route from "../tryouts/route.js";
import type * as tryouts_runtime_access from "../tryouts/runtime/access.js";
import type * as tryouts_runtime_attempt_page from "../tryouts/runtime/attempt/page.js";
import type * as tryouts_runtime_attempt_sections from "../tryouts/runtime/attempt/sections.js";
import type * as tryouts_runtime_attempt_source from "../tryouts/runtime/attempt/source.js";
import type * as tryouts_runtime_attempt_state from "../tryouts/runtime/attempt/state.js";
import type * as tryouts_runtime_choice from "../tryouts/runtime/choice.js";
import type * as tryouts_runtime_completion from "../tryouts/runtime/completion.js";
import type * as tryouts_runtime_content from "../tryouts/runtime/content.js";
import type * as tryouts_runtime_error from "../tryouts/runtime/error.js";
import type * as tryouts_runtime_estimate from "../tryouts/runtime/estimate.js";
import type * as tryouts_runtime_finish from "../tryouts/runtime/finish.js";
import type * as tryouts_runtime_irt from "../tryouts/runtime/irt.js";
import type * as tryouts_runtime_irt_items from "../tryouts/runtime/irt/items.js";
import type * as tryouts_runtime_irt_score from "../tryouts/runtime/irt/score.js";
import type * as tryouts_runtime_lookup from "../tryouts/runtime/lookup.js";
import type * as tryouts_runtime_ownership from "../tryouts/runtime/ownership.js";
import type * as tryouts_runtime_placement from "../tryouts/runtime/placement.js";
import type * as tryouts_runtime_response from "../tryouts/runtime/response.js";
import type * as tryouts_runtime_result from "../tryouts/runtime/result.js";
import type * as tryouts_runtime_scale from "../tryouts/runtime/scale.js";
import type * as tryouts_runtime_score from "../tryouts/runtime/score.js";
import type * as tryouts_runtime_section_questions from "../tryouts/runtime/section/questions.js";
import type * as tryouts_runtime_section_state from "../tryouts/runtime/section/state.js";
import type * as tryouts_runtime_sectionAttempt from "../tryouts/runtime/sectionAttempt.js";
import type * as tryouts_runtime_selectors from "../tryouts/runtime/selectors.js";
import type * as tryouts_runtime_set_state from "../tryouts/runtime/set/state.js";
import type * as tryouts_runtime_signed from "../tryouts/runtime/signed.js";
import type * as tryouts_runtime_spec from "../tryouts/runtime/spec.js";
import type * as tryouts_score from "../tryouts/score.js";
import type * as tryouts_score_result from "../tryouts/score/result.js";
import type * as tryouts_sets_page from "../tryouts/sets/page.js";
import type * as tryouts_sets_published from "../tryouts/sets/published.js";
import type * as tryouts_sets_spec from "../tryouts/sets/spec.js";
import type * as tryouts_start_attempt from "../tryouts/start/attempt.js";
import type * as tryouts_start_impl from "../tryouts/start/impl.js";
import type * as tryouts_start_scale from "../tryouts/start/scale.js";
import type * as tryouts_start_source from "../tryouts/start/source.js";
import type * as tryouts_start_spec from "../tryouts/start/spec.js";
import type * as tryouts_status from "../tryouts/status.js";
import type * as users_mutations from "../users/mutations.js";
import type * as users_queries from "../users/queries.js";
import type * as users_roles from "../users/roles.js";
import type * as utils_error from "../utils/error.js";
import type * as utils_id from "../utils/id.js";
import type * as utils_logger from "../utils/logger.js";
import type * as utils_number from "../utils/number.js";
import type * as utils_polar_client from "../utils/polar/client.js";
import type * as utils_polar_config from "../utils/polar/config.js";
import type * as utils_polar_env from "../utils/polar/env.js";
import type * as utils_polar_products from "../utils/polar/products.js";
import type * as utils_polar_webhook from "../utils/polar/webhook.js";
import type * as utils_site from "../utils/site.js";
import type * as utils_text from "../utils/text.js";
import type * as workflow from "../workflow.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "analytics/capture": typeof analytics_capture;
  "analytics/erasure/action": typeof analytics_erasure_action;
  "analytics/erasure/policy": typeof analytics_erasure_policy;
  "analytics/erasure/request": typeof analytics_erasure_request;
  "analytics/erasure/workflow": typeof analytics_erasure_workflow;
  "analytics/events": typeof analytics_events;
  "auth/actions": typeof auth_actions;
  "auth/cleanup": typeof auth_cleanup;
  "auth/cleanup/consents": typeof auth_cleanup_consents;
  "auth/cleanup/impl": typeof auth_cleanup_impl;
  "auth/cleanup/learning": typeof auth_cleanup_learning;
  "auth/cleanup/notifications": typeof auth_cleanup_notifications;
  "auth/cleanup/schoolCommunity": typeof auth_cleanup_schoolCommunity;
  "auth/cleanup/schools": typeof auth_cleanup_schools;
  "auth/cleanup/social": typeof auth_cleanup_social;
  "auth/cleanup/spec": typeof auth_cleanup_spec;
  "auth/cleanup/tryouts": typeof auth_cleanup_tryouts;
  "auth/client": typeof auth_client;
  "auth/deletion": typeof auth_deletion;
  "auth/deletion/attemptCancellation": typeof auth_deletion_attemptCancellation;
  "auth/deletion/cancel": typeof auth_deletion_cancel;
  "auth/deletion/claim": typeof auth_deletion_claim;
  "auth/deletion/commit": typeof auth_deletion_commit;
  "auth/deletion/constants": typeof auth_deletion_constants;
  "auth/deletion/finalize": typeof auth_deletion_finalize;
  "auth/deletion/prepare": typeof auth_deletion_prepare;
  "auth/deletion/receipt": typeof auth_deletion_receipt;
  "auth/deletion/recovery": typeof auth_deletion_recovery;
  "auth/deletion/spec": typeof auth_deletion_spec;
  "auth/deletion/state": typeof auth_deletion_state;
  "auth/deletion/successor": typeof auth_deletion_successor;
  "auth/deletion/tombstone": typeof auth_deletion_tombstone;
  "auth/deletion/verification": typeof auth_deletion_verification;
  "auth/lifecycle": typeof auth_lifecycle;
  "auth/queries": typeof auth_queries;
  "auth/reader": typeof auth_reader;
  "auth/runtime": typeof auth_runtime;
  "auth/username/availability": typeof auth_username_availability;
  "auth/username/plugin": typeof auth_username_plugin;
  "auth/username/policy": typeof auth_username_policy;
  "auth/username/request": typeof auth_username_request;
  "chats/actions": typeof chats_actions;
  "chats/assistantResponses": typeof chats_assistantResponses;
  "chats/assistantResponses/impl": typeof chats_assistantResponses_impl;
  "chats/constants": typeof chats_constants;
  "chats/context": typeof chats_context;
  "chats/helpers": typeof chats_helpers;
  "chats/messageParts/dbToUi": typeof chats_messageParts_dbToUi;
  "chats/messageParts/providerMetadata": typeof chats_messageParts_providerMetadata;
  "chats/messageParts/shared": typeof chats_messageParts_shared;
  "chats/messageParts/uiToDb": typeof chats_messageParts_uiToDb;
  "chats/mutations": typeof chats_mutations;
  "chats/nakafa": typeof chats_nakafa;
  "chats/queries": typeof chats_queries;
  "chats/read": typeof chats_read;
  "chats/traces/impl": typeof chats_traces_impl;
  "chats/traces/mutations": typeof chats_traces_mutations;
  "chats/traces/queries": typeof chats_traces_queries;
  "chats/traces/spec": typeof chats_traces_spec;
  "chats/utils": typeof chats_utils;
  "classes/constants": typeof classes_constants;
  "classes/forums/aggregate": typeof classes_forums_aggregate;
  "classes/forums/attachments/constants": typeof classes_forums_attachments_constants;
  "classes/forums/attachments/impl": typeof classes_forums_attachments_impl;
  "classes/forums/attachments/route": typeof classes_forums_attachments_route;
  "classes/forums/attachments/spec": typeof classes_forums_attachments_spec;
  "classes/forums/attachments/upload": typeof classes_forums_attachments_upload;
  "classes/forums/cleanup": typeof classes_forums_cleanup;
  "classes/forums/internalMutations": typeof classes_forums_internalMutations;
  "classes/forums/mutations/forums": typeof classes_forums_mutations_forums;
  "classes/forums/mutations/posts": typeof classes_forums_mutations_posts;
  "classes/forums/mutations/reactions": typeof classes_forums_mutations_reactions;
  "classes/forums/mutations/readState": typeof classes_forums_mutations_readState;
  "classes/forums/mutations/uploads": typeof classes_forums_mutations_uploads;
  "classes/forums/queries/forums": typeof classes_forums_queries_forums;
  "classes/forums/queries/pages": typeof classes_forums_queries_pages;
  "classes/forums/utils/access": typeof classes_forums_utils_access;
  "classes/forums/utils/constants": typeof classes_forums_utils_constants;
  "classes/forums/utils/mentions": typeof classes_forums_utils_mentions;
  "classes/forums/utils/postReactions": typeof classes_forums_utils_postReactions;
  "classes/forums/utils/posts": typeof classes_forums_utils_posts;
  "classes/forums/utils/reactions": typeof classes_forums_utils_reactions;
  "classes/forums/utils/readStateWrite": typeof classes_forums_utils_readStateWrite;
  "classes/forums/utils/unreadCounts": typeof classes_forums_utils_unreadCounts;
  "classes/forums/validators": typeof classes_forums_validators;
  "classes/materials/mutations": typeof classes_materials_mutations;
  "classes/materials/queries": typeof classes_materials_queries;
  "classes/materials/utils": typeof classes_materials_utils;
  "classes/mutations": typeof classes_mutations;
  "classes/queries": typeof classes_queries;
  "classes/utils": typeof classes_utils;
  "classes/validators": typeof classes_validators;
  "comments/mutations": typeof comments_mutations;
  "comments/queries": typeof comments_queries;
  "consents/current": typeof consents_current;
  "consents/impl": typeof consents_impl;
  "contentRelease/abort": typeof contentRelease_abort;
  "contentRelease/abort/budget": typeof contentRelease_abort_budget;
  "contentRelease/abort/rows": typeof contentRelease_abort_rows;
  "contentRelease/abort/runtime": typeof contentRelease_abort_runtime;
  "contentRelease/accept": typeof contentRelease_accept;
  "contentRelease/activate": typeof contentRelease_activate;
  "contentRelease/activation/candidate": typeof contentRelease_activation_candidate;
  "contentRelease/activation/complete": typeof contentRelease_activation_complete;
  "contentRelease/activation/model": typeof contentRelease_activation_model;
  "contentRelease/activation/recovery": typeof contentRelease_activation_recovery;
  "contentRelease/activation/spec": typeof contentRelease_activation_spec;
  "contentRelease/activation/validate": typeof contentRelease_activation_validate;
  "contentRelease/article": typeof contentRelease_article;
  "contentRelease/article/agent": typeof contentRelease_article_agent;
  "contentRelease/article/bucket": typeof contentRelease_article_bucket;
  "contentRelease/article/cursor": typeof contentRelease_article_cursor;
  "contentRelease/article/discovery": typeof contentRelease_article_discovery;
  "contentRelease/article/internal": typeof contentRelease_article_internal;
  "contentRelease/article/limits": typeof contentRelease_article_limits;
  "contentRelease/article/model": typeof contentRelease_article_model;
  "contentRelease/article/order": typeof contentRelease_article_order;
  "contentRelease/article/owner": typeof contentRelease_article_owner;
  "contentRelease/article/ownership": typeof contentRelease_article_ownership;
  "contentRelease/article/partition": typeof contentRelease_article_partition;
  "contentRelease/article/read": typeof contentRelease_article_read;
  "contentRelease/article/route": typeof contentRelease_article_route;
  "contentRelease/article/sitemap": typeof contentRelease_article_sitemap;
  "contentRelease/article/spec": typeof contentRelease_article_spec;
  "contentRelease/article/sync": typeof contentRelease_article_sync;
  "contentRelease/article/validation": typeof contentRelease_article_validation;
  "contentRelease/article/verify": typeof contentRelease_article_verify;
  "contentRelease/article/write": typeof contentRelease_article_write;
  "contentRelease/artifact/store": typeof contentRelease_artifact_store;
  "contentRelease/artifacts": typeof contentRelease_artifacts;
  "contentRelease/base": typeof contentRelease_base;
  "contentRelease/batch": typeof contentRelease_batch;
  "contentRelease/bucket": typeof contentRelease_bucket;
  "contentRelease/catalog": typeof contentRelease_catalog;
  "contentRelease/cleanup": typeof contentRelease_cleanup;
  "contentRelease/compact": typeof contentRelease_compact;
  "contentRelease/compact/artifacts": typeof contentRelease_compact_artifacts;
  "contentRelease/compact/rows": typeof contentRelease_compact_rows;
  "contentRelease/compact/runtime": typeof contentRelease_compact_runtime;
  "contentRelease/compact/state": typeof contentRelease_compact_state;
  "contentRelease/cursor": typeof contentRelease_cursor;
  "contentRelease/digest": typeof contentRelease_digest;
  "contentRelease/document": typeof contentRelease_document;
  "contentRelease/envelope": typeof contentRelease_envelope;
  "contentRelease/error": typeof contentRelease_error;
  "contentRelease/heads": typeof contentRelease_heads;
  "contentRelease/http/body": typeof contentRelease_http_body;
  "contentRelease/http/runtime/batch": typeof contentRelease_http_runtime_batch;
  "contentRelease/http/runtime/protected": typeof contentRelease_http_runtime_protected;
  "contentRelease/http/runtime/public": typeof contentRelease_http_runtime_public;
  "contentRelease/http/runtime/request": typeof contentRelease_http_runtime_request;
  "contentRelease/http/runtime/response": typeof contentRelease_http_runtime_response;
  "contentRelease/http/secret": typeof contentRelease_http_secret;
  "contentRelease/ingress/call": typeof contentRelease_ingress_call;
  "contentRelease/ingress/current": typeof contentRelease_ingress_current;
  "contentRelease/ingress/decode": typeof contentRelease_ingress_decode;
  "contentRelease/ingress/dispatch": typeof contentRelease_ingress_dispatch;
  "contentRelease/ingress/envelope": typeof contentRelease_ingress_envelope;
  "contentRelease/ingress/failure": typeof contentRelease_ingress_failure;
  "contentRelease/ingress/group": typeof contentRelease_ingress_group;
  "contentRelease/ingress/key": typeof contentRelease_ingress_key;
  "contentRelease/ingress/lifecycle": typeof contentRelease_ingress_lifecycle;
  "contentRelease/ingress/models": typeof contentRelease_ingress_models;
  "contentRelease/ingress/read": typeof contentRelease_ingress_read;
  "contentRelease/ingress/response": typeof contentRelease_ingress_response;
  "contentRelease/ingress/rollback": typeof contentRelease_ingress_rollback;
  "contentRelease/ingress/route": typeof contentRelease_ingress_route;
  "contentRelease/ingress/runtime/bundle": typeof contentRelease_ingress_runtime_bundle;
  "contentRelease/ingress/snapshot": typeof contentRelease_ingress_snapshot;
  "contentRelease/ingress/stage": typeof contentRelease_ingress_stage;
  "contentRelease/item": typeof contentRelease_item;
  "contentRelease/items": typeof contentRelease_items;
  "contentRelease/manifest": typeof contentRelease_manifest;
  "contentRelease/material": typeof contentRelease_material;
  "contentRelease/material/bucket": typeof contentRelease_material_bucket;
  "contentRelease/material/discovery": typeof contentRelease_material_discovery;
  "contentRelease/material/identity": typeof contentRelease_material_identity;
  "contentRelease/material/limits": typeof contentRelease_material_limits;
  "contentRelease/material/model": typeof contentRelease_material_model;
  "contentRelease/material/owner": typeof contentRelease_material_owner;
  "contentRelease/material/page": typeof contentRelease_material_page;
  "contentRelease/material/partition": typeof contentRelease_material_partition;
  "contentRelease/material/route": typeof contentRelease_material_route;
  "contentRelease/material/sitemap": typeof contentRelease_material_sitemap;
  "contentRelease/material/spec": typeof contentRelease_material_spec;
  "contentRelease/material/state": typeof contentRelease_material_state;
  "contentRelease/material/sync": typeof contentRelease_material_sync;
  "contentRelease/material/topic": typeof contentRelease_material_topic;
  "contentRelease/material/validation": typeof contentRelease_material_validation;
  "contentRelease/material/verify": typeof contentRelease_material_verify;
  "contentRelease/material/write": typeof contentRelease_material_write;
  "contentRelease/model": typeof contentRelease_model;
  "contentRelease/models": typeof contentRelease_models;
  "contentRelease/models/article": typeof contentRelease_models_article;
  "contentRelease/models/build": typeof contentRelease_models_build;
  "contentRelease/models/impact": typeof contentRelease_models_impact;
  "contentRelease/models/items": typeof contentRelease_models_items;
  "contentRelease/models/material": typeof contentRelease_models_material;
  "contentRelease/models/page": typeof contentRelease_models_page;
  "contentRelease/models/phase": typeof contentRelease_models_phase;
  "contentRelease/models/search": typeof contentRelease_models_search;
  "contentRelease/models/slot": typeof contentRelease_models_slot;
  "contentRelease/models/spec": typeof contentRelease_models_spec;
  "contentRelease/ownership": typeof contentRelease_ownership;
  "contentRelease/page": typeof contentRelease_page;
  "contentRelease/page/catalog": typeof contentRelease_page_catalog;
  "contentRelease/page/limits": typeof contentRelease_page_limits;
  "contentRelease/paging": typeof contentRelease_paging;
  "contentRelease/parse": typeof contentRelease_parse;
  "contentRelease/partner/cursor": typeof contentRelease_partner_cursor;
  "contentRelease/partner/page": typeof contentRelease_partner_page;
  "contentRelease/program": typeof contentRelease_program;
  "contentRelease/program/bucket": typeof contentRelease_program_bucket;
  "contentRelease/program/catalog": typeof contentRelease_program_catalog;
  "contentRelease/program/context": typeof contentRelease_program_context;
  "contentRelease/program/limits": typeof contentRelease_program_limits;
  "contentRelease/program/model": typeof contentRelease_program_model;
  "contentRelease/program/owner": typeof contentRelease_program_owner;
  "contentRelease/program/page": typeof contentRelease_program_page;
  "contentRelease/program/partition": typeof contentRelease_program_partition;
  "contentRelease/program/path": typeof contentRelease_program_path;
  "contentRelease/program/route": typeof contentRelease_program_route;
  "contentRelease/program/sitemap": typeof contentRelease_program_sitemap;
  "contentRelease/program/verify": typeof contentRelease_program_verify;
  "contentRelease/projection": typeof contentRelease_projection;
  "contentRelease/proof/artifact": typeof contentRelease_proof_artifact;
  "contentRelease/proof/budget": typeof contentRelease_proof_budget;
  "contentRelease/proof/catalog": typeof contentRelease_proof_catalog;
  "contentRelease/proof/commit": typeof contentRelease_proof_commit;
  "contentRelease/proof/content": typeof contentRelease_proof_content;
  "contentRelease/proof/coordinator": typeof contentRelease_proof_coordinator;
  "contentRelease/proof/failure": typeof contentRelease_proof_failure;
  "contentRelease/proof/poll": typeof contentRelease_proof_poll;
  "contentRelease/proof/read": typeof contentRelease_proof_read;
  "contentRelease/proof/routes": typeof contentRelease_proof_routes;
  "contentRelease/proof/snapshot": typeof contentRelease_proof_snapshot;
  "contentRelease/proof/spec": typeof contentRelease_proof_spec;
  "contentRelease/proof/stream": typeof contentRelease_proof_stream;
  "contentRelease/proof/verify": typeof contentRelease_proof_verify;
  "contentRelease/proof/workflow": typeof contentRelease_proof_workflow;
  "contentRelease/quran": typeof contentRelease_quran;
  "contentRelease/quran/attribution": typeof contentRelease_quran_attribution;
  "contentRelease/quran/bismillah": typeof contentRelease_quran_bismillah;
  "contentRelease/quran/catalog": typeof contentRelease_quran_catalog;
  "contentRelease/quran/chunks": typeof contentRelease_quran_chunks;
  "contentRelease/quran/document": typeof contentRelease_quran_document;
  "contentRelease/quran/facts": typeof contentRelease_quran_facts;
  "contentRelease/quran/input": typeof contentRelease_quran_input;
  "contentRelease/quran/interpretation": typeof contentRelease_quran_interpretation;
  "contentRelease/quran/limits": typeof contentRelease_quran_limits;
  "contentRelease/quran/markdown": typeof contentRelease_quran_markdown;
  "contentRelease/quran/owner": typeof contentRelease_quran_owner;
  "contentRelease/quran/reference": typeof contentRelease_quran_reference;
  "contentRelease/quran/row": typeof contentRelease_quran_row;
  "contentRelease/quran/sources": typeof contentRelease_quran_sources;
  "contentRelease/quran/spec": typeof contentRelease_quran_spec;
  "contentRelease/quran/surah": typeof contentRelease_quran_surah;
  "contentRelease/quran/translation": typeof contentRelease_quran_translation;
  "contentRelease/quran/verify": typeof contentRelease_quran_verify;
  "contentRelease/quran/view": typeof contentRelease_quran_view;
  "contentRelease/receipt": typeof contentRelease_receipt;
  "contentRelease/recovery": typeof contentRelease_recovery;
  "contentRelease/reference": typeof contentRelease_reference;
  "contentRelease/reference/agent": typeof contentRelease_reference_agent;
  "contentRelease/reference/input": typeof contentRelease_reference_input;
  "contentRelease/reference/internal": typeof contentRelease_reference_internal;
  "contentRelease/reference/read": typeof contentRelease_reference_read;
  "contentRelease/reference/spec": typeof contentRelease_reference_spec;
  "contentRelease/renderer": typeof contentRelease_renderer;
  "contentRelease/retention": typeof contentRelease_retention;
  "contentRelease/rollback": typeof contentRelease_rollback;
  "contentRelease/rollback/state": typeof contentRelease_rollback_state;
  "contentRelease/rollback/stored": typeof contentRelease_rollback_stored;
  "contentRelease/route": typeof contentRelease_route;
  "contentRelease/routes": typeof contentRelease_routes;
  "contentRelease/runtime/active": typeof contentRelease_runtime_active;
  "contentRelease/runtime/origin": typeof contentRelease_runtime_origin;
  "contentRelease/runtime/pin": typeof contentRelease_runtime_pin;
  "contentRelease/runtime/protected/dispatch": typeof contentRelease_runtime_protected_dispatch;
  "contentRelease/runtime/protected/internal": typeof contentRelease_runtime_protected_internal;
  "contentRelease/runtime/public/batch": typeof contentRelease_runtime_public_batch;
  "contentRelease/runtime/public/dispatch": typeof contentRelease_runtime_public_dispatch;
  "contentRelease/runtime/public/internal": typeof contentRelease_runtime_public_internal;
  "contentRelease/runtime/result": typeof contentRelease_runtime_result;
  "contentRelease/runtime/snapshot": typeof contentRelease_runtime_snapshot;
  "contentRelease/scope/family": typeof contentRelease_scope_family;
  "contentRelease/scope/route": typeof contentRelease_scope_route;
  "contentRelease/search/input": typeof contentRelease_search_input;
  "contentRelease/search/owner": typeof contentRelease_search_owner;
  "contentRelease/search/spec": typeof contentRelease_search_spec;
  "contentRelease/search/sync": typeof contentRelease_search_sync;
  "contentRelease/search/validation": typeof contentRelease_search_validation;
  "contentRelease/search/verify": typeof contentRelease_search_verify;
  "contentRelease/search/write": typeof contentRelease_search_write;
  "contentRelease/sitemap": typeof contentRelease_sitemap;
  "contentRelease/snapshot": typeof contentRelease_snapshot;
  "contentRelease/snapshot/batch": typeof contentRelease_snapshot_batch;
  "contentRelease/snapshot/cleanup": typeof contentRelease_snapshot_cleanup;
  "contentRelease/snapshot/manifest": typeof contentRelease_snapshot_manifest;
  "contentRelease/snapshot/program": typeof contentRelease_snapshot_program;
  "contentRelease/snapshot/quran": typeof contentRelease_snapshot_quran;
  "contentRelease/snapshot/read": typeof contentRelease_snapshot_read;
  "contentRelease/snapshot/request": typeof contentRelease_snapshot_request;
  "contentRelease/snapshot/retention": typeof contentRelease_snapshot_retention;
  "contentRelease/snapshot/rows": typeof contentRelease_snapshot_rows;
  "contentRelease/snapshot/tryout": typeof contentRelease_snapshot_tryout;
  "contentRelease/spec": typeof contentRelease_spec;
  "contentRelease/status": typeof contentRelease_status;
  "contentRelease/sync": typeof contentRelease_sync;
  "contentRelease/tryout": typeof contentRelease_tryout;
  "contentRelease/tryout/binding": typeof contentRelease_tryout_binding;
  "contentRelease/tryout/catalog": typeof contentRelease_tryout_catalog;
  "contentRelease/tryout/facts": typeof contentRelease_tryout_facts;
  "contentRelease/tryout/limits": typeof contentRelease_tryout_limits;
  "contentRelease/tryout/owner": typeof contentRelease_tryout_owner;
  "contentRelease/tryout/runtime": typeof contentRelease_tryout_runtime;
  "contentRelease/tryout/section": typeof contentRelease_tryout_section;
  "contentRelease/tryout/set": typeof contentRelease_tryout_set;
  "contentRelease/tryout/sitemap": typeof contentRelease_tryout_sitemap;
  "contentRelease/tryout/taxonomy": typeof contentRelease_tryout_taxonomy;
  "contentRelease/tryout/verify": typeof contentRelease_tryout_verify;
  "contentRelease/verify": typeof contentRelease_verify;
  "contentRelease/verify/delete": typeof contentRelease_verify_delete;
  "contentRelease/verify/item": typeof contentRelease_verify_item;
  "contentRelease/verify/upsert": typeof contentRelease_verify_upsert;
  "contentRelease/wire": typeof contentRelease_wire;
  "contents/analytics/impl": typeof contents_analytics_impl;
  "contents/analytics/spec": typeof contents_analytics_spec;
  "contents/constants": typeof contents_constants;
  "contents/context": typeof contents_context;
  "contents/graph": typeof contents_graph;
  "contents/helpers/partitions": typeof contents_helpers_partitions;
  "contents/helpers/search/documents": typeof contents_helpers_search_documents;
  "contents/helpers/search/excerpt": typeof contents_helpers_search_excerpt;
  "contents/helpers/search/groups": typeof contents_helpers_search_groups;
  "contents/helpers/search/input": typeof contents_helpers_search_input;
  "contents/helpers/search/published": typeof contents_helpers_search_published;
  "contents/helpers/search/quran/authenticate": typeof contents_helpers_search_quran_authenticate;
  "contents/helpers/search/quran/candidates": typeof contents_helpers_search_quran_candidates;
  "contents/helpers/search/quran/read": typeof contents_helpers_search_quran_read;
  "contents/helpers/search/rank": typeof contents_helpers_search_rank;
  "contents/helpers/search/read": typeof contents_helpers_search_read;
  "contents/helpers/search/result": typeof contents_helpers_search_result;
  "contents/helpers/search/terms": typeof contents_helpers_search_terms;
  "contents/helpers/search/tryout": typeof contents_helpers_search_tryout;
  "contents/metrics/apply": typeof contents_metrics_apply;
  "contents/metrics/batch": typeof contents_metrics_batch;
  "contents/metrics/refresh": typeof contents_metrics_refresh;
  "contents/mutations/analytics": typeof contents_mutations_analytics;
  "contents/mutations/popularity": typeof contents_mutations_popularity;
  "contents/mutations/views": typeof contents_mutations_views;
  "contents/popularity": typeof contents_popularity;
  "contents/queries/recent": typeof contents_queries_recent;
  "contents/queries/search": typeof contents_queries_search;
  "contents/queries/trending": typeof contents_queries_trending;
  "contents/rankings": typeof contents_rankings;
  "contents/trending/impl": typeof contents_trending_impl;
  "contents/trending/spec": typeof contents_trending_spec;
  "contents/views/context": typeof contents_views_context;
  "contents/views/impl": typeof contents_views_impl;
  "contents/views/recent": typeof contents_views_recent;
  "contents/views/signals": typeof contents_views_signals;
  "contents/views/spec": typeof contents_views_spec;
  "contents/views/target": typeof contents_views_target;
  "credits/constants": typeof credits_constants;
  "credits/helpers/state": typeof credits_helpers_state;
  "credits/mutations": typeof credits_mutations;
  crons: typeof crons;
  "customers/actions/internal": typeof customers_actions_internal;
  "customers/actions/public": typeof customers_actions_public;
  "customers/checkout/admission": typeof customers_checkout_admission;
  "customers/checkout/impl": typeof customers_checkout_impl;
  "customers/checkout/localization": typeof customers_checkout_localization;
  "customers/checkout/session": typeof customers_checkout_session;
  "customers/checkout/spec": typeof customers_checkout_spec;
  "customers/deletion/billing": typeof customers_deletion_billing;
  "customers/deletion/billingState": typeof customers_deletion_billingState;
  "customers/deletion/cleanup": typeof customers_deletion_cleanup;
  "customers/deletion/workflow": typeof customers_deletion_workflow;
  "customers/integrity/internal": typeof customers_integrity_internal;
  "customers/mutations/internal": typeof customers_mutations_internal;
  "customers/mutations/spec": typeof customers_mutations_spec;
  "customers/polar/impl": typeof customers_polar_impl;
  "customers/polar/live": typeof customers_polar_live;
  "customers/polar/spec": typeof customers_polar_spec;
  "customers/polar/target": typeof customers_polar_target;
  "customers/polar/webhook": typeof customers_polar_webhook;
  "customers/queries/internal/customer": typeof customers_queries_internal_customer;
  "customers/records": typeof customers_records;
  "customers/sync/impl": typeof customers_sync_impl;
  "customers/sync/settlement": typeof customers_sync_settlement;
  "customers/sync/spec": typeof customers_sync_spec;
  "emails/client": typeof emails_client;
  "emails/deletion": typeof emails_deletion;
  "emails/delivery": typeof emails_delivery;
  "emails/retention": typeof emails_retention;
  "emails/welcome": typeof emails_welcome;
  functions: typeof functions;
  http: typeof http;
  "learningPreferences/impl": typeof learningPreferences_impl;
  "learningPreferences/mutations": typeof learningPreferences_mutations;
  "learningPreferences/program": typeof learningPreferences_program;
  "learningPreferences/queries": typeof learningPreferences_queries;
  "lib/attempts": typeof lib_attempts;
  "lib/effect": typeof lib_effect;
  "lib/helpers/auth": typeof lib_helpers_auth;
  "lib/helpers/chat": typeof lib_helpers_chat;
  "lib/helpers/class": typeof lib_helpers_class;
  "lib/helpers/invite": typeof lib_helpers_invite;
  "lib/helpers/permissions": typeof lib_helpers_permissions;
  "lib/helpers/school": typeof lib_helpers_school;
  "lib/helpers/user": typeof lib_helpers_user;
  "lib/images": typeof lib_images;
  "lib/validators/contents": typeof lib_validators_contents;
  "lib/validators/trending": typeof lib_validators_trending;
  "lib/validators/user": typeof lib_validators_user;
  "lib/validators/vv": typeof lib_validators_vv;
  "notifications/mutations": typeof notifications_mutations;
  "notifications/queries": typeof notifications_queries;
  "onboarding/impl": typeof onboarding_impl;
  "onboarding/mutations": typeof onboarding_mutations;
  "onboarding/queries": typeof onboarding_queries;
  "onboarding/spec": typeof onboarding_spec;
  "onboarding/values": typeof onboarding_values;
  polyfills: typeof polyfills;
  "privacy/recovery": typeof privacy_recovery;
  "privacy/spec": typeof privacy_spec;
  "routes/agent/api": typeof routes_agent_api;
  "routes/agent/content": typeof routes_agent_content;
  "routes/agent/guard": typeof routes_agent_guard;
  "routes/agent/input": typeof routes_agent_input;
  "routes/agent/limit": typeof routes_agent_limit;
  "routes/agent/mcp/guard": typeof routes_agent_mcp_guard;
  "routes/agent/mcp/input": typeof routes_agent_mcp_input;
  "routes/agent/mcp/response": typeof routes_agent_mcp_response;
  "routes/agent/mcp/route": typeof routes_agent_mcp_route;
  "routes/agent/quran": typeof routes_agent_quran;
  "routes/agent/response": typeof routes_agent_response;
  "routes/agent/runtime": typeof routes_agent_runtime;
  "routes/agent/search": typeof routes_agent_search;
  "routes/agent/security": typeof routes_agent_security;
  "routes/constants": typeof routes_constants;
  "routes/middleware/requestId": typeof routes_middleware_requestId;
  "routes/polar": typeof routes_polar;
  "schools/mutations": typeof schools_mutations;
  "schools/queries": typeof schools_queries;
  "schools/slug": typeof schools_slug;
  "schools/utils": typeof schools_utils;
  "schools/validators": typeof schools_validators;
  "subscriptions/mutations": typeof subscriptions_mutations;
  "subscriptions/queries": typeof subscriptions_queries;
  "subscriptions/records/impl": typeof subscriptions_records_impl;
  "subscriptions/records/spec": typeof subscriptions_records_spec;
  "subscriptions/utils": typeof subscriptions_utils;
  "triggers/chats/chats": typeof triggers_chats_chats;
  "triggers/chats/cleanup": typeof triggers_chats_cleanup;
  "triggers/chats/messages": typeof triggers_chats_messages;
  "triggers/comments/cleanup": typeof triggers_comments_cleanup;
  "triggers/comments/commentVotes": typeof triggers_comments_commentVotes;
  "triggers/comments/comments": typeof triggers_comments_comments;
  "triggers/contents/popularity": typeof triggers_contents_popularity;
  "triggers/contents/views": typeof triggers_contents_views;
  "triggers/forums/postReactions": typeof triggers_forums_postReactions;
  "triggers/forums/posts": typeof triggers_forums_posts;
  "triggers/forums/reactions": typeof triggers_forums_reactions;
  "triggers/helpers/classes": typeof triggers_helpers_classes;
  "triggers/helpers/forumPosts": typeof triggers_helpers_forumPosts;
  "triggers/helpers/metadata": typeof triggers_helpers_metadata;
  "triggers/helpers/notifications": typeof triggers_helpers_notifications;
  "triggers/materials/cleanup": typeof triggers_materials_cleanup;
  "triggers/materials/groups": typeof triggers_materials_groups;
  "triggers/materials/materials": typeof triggers_materials_materials;
  "triggers/notifications/notifications": typeof triggers_notifications_notifications;
  "triggers/schools/classMembers": typeof triggers_schools_classMembers;
  "triggers/schools/classes": typeof triggers_schools_classes;
  "triggers/schools/cleanup": typeof triggers_schools_cleanup;
  "triggers/schools/members": typeof triggers_schools_members;
  "triggers/schools/schools": typeof triggers_schools_schools;
  "triggers/subscriptions/impl": typeof triggers_subscriptions_impl;
  "triggers/subscriptions/spec": typeof triggers_subscriptions_spec;
  "triggers/subscriptions/subscriptions": typeof triggers_subscriptions_subscriptions;
  "triggers/tryouts/scores": typeof triggers_tryouts_scores;
  "tryouts/access/impl": typeof tryouts_access_impl;
  "tryouts/access/source": typeof tryouts_access_source;
  "tryouts/access/subscription": typeof tryouts_access_subscription;
  "tryouts/attemptPage/impl": typeof tryouts_attemptPage_impl;
  "tryouts/attemptPage/spec": typeof tryouts_attemptPage_spec;
  "tryouts/catalog/destination": typeof tryouts_catalog_destination;
  "tryouts/catalog/featured": typeof tryouts_catalog_featured;
  "tryouts/catalog/hierarchy": typeof tryouts_catalog_hierarchy;
  "tryouts/catalog/metadata": typeof tryouts_catalog_metadata;
  "tryouts/catalog/published": typeof tryouts_catalog_published;
  "tryouts/catalog/row": typeof tryouts_catalog_row;
  "tryouts/catalog/selection": typeof tryouts_catalog_selection;
  "tryouts/catalog/spec": typeof tryouts_catalog_spec;
  "tryouts/mutations/access": typeof tryouts_mutations_access;
  "tryouts/mutations/attempts": typeof tryouts_mutations_attempts;
  "tryouts/mutations/expiry": typeof tryouts_mutations_expiry;
  "tryouts/mutations/responses": typeof tryouts_mutations_responses;
  "tryouts/mutations/sections": typeof tryouts_mutations_sections;
  "tryouts/progress/size": typeof tryouts_progress_size;
  "tryouts/progress/write": typeof tryouts_progress_write;
  "tryouts/queries/access": typeof tryouts_queries_access;
  "tryouts/queries/attempt": typeof tryouts_queries_attempt;
  "tryouts/queries/attemptPage": typeof tryouts_queries_attemptPage;
  "tryouts/queries/catalog": typeof tryouts_queries_catalog;
  "tryouts/queries/catalogModel": typeof tryouts_queries_catalogModel;
  "tryouts/queries/history": typeof tryouts_queries_history;
  "tryouts/queries/runtime": typeof tryouts_queries_runtime;
  "tryouts/queries/sets": typeof tryouts_queries_sets;
  "tryouts/questions": typeof tryouts_questions;
  "tryouts/response/contract": typeof tryouts_response_contract;
  "tryouts/response/evaluation": typeof tryouts_response_evaluation;
  "tryouts/response/integrity": typeof tryouts_response_integrity;
  "tryouts/response/legacy": typeof tryouts_response_legacy;
  "tryouts/response/migrate": typeof tryouts_response_migrate;
  "tryouts/response/model": typeof tryouts_response_model;
  "tryouts/response/spec": typeof tryouts_response_spec;
  "tryouts/response/validation": typeof tryouts_response_validation;
  "tryouts/response/write": typeof tryouts_response_write;
  "tryouts/route": typeof tryouts_route;
  "tryouts/runtime/access": typeof tryouts_runtime_access;
  "tryouts/runtime/attempt/page": typeof tryouts_runtime_attempt_page;
  "tryouts/runtime/attempt/sections": typeof tryouts_runtime_attempt_sections;
  "tryouts/runtime/attempt/source": typeof tryouts_runtime_attempt_source;
  "tryouts/runtime/attempt/state": typeof tryouts_runtime_attempt_state;
  "tryouts/runtime/choice": typeof tryouts_runtime_choice;
  "tryouts/runtime/completion": typeof tryouts_runtime_completion;
  "tryouts/runtime/content": typeof tryouts_runtime_content;
  "tryouts/runtime/error": typeof tryouts_runtime_error;
  "tryouts/runtime/estimate": typeof tryouts_runtime_estimate;
  "tryouts/runtime/finish": typeof tryouts_runtime_finish;
  "tryouts/runtime/irt": typeof tryouts_runtime_irt;
  "tryouts/runtime/irt/items": typeof tryouts_runtime_irt_items;
  "tryouts/runtime/irt/score": typeof tryouts_runtime_irt_score;
  "tryouts/runtime/lookup": typeof tryouts_runtime_lookup;
  "tryouts/runtime/ownership": typeof tryouts_runtime_ownership;
  "tryouts/runtime/placement": typeof tryouts_runtime_placement;
  "tryouts/runtime/response": typeof tryouts_runtime_response;
  "tryouts/runtime/result": typeof tryouts_runtime_result;
  "tryouts/runtime/scale": typeof tryouts_runtime_scale;
  "tryouts/runtime/score": typeof tryouts_runtime_score;
  "tryouts/runtime/section/questions": typeof tryouts_runtime_section_questions;
  "tryouts/runtime/section/state": typeof tryouts_runtime_section_state;
  "tryouts/runtime/sectionAttempt": typeof tryouts_runtime_sectionAttempt;
  "tryouts/runtime/selectors": typeof tryouts_runtime_selectors;
  "tryouts/runtime/set/state": typeof tryouts_runtime_set_state;
  "tryouts/runtime/signed": typeof tryouts_runtime_signed;
  "tryouts/runtime/spec": typeof tryouts_runtime_spec;
  "tryouts/score": typeof tryouts_score;
  "tryouts/score/result": typeof tryouts_score_result;
  "tryouts/sets/page": typeof tryouts_sets_page;
  "tryouts/sets/published": typeof tryouts_sets_published;
  "tryouts/sets/spec": typeof tryouts_sets_spec;
  "tryouts/start/attempt": typeof tryouts_start_attempt;
  "tryouts/start/impl": typeof tryouts_start_impl;
  "tryouts/start/scale": typeof tryouts_start_scale;
  "tryouts/start/source": typeof tryouts_start_source;
  "tryouts/start/spec": typeof tryouts_start_spec;
  "tryouts/status": typeof tryouts_status;
  "users/mutations": typeof users_mutations;
  "users/queries": typeof users_queries;
  "users/roles": typeof users_roles;
  "utils/error": typeof utils_error;
  "utils/id": typeof utils_id;
  "utils/logger": typeof utils_logger;
  "utils/number": typeof utils_number;
  "utils/polar/client": typeof utils_polar_client;
  "utils/polar/config": typeof utils_polar_config;
  "utils/polar/env": typeof utils_polar_env;
  "utils/polar/products": typeof utils_polar_products;
  "utils/polar/webhook": typeof utils_polar_webhook;
  "utils/site": typeof utils_site;
  "utils/text": typeof utils_text;
  workflow: typeof workflow;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("@repo/backend/convex/betterAuth/_generated/component.js").ComponentApi<"betterAuth">;
  agentRateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"agentRateLimiter">;
  workflow: import("@convex-dev/workflow/_generated/component.js").ComponentApi<"workflow">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
  posthog: import("@posthog/convex/_generated/component.js").ComponentApi<"posthog">;
  globalLeaderboard: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"globalLeaderboard">;
  forumPostsBySequence: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"forumPostsBySequence">;
  forumPostsByAuthorSequence: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"forumPostsByAuthorSequence">;
  learningPopularityRankings: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"learningPopularityRankings">;
};
