import registeredFunctions from "@repo/backend/confect/_generated/registered/audioStudies";

export const getAudioAndContentForScriptGeneration = registeredFunctions.audioStudies.queries.internalFunctions.getAudioAndContentForScriptGeneration;
export const getAudioForSpeechGeneration = registeredFunctions.audioStudies.queries.internalFunctions.getAudioForSpeechGeneration;
export const getContentHash = registeredFunctions.audioStudies.queries.internalFunctions.getContentHash;
export const verifyContentHash = registeredFunctions.audioStudies.queries.internalFunctions.verifyContentHash;
