import registeredFunctions from "@repo/backend/confect/_generated/registered/irt";

export const getCalibrationCacheIntegrity = registeredFunctions.irt.queries.internalFunctions.maintenance.getCalibrationCacheIntegrity;
export const getCalibrationQueueAttemptIntegrity = registeredFunctions.irt.queries.internalFunctions.maintenance.getCalibrationQueueAttemptIntegrity;
export const getCalibrationQueueEntryIntegrity = registeredFunctions.irt.queries.internalFunctions.maintenance.getCalibrationQueueEntryIntegrity;
export const getScaleQualityIntegrity = registeredFunctions.irt.queries.internalFunctions.maintenance.getScaleQualityIntegrity;
