// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { assessmentsLayer } from "@repo/backend/confect/modules/school/assessments/assessments.impl";
import { assessmentsGroup } from "@repo/backend/confect/modules/school/assessments/assessments.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(assessmentsGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(assessmentsLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
