// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { audioStudiesLayer } from "@repo/backend/confect/modules/content/audioStudies/audioStudies.impl";
import { audioStudiesGroup } from "@repo/backend/confect/modules/content/audioStudies/audioStudies.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(audioStudiesGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(audioStudiesLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
