// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { authLayer } from "@repo/backend/confect/modules/identity/auth/auth.impl";
import { authGroup } from "@repo/backend/confect/modules/identity/auth/auth.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(authGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(authLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
