// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { chatsLayer } from "@repo/backend/confect/modules/chat/chats/chats.impl";
import { chatsGroup } from "@repo/backend/confect/modules/chat/chats/chats.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(chatsGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(chatsLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
