// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { classesLayer } from "@repo/backend/confect/modules/school/classes/classes.impl";
import { classesGroup } from "@repo/backend/confect/modules/school/classes/classes.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(classesGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(classesLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
