// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { commentsLayer } from "@repo/backend/confect/modules/content/comments/comments.impl";
import { commentsGroup } from "@repo/backend/confect/modules/content/comments/comments.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(commentsGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(commentsLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
