// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { contentSyncLayer } from "@repo/backend/confect/modules/content/contentSync/contentSync.impl";
import { contentSyncGroup } from "@repo/backend/confect/modules/content/contentSync/contentSync.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(contentSyncGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(contentSyncLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
