// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { contentsLayer } from "@repo/backend/confect/modules/content/contents/contents.impl";
import { contentsGroup } from "@repo/backend/confect/modules/content/contents/contents.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(contentsGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(contentsLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
