// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { creditsLayer } from "@repo/backend/confect/modules/commerce/credits/credits.impl";
import { creditsGroup } from "@repo/backend/confect/modules/commerce/credits/credits.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(creditsGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(creditsLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
