// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { customersLayer } from "@repo/backend/confect/modules/commerce/customers/customers.impl";
import { customersGroup } from "@repo/backend/confect/modules/commerce/customers/customers.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(customersGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(customersLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
