// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { emailsLayer } from "@repo/backend/confect/modules/notifications/emails/emails.impl";
import { emailsGroup } from "@repo/backend/confect/modules/notifications/emails/emails.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(emailsGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(emailsLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
