// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { exercisesLayer } from "@repo/backend/confect/modules/learning/exercises/exercises.impl";
import { exercisesGroup } from "@repo/backend/confect/modules/learning/exercises/exercises.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(exercisesGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(exercisesLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
