// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { irtLayer } from "@repo/backend/confect/modules/tryout/irt/irt.impl";
import { irtGroup } from "@repo/backend/confect/modules/tryout/irt/irt.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(irtGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(irtLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
