// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { notificationsLayer } from "@repo/backend/confect/modules/notifications/notifications/notifications.impl";
import { notificationsGroup } from "@repo/backend/confect/modules/notifications/notifications/notifications.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(notificationsGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(notificationsLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
