// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { schoolsLayer } from "@repo/backend/confect/modules/school/schools/schools.impl";
import { schoolsGroup } from "@repo/backend/confect/modules/school/schools/schools.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(schoolsGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(schoolsLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
