// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { subjectSectionsLayer } from "@repo/backend/confect/modules/content/subjectSections/subjectSections.impl";
import { subjectSectionsGroup } from "@repo/backend/confect/modules/content/subjectSections/subjectSections.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(subjectSectionsGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(subjectSectionsLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
