// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { subscriptionsLayer } from "@repo/backend/confect/modules/commerce/subscriptions/subscriptions.impl";
import { subscriptionsGroup } from "@repo/backend/confect/modules/commerce/subscriptions/subscriptions.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(subscriptionsGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(subscriptionsLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
