// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { triggersLayer } from "@repo/backend/confect/modules/operations/triggers/triggers.impl";
import { triggersGroup } from "@repo/backend/confect/modules/operations/triggers/triggers.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(triggersGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(triggersLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
