// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { tryoutsLayer } from "@repo/backend/confect/modules/tryout/tryouts/tryouts.impl";
import { tryoutsGroup } from "@repo/backend/confect/modules/tryout/tryouts/tryouts.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(tryoutsGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(tryoutsLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
