// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { tryoutAccessLayer } from "@repo/backend/confect/modules/tryout/tryoutAccess/tryoutAccess.impl";
import { tryoutAccessGroup } from "@repo/backend/confect/modules/tryout/tryoutAccess/tryoutAccess.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(tryoutAccessGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(tryoutAccessLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
