// Generated by packages/backend/scripts/codegen/scopedRegistry.files.ts.
import { Spec } from "@confect/core";
import {
  Api,
  Impl,
  RegisteredConvexFunction,
  RegisteredFunctions,
} from "@confect/server";
import schema from "@repo/backend/confect/schema";
import { usersLayer } from "@repo/backend/confect/modules/identity/users/users.impl";
import { usersGroup } from "@repo/backend/confect/modules/identity/users/users.spec";
import { Layer } from "effect";

const api = Api.make(schema, Spec.make().add(usersGroup));

export default RegisteredFunctions.make(
  Impl.make(api).pipe(Layer.provide(usersLayer), Impl.finalize),
  RegisteredConvexFunction.make
);
