import {
  AbacusIcon,
  ApproximatelyEqualIcon,
  ArrangeByNumbersOneNineIcon,
  ArrowDataTransferHorizontalIcon,
  Calculator01Icon,
  CancelCircleIcon,
  ChartAverageIcon,
  ChartBarLineIcon,
  ChartEvaluationIcon,
  ChartHistogramIcon,
  ChartLineData01Icon,
  ChartMaximumIcon,
  ChartMediumIcon,
  CircleIcon,
  CongruentToCircleIcon,
  Coordinate02Icon,
  DivideSignCircleIcon,
  EqualSignCircleIcon,
  FirstBracketCircleIcon,
  FunctionCircleIcon,
  FunctionOfXIcon,
  FunctionSquareIcon,
  GridTableIcon,
  GroupItemsIcon,
  HierarchySquare03Icon,
  Infinity01Icon,
  MatrixIcon,
  MoreOrLessSquareIcon,
  MultiplicationSignCircleIcon,
  MultiplicationSignSquareIcon,
  NThRootCircleIcon,
  Parabola01Icon,
  PathfinderIntersectIcon,
  PercentCircleIcon,
  PercentIcon,
  PercentSquareIcon,
  PieChart04Icon,
  PiIcon,
  PlusMinusCircle01Icon,
  PlusSignSquareIcon,
  RankingIcon,
  RulerIcon,
  SecondBracketSquareIcon,
  SegmentIcon,
  SquareRootSquareIcon,
  Summation01Icon,
  SummationCircleIcon,
  SummationSquareIcon,
  TextNumberSignIcon,
  TriangleIcon,
  UngroupItemsIcon,
  VectorSquareIcon,
  XVariableSquareIcon,
} from "@hugeicons/core-free-icons";
import type { MathOperation } from "@repo/math/schema/operations";

const mathOperationIcons = {
  apart: UngroupItemsIcon,
  cancel: CancelCircleIcon,
  circle: CircleIcon,
  combination: FirstBracketCircleIcon,
  compare: CongruentToCircleIcon,
  cumulative_probability: PercentCircleIcon,
  determinant: MatrixIcon,
  differentiate: FunctionOfXIcon,
  distance: RulerIcon,
  distribution: Parabola01Icon,
  domain: XVariableSquareIcon,
  eigenvalues: FunctionSquareIcon,
  eigenvectors: VectorSquareIcon,
  evaluate: Calculator01Icon,
  expected_value: SummationSquareIcon,
  expand: PlusSignSquareIcon,
  factor: SecondBracketSquareIcon,
  gcd: AbacusIcon,
  integrate: FunctionCircleIcon,
  intersection: PathfinderIntersectIcon,
  inverse: ArrowDataTransferHorizontalIcon,
  is_prime: PiIcon,
  interval_probability: PercentSquareIcon,
  lcm: PlusMinusCircle01Icon,
  limit: Infinity01Icon,
  line: SegmentIcon,
  linear_system: HierarchySquare03Icon,
  matrix_multiply: MultiplicationSignSquareIcon,
  mean: ChartAverageIcon,
  median: ChartMediumIcon,
  midpoint: Coordinate02Icon,
  mode: ChartMaximumIcon,
  modular: DivideSignCircleIcon,
  permutation: ArrangeByNumbersOneNineIcon,
  point_probability: PercentIcon,
  prime_factorization: TextNumberSignIcon,
  product: MultiplicationSignCircleIcon,
  quartiles: ChartHistogramIcon,
  rank: RankingIcon,
  rationalize: SquareRootSquareIcon,
  roots: NThRootCircleIcon,
  rref: GridTableIcon,
  series: SummationCircleIcon,
  simplify: ApproximatelyEqualIcon,
  slope: TriangleIcon,
  solve: EqualSignCircleIcon,
  standard_deviation: ChartLineData01Icon,
  summation: Summation01Icon,
  tail_probability: PieChart04Icon,
  together: GroupItemsIcon,
  variance: ChartBarLineIcon,
  variance_probability: MoreOrLessSquareIcon,
  z_score: ChartEvaluationIcon,
} satisfies Record<MathOperation, typeof AbacusIcon>;

/** Selects the math-specific icon for each operation group. */
export function getMathIcon(operation: MathOperation) {
  return mathOperationIcons[operation];
}
