import type { Locale } from "next-intl";
import { getOgUrl } from "@/lib/utils/metadata";

const ALL_ARTWORK_LOCALES = ["en", "id", "de"] as const;
const ENGLISH_ARTWORK = ["en"] as const;

/** Reviewed public artwork grouped by stable, language-neutral identity. */
export const artworkSources = {
  "app/ask-nakafa": ALL_ARTWORK_LOCALES,
  "app/pricing": ALL_ARTWORK_LOCALES,
  "app/school": ENGLISH_ARTWORK,
  "curriculum/cambridge-international": ENGLISH_ARTWORK,
  "curriculum/merdeka": ALL_ARTWORK_LOCALES,
  "curriculum/singapore-moe": ENGLISH_ARTWORK,
  "curriculum/united-states": ENGLISH_ARTWORK,
  "grade/9": ALL_ARTWORK_LOCALES,
  "grade/10": ALL_ARTWORK_LOCALES,
  "grade/11": ALL_ARTWORK_LOCALES,
  "grade/12": ALL_ARTWORK_LOCALES,
  "grade/bachelor": ["en", "id"],
  "quran/index": ALL_ARTWORK_LOCALES,
  "subject/ai-ds": ALL_ARTWORK_LOCALES,
  "subject/arabic-language": ENGLISH_ARTWORK,
  "subject/biology": ALL_ARTWORK_LOCALES,
  "subject/chemistry": ALL_ARTWORK_LOCALES,
  "subject/computer-science": ALL_ARTWORK_LOCALES,
  "subject/economics": ALL_ARTWORK_LOCALES,
  "subject/english-language": ALL_ARTWORK_LOCALES,
  "subject/general-reasoning": ALL_ARTWORK_LOCALES,
  "subject/geography": ALL_ARTWORK_LOCALES,
  "subject/geospatial": ALL_ARTWORK_LOCALES,
  "subject/history": ALL_ARTWORK_LOCALES,
  "subject/indonesian-language": ALL_ARTWORK_LOCALES,
  "subject/informatics": ALL_ARTWORK_LOCALES,
  "subject/mathematical-reasoning": ALL_ARTWORK_LOCALES,
  "subject/mathematics": ALL_ARTWORK_LOCALES,
  "subject/physics": ALL_ARTWORK_LOCALES,
  "subject/quantitative-knowledge": ALL_ARTWORK_LOCALES,
  "subject/sociology": ALL_ARTWORK_LOCALES,
  "subject/technology-electro-medical": ALL_ARTWORK_LOCALES,
  "tryout/index": ["en", "de"],
  "tryout/indonesia/2027": ENGLISH_ARTWORK,
  "tryout/indonesia/snbt": ENGLISH_ARTWORK,
  "tryout/indonesia/tka": ENGLISH_ARTWORK,
} as const satisfies Readonly<Record<string, readonly ["en", ...Locale[]]>>;

export type ArtworkIdentity = keyof typeof artworkSources;

/** Resolves exact locale artwork, then the reviewed English default. */
export function resolveStaticArtwork(
  identity: ArtworkIdentity | undefined,
  locale: Locale
) {
  if (!identity) {
    return;
  }

  const locales = artworkSources[identity];
  const artworkLocale =
    locales.find((candidate) => candidate === locale) ?? locales[0];

  return getStaticArtworkPath(identity, artworkLocale);
}

/** Resolves static artwork or the localized generated social fallback. */
export function resolveSocialArtwork({
  identity,
  locale,
  publicPath,
}: {
  readonly identity: ArtworkIdentity | undefined;
  readonly locale: Locale;
  readonly publicPath: string;
}) {
  return resolveStaticArtwork(identity, locale) ?? getOgUrl(locale, publicPath);
}

/** Lists the complete static inventory generated by the canonical manifest. */
export function listStaticArtworkPaths() {
  return Object.entries(artworkSources).flatMap(([identity, locales]) =>
    locales.map((locale) => getStaticArtworkPath(identity, locale))
  );
}

function getStaticArtworkPath(identity: string, locale: string) {
  const separator = identity.lastIndexOf("/");
  const directory = identity.slice(0, separator);
  const key = identity.slice(separator + 1);

  return `/open-graph/${directory}/${locale}-${key}.png` as const;
}
