const CHAT_MESSAGES_PAGE_SIZE = 50;
const MAX_CHAT_MESSAGE_PARTS = 100;
const CHAT_TRANSCRIPT_REWRITE_MESSAGE_BATCH_SIZE = 25;

export {
  CHAT_MESSAGES_PAGE_SIZE,
  CHAT_TRANSCRIPT_REWRITE_MESSAGE_BATCH_SIZE,
  MAX_CHAT_MESSAGE_PARTS,
};
