import type { ProgrammingIcon } from "@repo/design-system/components/icons/simple";
import {
  siAstro,
  siBiome,
  siBower,
  siBun,
  siC,
  siCircleci,
  siCoffeescript,
  siCplusplus,
  siCss,
  siCssmodules,
  siDart,
  siDocker,
  siDocusaurus,
  siDotenv,
  siEditorconfig,
  siEslint,
  siGatsby,
  siGitignoredotio,
  siGnubash,
  siGo,
  siGraphql,
  siGrunt,
  siGulp,
  siHandlebarsdotjs,
  siHtml5,
  siJavascript,
  siJest,
  siJson,
  siLess,
  siMarkdown,
  siMdx,
  siMermaid,
  siMintlify,
  siMocha,
  siMysql,
  siNextdotjs,
  siPerl,
  siPhp,
  siPostcss,
  siPrettier,
  siPrisma,
  siPug,
  siPython,
  siR,
  siReact,
  siReadme,
  siRedis,
  siRemix,
  siRive,
  siRollupdotjs,
  siRuby,
  siRust,
  siSanity,
  siSass,
  siScala,
  siSentry,
  siShadcnui,
  siStorybook,
  siStylelint,
  siSublimetext,
  siSvelte,
  siSvg,
  siSwift,
  siTailwindcss,
  siToml,
  siTypescript,
  siVercel,
  siVite,
  siVuedotjs,
  siWebassembly,
} from "simple-icons";

export const filenameIconMap = {
  ".env": siDotenv,
  ".bowerrc": siBower,
  ".circleci/config.yml": siCircleci,
  ".editorconfig": siEditorconfig,
  ".eslintrc": siEslint,
  ".gitignore": siGitignoredotio,
  ".sublime-settings": siSublimetext,
  "*.astro": siAstro,
  "*.c": siC,
  "*.coffee": siCoffeescript,
  "*.cpp": siCplusplus,
  "*.css": siCss,
  "*.dart": siDart,
  "*.go": siGo,
  "*.graphql": siGraphql,
  "*.hbs": siHandlebarsdotjs,
  "*.html": siHtml5,
  "*.javascript": siJavascript,
  "*.js": siJavascript,
  "*.json": siJson,
  "*.less": siLess,
  "*.md": siMarkdown,
  "*.mdx": siMdx,
  "*.module.css": siCssmodules,
  "*.mustache": siHandlebarsdotjs,
  "*.php": siPhp,
  "*.pl": siPerl,
  "*.prisma": siPrisma,
  "*.pug": siPug,
  "*.py": siPython,
  "*.python": siPython,
  "*.r": siR,
  "*.rb": siRuby,
  "*.rdb": siRedis,
  "*.riv": siRive,
  "*.rs": siRust,
  "*.rust": siRust,
  "*.sass": siSass,
  "*.sc": siScala,
  "*.scala": siScala,
  "*.scss": siSass,
  "*.sh": siGnubash,
  "*.svg": siSvg,
  "*.svelte": siSvelte,
  "*.swift": siSwift,
  "*.test.js": siJest,
  "*.toml": siToml,
  "*.ts": siTypescript,
  "*.tsx": siReact,
  "*.typescript": siTypescript,
  "*.vue": siVuedotjs,
  "*.wasm": siWebassembly,
  "biome.json": siBiome,
  "bun.lockb": siBun,
  "components.json": siShadcnui,
  "docusaurus.config.js": siDocusaurus,
  Dockerfile: siDocker,
  "eslint.config.*": siEslint,
  "gatsby-config.*": siGatsby,
  "Gruntfile.*": siGrunt,
  "gulpfile.*": siGulp,
  "mintlify.json": siMintlify,
  "mocha.opts": siMocha,
  "next.config.*": siNextdotjs,
  "postcss.config.*": siPostcss,
  "prettier.config.*": siPrettier,
  "readme.md": siReadme,
  "remix.config.*": siRemix,
  "rollup.config.*": siRollupdotjs,
  "sanity.config.*": siSanity,
  "sentry.client.config.*": siSentry,
  "storybook.config.*": siStorybook,
  "stylelint.config.*": siStylelint,
  "tailwind.config.*": siTailwindcss,
  "vercel.json": siVercel,
  "vite.config.*": siVite,
} satisfies Record<string, ProgrammingIcon>;

export const languageIconMap = {
  astro: siAstro,
  bash: siGnubash,
  c: siC,
  "c++": siCplusplus,
  coffeescript: siCoffeescript,
  cpp: siCplusplus,
  css: siCss,
  dart: siDart,
  dockerfile: siDocker,
  go: siGo,
  graphql: siGraphql,
  handlebars: siHandlebarsdotjs,
  hbs: siHandlebarsdotjs,
  html: siHtml5,
  javascript: siJavascript,
  js: siJavascript,
  json: siJson,
  less: siLess,
  markdown: siMarkdown,
  md: siMarkdown,
  mdx: siMdx,
  mermaid: siMermaid,
  mysql: siMysql,
  perl: siPerl,
  php: siPhp,
  prisma: siPrisma,
  pug: siPug,
  py: siPython,
  python: siPython,
  r: siR,
  rb: siRuby,
  react: siReact,
  rs: siRust,
  ruby: siRuby,
  rust: siRust,
  sass: siSass,
  scala: siScala,
  scss: siSass,
  sh: siGnubash,
  shell: siGnubash,
  sql: siMysql,
  svg: siSvg,
  svelte: siSvelte,
  swift: siSwift,
  toml: siToml,
  ts: siTypescript,
  tsx: siReact,
  typescript: siTypescript,
  vue: siVuedotjs,
  wasm: siWebassembly,
} satisfies Record<string, ProgrammingIcon>;
